<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="operationsDescription" nsURI="http://operationsDescription/1.0"
    nsPrefix="operationsDescription">
  <eClassifiers xsi:type="ecore:EClass" name="OperationDescriptions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputParameters" upperBound="-1"
        eType="ecore:EClass ../../com.dml/model/DML.ecore#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executableScript" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputParameters" eType="ecore:EClass ../../com.dml/model/DML.ecore#//Parameter"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
