/**
 * generated by Xtext 2.18.0
 */
package com.smr.activity.dsl.serializer;

import com.smr.activity.dsl.serializer.AbstractActivityDiagramSyntacticSequencer;

@SuppressWarnings("all")
public class ActivityDiagramSyntacticSequencer extends AbstractActivityDiagramSyntacticSequencer {
}
