/**
 * generated by Xtext 2.15.0
 */
package com.capability.ui.contentassist;

import CapabilityDescription.Capability;
import com.capability.ui.contentassist.AbstractCapabilityProposalProvider;
import com.capability.validation.CapabilityValidator;
import com.google.common.base.Function;
import com.google.inject.Inject;
import java.util.function.Consumer;
import mncModel.Action;
import mncModel.ActionCommand;
import mncModel.Alarm;
import mncModel.Command;
import mncModel.DataPoint;
import mncModel.Event;
import mncModel.InterfaceDescription;
import org.eclipse.emf.common.util.BasicEList;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CapabilityProposalProvider extends AbstractCapabilityProposalProvider {
  @Inject
  private IQualifiedNameProvider qualifiedNameProvider;
  
  @Override
  public void completeActionCommand_Command(final EObject action, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    if ((action instanceof ActionCommand)) {
      Capability capability = EcoreUtil2.<Capability>getContainerOfType(action, Capability.class);
      if ((capability != null)) {
        EList<InterfaceDescription> componentInterfaces = capability.getComponentInterface();
        if ((componentInterfaces != null)) {
          BasicEList<Command> validCommandsForAction = CapabilityValidator.getCommandsFromAllInterfaces(componentInterfaces);
          if ((validCommandsForAction != null)) {
            final Consumer<Command> _function = (Command it) -> {
              String proposal = new Function<Command, QualifiedName>() {
                @Override
                public QualifiedName apply(final Command input) {
                  return CapabilityProposalProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
                }
                
                @Override
                public boolean equals(final Object object) {
                  throw new UnsupportedOperationException("TODO: auto-generated method stub");
                }
              }.apply(it).toString();
              acceptor.accept(this.createCompletionProposal(proposal, context));
            };
            validCommandsForAction.forEach(_function);
          }
        }
      }
    }
  }
  
  @Override
  public void completeAction_RaiseAlarm(final EObject action, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    if ((action instanceof Action)) {
      Capability capability = EcoreUtil2.<Capability>getContainerOfType(action, Capability.class);
      if ((capability != null)) {
        EList<InterfaceDescription> componentInterfaces = capability.getComponentInterface();
        if ((componentInterfaces != null)) {
          BasicEList<Alarm> validAlarmsForAction = CapabilityValidator.getAlarmsFromAllInterfaces(componentInterfaces);
          if ((validAlarmsForAction != null)) {
            final Consumer<Alarm> _function = (Alarm it) -> {
              String proposal = new Function<Alarm, QualifiedName>() {
                @Override
                public QualifiedName apply(final Alarm input) {
                  return CapabilityProposalProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
                }
                
                @Override
                public boolean equals(final Object object) {
                  throw new UnsupportedOperationException("TODO: auto-generated method stub");
                }
              }.apply(it).toString();
              acceptor.accept(this.createCompletionProposal(proposal, context));
            };
            validAlarmsForAction.forEach(_function);
          }
        }
      }
    }
  }
  
  @Override
  public void completeAction_PublishEvent(final EObject action, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    if ((action instanceof Action)) {
      Capability capability = EcoreUtil2.<Capability>getContainerOfType(action, Capability.class);
      if ((capability != null)) {
        EList<InterfaceDescription> componentInterfaces = capability.getComponentInterface();
        if ((componentInterfaces != null)) {
          BasicEList<Event> validEventsForAction = CapabilityValidator.getEventsFromAllInterfaces(componentInterfaces);
          if ((validEventsForAction != null)) {
            final Consumer<Event> _function = (Event it) -> {
              String proposal = new Function<Event, QualifiedName>() {
                @Override
                public QualifiedName apply(final Event input) {
                  return CapabilityProposalProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
                }
                
                @Override
                public boolean equals(final Object object) {
                  throw new UnsupportedOperationException("TODO: auto-generated method stub");
                }
              }.apply(it).toString();
              acceptor.accept(this.createCompletionProposal(proposal, context));
            };
            validEventsForAction.forEach(_function);
          }
        }
      }
    }
  }
  
  @Override
  public void completeAction_TriggerDataPoint(final EObject action, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    if ((action instanceof Action)) {
      Capability capability = EcoreUtil2.<Capability>getContainerOfType(action, Capability.class);
      if ((capability != null)) {
        EList<InterfaceDescription> componentInterfaces = capability.getComponentInterface();
        if ((componentInterfaces != null)) {
          BasicEList<DataPoint> validDataPointsForActionrAction = CapabilityValidator.getDataPointsFromAllInterfaces(componentInterfaces);
          final Consumer<DataPoint> _function = (DataPoint it) -> {
            String proposal = new Function<DataPoint, QualifiedName>() {
              @Override
              public QualifiedName apply(final DataPoint input) {
                return CapabilityProposalProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
              }
              
              @Override
              public boolean equals(final Object object) {
                throw new UnsupportedOperationException("TODO: auto-generated method stub");
              }
            }.apply(it).toString();
            acceptor.accept(this.createCompletionProposal(proposal, context));
          };
          validDataPointsForActionrAction.forEach(_function);
        }
      }
    }
  }
}
