/**
 * generated by Xtext 2.13.0
 */
package com.smr.activity.dsl.ide;

import com.smr.activity.dsl.ide.AbstractActivityDiagramIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ActivityDiagramIdeModule extends AbstractActivityDiagramIdeModule {
}
