/**
 * generated by Xtext 2.13.0
 */
package com.smr.activity.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.smr.activity.dsl.ActivityDiagramRuntimeModule;
import com.smr.activity.dsl.ActivityDiagramStandaloneSetup;
import com.smr.activity.dsl.ide.ActivityDiagramIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ActivityDiagramIdeSetup extends ActivityDiagramStandaloneSetup {
  @Override
  public Injector createInjector() {
    ActivityDiagramRuntimeModule _activityDiagramRuntimeModule = new ActivityDiagramRuntimeModule();
    ActivityDiagramIdeModule _activityDiagramIdeModule = new ActivityDiagramIdeModule();
    return Guice.createInjector(Modules2.mixin(_activityDiagramRuntimeModule, _activityDiagramIdeModule));
  }
}
