/*
 * generated by Xtext 2.13.0
 */
package com.dml.dsl.ide


/**
 * Use this class to register ide components.
 */
class DmlIdeModule extends AbstractDmlIdeModule {
    def Class<? extends org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider>
        bindIdeContentProposalProvider() {
        DmlIdeContentProposalProvider
    }
}
