# About dialog contributions for the KIDE Modelling Studio.
aboutText=%blurb
windowImage=icons/kide32.png
featureImage=icons/kide32.png
aboutImage=icons/about.png
appName=KIDE Modelling Studio
tipsAndTricksHref=https://github.com/amarbanerjee23/KIDE#readme
