source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               plugin.properties,\
               plugin_customization.ini,\
               about.ini,\
               about.mappings,\
               about.properties,\
               splash.bmp,\
               icons/,\
               css/,\
               templates/
