/**
 * generated by Xtext 2.15.0
 */
package com.operation.dsl.ui;

import com.operation.dsl.ui.AbstractOperationUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OperationUiModule extends AbstractOperationUiModule {
  public OperationUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
