/*
 * generated by Xtext 2.13.0
 */
package com.smr.activity.dsl.ide

import com.google.inject.Guice
import com.smr.activity.dsl.ActivityDiagramRuntimeModule
import com.smr.activity.dsl.ActivityDiagramStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ActivityDiagramIdeSetup extends ActivityDiagramStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ActivityDiagramRuntimeModule, new ActivityDiagramIdeModule))
	}
	
}
