/*
 * generated by Xtext 2.13.0
 */
package com.smr.activity.dsl.ide

import com.smr.activity.dsl.ide.highlighting.ActivityDiagramLspSemanticHighlightingCalculator
import com.smr.activity.dsl.ide.hover.ActivityDiagramLspHoverService
import com.smr.activity.dsl.ide.quickfix.ActivityDiagramCodeActionService
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2
import org.eclipse.xtext.ide.server.hover.IHoverService
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator

/**
 * KIDE-owned IDE bindings layered on the generated Activity services.
 */
class ActivityDiagramIdeModule extends AbstractActivityDiagramIdeModule {

    def Class<? extends ICodeActionService2> bindICodeActionService2() {
        ActivityDiagramCodeActionService
    }

    def Class<? extends IHoverService> bindIHoverService() {
        ActivityDiagramLspHoverService
    }

    def Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
        ActivityDiagramLspSemanticHighlightingCalculator
    }
}
