/*
 * generated by Xtext 2.13.0
 */
package com.smr.activity.dsl.ide


/**
 * Use this class to register ide components.
 */
class ActivityDiagramIdeModule extends AbstractActivityDiagramIdeModule {
}
