/*
 * generated by Xtext 2.15.0
 */
package com.mncml.dsl.formatting2

import mncModel.CommandResponseBlock
import mncModel.ControlNode
import mncModel.InterfaceDescription
import mncModel.Model
import mncModel.Transition
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import com.mncml.dsl.services.MncGrammarAccess
import com.google.inject.Inject
import mncModel.SubscribableItemList
import mncModel.EventBlock
import mncModel.AlarmBlock
import mncModel.DataPointBlock
import mncModel.Action
import mncModel.Command
import mncModel.Event
import mncModel.Alarm
import mncModel.DataPoint
import mncModel.utility.OperatingStateUtility
import mncModel.Validation

class MncFormatter extends AbstractFormatter2 {

	@Inject 
	MncGrammarAccess access

	def dispatch void format(InterfaceDescription id, extension IFormattableDocument document) {
		println(id.name) 
	id.regionFor.keyword(access.interfaceDescriptionAccess.interfaceDescriptionKeyword_1).prepend[newLine]
	id.regionFor.assignment(access.interfaceDescriptionAccess.nameAssignment_2).append[newLine]
	id.regionFor.assignment(access.interfaceDescriptionAccess.usesAssignment_3_1).append[newLine]
	id.regionFor.assignment(access.interfaceDescriptionAccess.usesAssignment_3_2_1).append[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.commaKeyword_3_2_0).append[newLine]
	 
	id.regionFor.keyword(access.interfaceDescriptionAccess.leftCurlyBracketKeyword_4).append[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.leftCurlyBracketKeyword_5_0_1_0_1).append[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.leftCurlyBracketKeyword_5_1_1).append[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.leftCurlyBracketKeyword_5_3_1).append[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.leftCurlyBracketKeyword_5_4_1).append[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.leftCurlyBracketKeyword_5_5_1).append[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.leftCurlyBracketKeyword_5_5_1).append[newLine]
	
	id.regionFor.keyword(access.interfaceDescriptionAccess.rightCurlyBracketKeyword_5_0_1_1).prepend[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.rightCurlyBracketKeyword_5_1_3).prepend[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.rightCurlyBracketKeyword_5_2_3).prepend[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.rightCurlyBracketKeyword_5_3_3).prepend[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.rightCurlyBracketKeyword_5_4_3).prepend[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.rightCurlyBracketKeyword_5_5_3).prepend[newLine]
	id.regionFor.keyword(access.interfaceDescriptionAccess.rightCurlyBracketKeyword_6).prepend[newLine]
		
	if(id.commands!==null)
		id.regionFor.keyword(access.interfaceDescriptionAccess.commandsKeyword_5_2_0).prepend[newLine]
		for(com: id.commands)
			com.format
		
	if(id.events!==null)
		id.regionFor.keyword(access.interfaceDescriptionAccess.eventsKeyword_5_3_0).prepend[newLine]
		for(event : id.events)
			event.format
			
	if(id.dataPoints!==null)
		id.regionFor.keyword(access.interfaceDescriptionAccess.dataPointsKeyword_5_0_1_0_0).prepend[newLine]
		for(dp:id.dataPoints)
			dp.format
			
	if(id.alarms!==null)
		id.regionFor.keyword(access.interfaceDescriptionAccess.alarmsKeyword_5_1_0).prepend[newLine]
		for(alarm :id.alarms)
			alarm.format
			
	if(id.operatingStatesUtility!==null)
		id.regionFor.keyword(access.interfaceDescriptionAccess.operatingStatesKeyword_5_5_0).prepend[newLine]
		id.operatingStatesUtility.format
			
	if(id.subscribedItems!==null)
		id.subscribedItems.format
	}
	 
	def dispatch format(OperatingStateUtility opsu, extension IFormattableDocument document){
		opsu.regionFor.keyword(access.operatingStateUtilityAccess.startStatesKeyword_2_0.prepend[newLine])
		opsu.regionFor.keyword(access.operatingStateUtilityAccess.startStatesKeyword_2_0.append[newLine])
		opsu.regionFor.keyword(access.operatingStateUtilityAccess.endStatesKeyword_3_0.prepend[newLine])
		opsu.regionFor.keyword(access.operatingStateUtilityAccess.endStatesKeyword_3_0.append[newLine])
	}
	
	def dispatch format(Command com, extension IFormattableDocument document){
		com.regionFor.keyword(access.commandAccess.rightSquareBracketKeyword_5.append[newLine])
	}
	
	def dispatch format(Event event, extension IFormattableDocument document){
		event.regionFor.keyword(access.eventAccess.rightSquareBracketKeyword_5.append[newLine])
	}
	def dispatch format(Alarm alarm, extension IFormattableDocument document){
		alarm.regionFor.keyword(access.alarmAccess.rightSquareBracketKeyword_6.append[newLine])
	}
	def dispatch format(DataPoint dp, extension IFormattableDocument document){
		dp.regionFor.keyword(access.dataPointAccess.rightSquareBracketKeyword_7.append[newLine])
	}
	  
	def dispatch void format(SubscribableItemList list, extension IFormattableDocument document) {
		list.regionFor.keyword(access.subscribableItemListAccess.subscribableItemListKeyword_1).append[newLine]
		list.regionFor.keyword(access.subscribableItemListAccess.leftCurlyBracketKeyword_2).append[newLine]
		list.regionFor.keyword(access.subscribableItemListAccess.leftCurlyBracketKeyword_2).prepend[newLine]
		list.regionFor.keyword(access.subscribableItemListAccess.subscribedEventsKeyword_3_0).prepend[newLine]
		list.regionFor.keyword(access.subscribableItemListAccess.subscribedAlarmsKeyword_4_0).prepend[newLine]
		list.regionFor.keyword(access.subscribableItemListAccess.subscribedDataPointsKeyword_5_0).prepend[newLine]
		list.regionFor.keyword(access.subscribableItemListAccess.rightCurlyBracketKeyword_6).prepend[newLine]
		list.regionFor.keyword(access.subscribableItemListAccess.rightCurlyBracketKeyword_6).append[newLine]
	}

	def dispatch void format(ControlNode cn, extension IFormattableDocument document) {
		println(cn.name)
		cn.regionFor.keyword(access.controlNodeAccess.controlNodeKeyword_1).prepend[newLine]
		cn.regionFor.assignment(access.controlNodeAccess.nameAssignment_2).append[newLine]
		
		cn.regionFor.keyword(access.controlNodeAccess.leftCurlyBracketKeyword_4).append[newLine]
		
		cn.regionFor.keyword(access.controlNodeAccess.leftCurlyBracketKeyword_5_1_1).append[newLine]
		cn.regionFor.keyword(access.controlNodeAccess.leftCurlyBracketKeyword_5_2_1).append[newLine]
		cn.regionFor.keyword(access.controlNodeAccess.leftCurlyBracketKeyword_5_3_1).append[newLine]
		cn.regionFor.keyword(access.controlNodeAccess.leftCurlyBracketKeyword_5_4_1).append[newLine]
		
		
		cn.regionFor.keyword(access.controlNodeAccess.rightCurlyBracketKeyword_6).append[newLine]
		cn.regionFor.keyword(access.controlNodeAccess.rightCurlyBracketKeyword_5_1_3).append[newLine]
		cn.regionFor.keyword(access.controlNodeAccess.rightCurlyBracketKeyword_5_2_3).append[newLine]
		cn.regionFor.keyword(access.controlNodeAccess.rightCurlyBracketKeyword_5_3_3).append[newLine]
		cn.regionFor.keyword(access.controlNodeAccess.rightCurlyBracketKeyword_5_4_3).append[newLine]
		
		cn.commandResponseBlocks.forEach[it.format]
		cn.eventBlocks.forEach[it.format]
		cn.alarmBlocks.forEach[it.format]
		cn.dataPointBlocks.forEach[it.format]

	}

	
	def dispatch void format(CommandResponseBlock cr, extension IFormattableDocument document) {
		
		cr.regionFor.keyword(access.commandResponseBlockAccess.commandKeyword_1).prepend[newLine]
		cr.regionFor.assignment(access.commandResponseBlockAccess.commandAssignment_2).append[newLine]
		
		cr.regionFor.keyword(access.commandResponseBlockAccess.leftCurlyBracketKeyword_3).append[newLine]
		cr.regionFor.keyword(access.commandResponseBlockAccess.rightCurlyBracketKeyword_6_4).append[newLine]
		cr.regionFor.keyword(access.commandResponseBlockAccess.rightCurlyBracketKeyword_7).append[newLine]
		
		cr.regionFor.keyword(access.commandResponseBlockAccess.leftCurlyBracketKeyword_3).append[newLine]
		cr.regionFor.keyword(access.commandResponseBlockAccess.leftCurlyBracketKeyword_6_2).append[newLine]
		
		cr.regionFor.keyword(access.commandResponseBlockAccess.rightCurlyBracketKeyword_6_4).append[newLine]
		cr.regionFor.keyword(access.commandResponseBlockAccess.rightCurlyBracketKeyword_7).append[newLine]

		cr.validationRules.forEach[it.format]
		cr.validationRules.forEach[it.onSuccessAction.format]
		cr.action.format
	}
	
	def dispatch void format(Validation vaidation, extension IFormattableDocument document) {
		vaidation.regionFor.keyword(access.validationAccess.validateKeyword_1).prepend[newLine]
		vaidation.regionFor.keyword(access.validationAccess.validateKeyword_1).append[newLine]
	}
	
	def dispatch void format(EventBlock ev, extension IFormattableDocument document) {
		ev.regionFor.keyword(access.eventBlockAccess.leftCurlyBracketKeyword_3).append[newLine]
		ev.regionFor.keyword(access.eventBlockAccess.rightCurlyBracketKeyword_6).append[newLine]
		ev.action.format
		ev.validationRules.forEach[it.onSuccessAction.format]
	}
	
	def dispatch void format(AlarmBlock al, extension IFormattableDocument document) {
		al.regionFor.keyword(access.alarmBlockAccess.leftCurlyBracketKeyword_3).append[newLine]
		al.regionFor.keyword(access.alarmBlockAccess.rightCurlyBracketKeyword_6).append[newLine]
		al.validationRules.forEach[it.onSuccessAction.format]
		al.action.format
	}
	
	def dispatch void format(DataPointBlock dp, extension IFormattableDocument document) {
		dp.regionFor.keyword(access.dataPointBlockAccess.leftCurlyBracketKeyword_4).append[newLine]
		dp.regionFor.keyword(access.dataPointBlockAccess.rightCurlyBracketKeyword_7).append[newLine]
		dp.validationRules.forEach[it.onSuccessAction.format]
		dp.action.format
	}
	
	def dispatch void format(Action ac, extension IFormattableDocument document) {
		ac.regionFor.keyword(access.actionAccess.leftCurlyBracketKeyword_2).append[newLine]
		
		
		ac.regionFor.keyword(access.actionAccess.rightCurlyBracketKeyword_9).append[newLine]
		
		ac.regionFor.keyword(access.actionAccess.leftSquareBracketKeyword_3_2).append[newLine]
		ac.regionFor.keyword(access.actionAccess.leftSquareBracketKeyword_4_2).append[newLine]
		ac.regionFor.keyword(access.actionAccess.leftSquareBracketKeyword_5_2).append[newLine]
		ac.regionFor.keyword(access.actionAccess.leftSquareBracketKeyword_7_2).append[newLine]
		ac.regionFor.keyword(access.actionAccess.leftSquareBracketKeyword_8_2).append[newLine]
		
		ac.regionFor.keyword(access.actionAccess.rightSquareBracketKeyword_3_4).append[newLine]
		ac.regionFor.keyword(access.actionAccess.rightSquareBracketKeyword_4_4).append[newLine]
		ac.regionFor.keyword(access.actionAccess.rightSquareBracketKeyword_5_4).append[newLine]
		ac.regionFor.keyword(access.actionAccess.rightSquareBracketKeyword_6_4).append[newLine]
		ac.regionFor.keyword(access.actionAccess.rightSquareBracketKeyword_7_4).append[newLine]
		ac.regionFor.keyword(access.actionAccess.rightSquareBracketKeyword_8_4).append[newLine]
			
		ac.regionFor.keyword(access.actionAccess.commandsKeyword_4_1).append[newLine]
		ac.regionFor.keyword(access.actionAccess.eventsKeyword_5_1).append[newLine]
		ac.regionFor.keyword(access.actionAccess.dataKeyword_6_1).append[newLine]
		ac.regionFor.keyword(access.actionAccess.alarmsKeyword_3_1).append[newLine]
		ac.regionFor.keyword(access.actionAccess.statesKeyword_8_1).append[newLine]
		
		if(ac.fireCommand!==null)
			for(a : ac.fireCommand)
				a.format
				
	
		if(ac.raiseAlarm!==null)
			for(a : ac.raiseAlarm)
				a.format
		
		if(ac.publishEvent!==null)
			for(a : ac.publishEvent)
				a.format
		
		if(ac.triggerDataPoint!==null)
			for(a : ac.triggerDataPoint)
				a.format
				
		if(ac.transitionStates!==null)
			for(a : ac.transitionStates)
				a.format
				
				
		interior(
			ac.regionFor.keyword(access.actionAccess.leftSquareBracketKeyword_3_2).append[newLine],
			ac.regionFor.keyword(access.actionAccess.rightSquareBracketKeyword_3_4).append[newLine]	
		)[indent]
	}
	
	def dispatch void format(Transition tr, extension IFormattableDocument document) {
		
		
		tr.regionFor.keyword(access.transitionAccess.currentStateKeyword_1).prepend[newLine]
		tr.regionFor.keyword(access.transitionAccess.equalsSignGreaterThanSignKeyword_4).append[newLine]
		tr.regionFor.assignment(access.transitionAccess.currentStateAssignment_2_0_0).append[newLine]
		tr.regionFor.keyword(access.transitionAccess.commaKeyword_2_0_1_0).append[newLine]
		tr.regionFor.assignment(access.transitionAccess.currentStateAssignment_2_0_1_1).append[newLine]
		tr.regionFor.assignment(access.transitionAccess.nextStateAssignment_6).append[newLine]
	}

// TODO: implement for InterfaceDescription, CommandResponseBlockUtility, EventBlockUtility, AlarmBlockUtility, DataPointBlockUtility, ResponseBlockUtility, ResponseBlock, CommandResponseBlock, CommandTriggerCondition, CommandDistributionUtility, Command, TransitionUtility, Event, ResponseTranslation, ResponseTranslationRule, CommandValidation, CheckParameterCondition, Response, Alarm, DataPoint, DataPointValidCondition, Transition, OperatingState, Action, CommandTranslation, ResponseValidation, EventBlock, EventTriggerCondition, EventHandling, AlarmBlock, AlarmTriggerCondition, AlarmHandling, DataPointBlock, DataPointTriggerCondition, DataPointHandling, DataPointUtility, AlarmUtility, CommandUtility, EventUtility, ResponseUtility, StateUtility
}
