/**
 * generated by Xtext 2.13.0
 */
package com.dml.dsl.ide;

import com.dml.dsl.ide.AbstractDmlIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DmlIdeModule extends AbstractDmlIdeModule {
}
