/**
 * generated by Xtext 2.13.0
 */
package com.dml.dsl.ide;

import com.dml.dsl.DmlRuntimeModule;
import com.dml.dsl.DmlStandaloneSetup;
import com.dml.dsl.ide.DmlIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DmlIdeSetup extends DmlStandaloneSetup {
  @Override
  public Injector createInjector() {
    DmlRuntimeModule _dmlRuntimeModule = new DmlRuntimeModule();
    DmlIdeModule _dmlIdeModule = new DmlIdeModule();
    return Guice.createInjector(Modules2.mixin(_dmlRuntimeModule, _dmlIdeModule));
  }
}
