/**
 * generated by Xtext 2.13.0
 */
package com.smr.activity.dsl.scoping;

import activityDiagramModel.Activity;
import activityDiagramModel.Outcome;
import com.google.common.base.Function;
import com.google.inject.Inject;
import com.smr.activity.dsl.validation.ActivityDiagramValidator;
import dataModelPackage.Parameter;
import mncModel.AbstractInterfaceItems;
import mncModel.AbstractOutcomeItems;
import org.eclipse.emf.common.util.BasicEList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.resource.impl.ResourceDescriptionsProvider;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ActivityDiagramScopeProvider extends AbstractDeclarativeScopeProvider {
  @Inject
  private IQualifiedNameProvider qualifiedNameProvider;
  
  @Inject
  private ResourceDescriptionsProvider resourceDescriptionsProvider;
  
  private QualifiedName simpleName(final EObject object) {
    QualifiedName qualified = this.qualifiedNameProvider.getFullyQualifiedName(object);
    if (qualified == null || qualified.getSegmentCount() == 0) {
      return null;
    }
    return QualifiedName.create(qualified.getLastSegment());
  }
  
  public IScope scope_Outcome_outcomeParameter(final Outcome outcome, final EReference ref) {
    BasicEList<Parameter> _candidateParametersForOutcome = ActivityDiagramValidator.getCandidateParametersForOutcome(outcome);
    return Scopes.<Parameter>scopeFor(_candidateParametersForOutcome, 
      new Function<Parameter, QualifiedName>() {
        @Override
        public QualifiedName apply(final Parameter outcome) {
          return ActivityDiagramScopeProvider.this.simpleName(outcome);
        }
        
        @Override
        public boolean equals(final Object object) {
          throw new UnsupportedOperationException("TODO: auto-generated method stub");
        }
      }, 
      IScope.NULLSCOPE);
  }
  
  public IScope scope_Outcome_capabilityOutcome(final Outcome outcome, final EReference ref) {
    BasicEList<AbstractOutcomeItems> _candidateCapabilityOutcomes = ActivityDiagramValidator.getCandidateCapabilityOutcomes(outcome);
    return Scopes.<AbstractOutcomeItems>scopeFor(_candidateCapabilityOutcomes, 
      new Function<AbstractOutcomeItems, QualifiedName>() {
        @Override
        public QualifiedName apply(final AbstractOutcomeItems outcome) {
          return ActivityDiagramScopeProvider.this.simpleName(outcome);
        }
        
        @Override
        public boolean equals(final Object object) {
          throw new UnsupportedOperationException("TODO: auto-generated method stub");
        }
      }, 
      IScope.NULLSCOPE);
  }
  
  public IScope scope_Activity_useControlCapabilities(final Activity activity, final EReference ref) {
    BasicEList<AbstractInterfaceItems> _candidateAbstractItemsAsControlCapabilities = ActivityDiagramValidator.getCandidateAbstractItemsAsControlCapabilities(activity);
    return Scopes.<AbstractInterfaceItems>scopeFor(_candidateAbstractItemsAsControlCapabilities, 
      new Function<AbstractInterfaceItems, QualifiedName>() {
        @Override
        public QualifiedName apply(final AbstractInterfaceItems outcome) {
          return ActivityDiagramScopeProvider.this.simpleName(outcome);
        }
        
        @Override
        public boolean equals(final Object object) {
          throw new UnsupportedOperationException("TODO: auto-generated method stub");
        }
      }, 
      IScope.NULLSCOPE);
  }
}
