/**
 * generated by Xtext 2.15.0
 */
package com.mncml.dsl.serializer;

import com.mncml.dsl.serializer.AbstractMncSemanticSequencer;

@SuppressWarnings("all")
public class MncSemanticSequencer extends AbstractMncSemanticSequencer {
}
