/*
 * generated by Xtext 2.15.0
 */

package com.mncml.dsl.validation

import com.google.inject.Inject
import dataModelPackage.BoolValue
import dataModelPackage.DataModelPackage
import dataModelPackage.FloatValue
import dataModelPackage.IntValue
import dataModelPackage.Parameter
import dataModelPackage.SimpleType
import dataModelPackage.StringValue
import java.util.List
import mncModel.Action
import mncModel.Address
import mncModel.Alarm
import mncModel.AlarmBlock
import mncModel.CheckParameterCondition
import mncModel.Command
import mncModel.CommandResponseBlock
import mncModel.ControlNode
import mncModel.DataPointBlock
import mncModel.Event
import mncModel.EventBlock
import mncModel.InterfaceDescription
import mncModel.MncModelPackage
import mncModel.Model
import mncModel.OperatingState
import mncModel.Port
import mncModel.Response
import mncModel.ResponseBlock
import mncModel.SubscribableItemList
import mncModel.System
import org.eclipse.emf.common.util.BasicEList
import org.eclipse.emf.ecore.util.EcoreUtil
import org.eclipse.xtext.EcoreUtil2
import org.eclipse.xtext.naming.IQualifiedNameProvider
import org.eclipse.xtext.resource.impl.ResourceDescriptionsProvider
import org.eclipse.xtext.validation.Check

import static extension org.eclipse.xtext.EcoreUtil2.*
import mncModel.Validation
import java.util.ArrayList
import mncModel.DataPoint

class MncValidator extends AbstractMncValidator {

	@Inject
	extension IQualifiedNameProvider qualifiedNameProvider

	@Inject
	ResourceDescriptionsProvider resourceDescriptionsProvider

	public static val INVALID_NAME = 'invalidName'
	public static val CONTROL_NODE_CAPITAL = 'Control Node should start with a capital letter'
	public static val CONTROL_NODE_HAS_NAME = 'Control Node must have a name'
	public static val INTERFACE_DESCRIPTION_HAS_NAME = 'Interface Description must have a name'
	public static val INT = "int"
	public static val STRING = "string"
	public static val BOOLEAN = "boolean"
	public static val FLOAT = "float"

	@Check
	def checkSystemStartsWithCapital(ControlNode controlNode) {
		if (!Character.isUpperCase(controlNode.name.charAt(0))) {

			warning(CONTROL_NODE_CAPITAL, MncModelPackage.Literals.CONTROL_NODE__NAME, INVALID_NAME)
		}
	}

	@Check
	def checkSystemHasName(Model model) {
		var count = 0
		for (System system : model.systems) {
			if (system instanceof ControlNode && (system as ControlNode).name === null) {
				error(CONTROL_NODE_HAS_NAME, MncModelPackage.Literals.MODEL__SYSTEMS, count)
			} else if (system instanceof InterfaceDescription && (system as InterfaceDescription).name === null) {
				error(INTERFACE_DESCRIPTION_HAS_NAME, MncModelPackage.Literals.MODEL__SYSTEMS, count)
			}
			count++
		}
	}

	@Check
	def checkNoDuplicateControlNode(ControlNode controlNode) {
		var proxyControlNode = controlNode
		for (ControlNode cnode : getAllControlNode()) {
			proxyControlNode = cnode
			if (cnode.eIsProxy) {
				proxyControlNode = EcoreUtil.resolve(proxyControlNode, controlNode) as ControlNode
			}
			if (proxyControlNode != controlNode && proxyControlNode.name === controlNode.name)
				error(
					"Duplicate Control Node '" + controlNode.name + "' in resource '" + proxyControlNode.eResource.URI +
						"'", controlNode, MncModelPackage.eINSTANCE.controlNode_Name)
		}
	}

	def getAllControlNode() {
		var List<ControlNode> listOfControlNodes = newArrayList()
		for (eObjectDescription : resourceDescriptionsProvider.createResourceDescriptions.getExportedObjectsByType(
			MncModelPackage.Literals.CONTROL_NODE))
			listOfControlNodes.add(eObjectDescription.EObjectOrProxy as ControlNode)
		listOfControlNodes
	}

	@Check
	def checkNoDuplicateInterfaceDescription(InterfaceDescription interfaceDescription) {
		if (interfaceDescription.getContainerOfType((Model)).systems.exists [
			if (it instanceof InterfaceDescription) {
				val auxilliaryInterfaceDescription = (it as InterfaceDescription)
				auxilliaryInterfaceDescription != interfaceDescription &&
					auxilliaryInterfaceDescription.name === interfaceDescription.name
			} else {
			}
		])
			error("Duplicate Interface Description '" + interfaceDescription.name + "'",
				MncModelPackage.eINSTANCE.interfaceDescription_Name)
	}

	@Check
	def checkParameterValueWithType(SimpleType parameter) {
		var type = parameter.type.getName
		var value = parameter.value
		var flag = false
		switch (type) {
			case INT: if(!(value instanceof IntValue)) flag = true
			case BOOLEAN: if(!(value instanceof BoolValue)) flag = true
			case FLOAT: if(!(value instanceof FloatValue || value instanceof IntValue)) flag = true
			case STRING: if(!(value instanceof StringValue)) flag = true
		}
		if (value === null)
			flag = false
		if (flag)
			error("Parameter value does not match with the parameter type '" + type + "'",
				DataModelPackage.Literals.SIMPLE_TYPE__VALUE)

	}

	@Check
	def checkChildNodeDifferentFromParentNode(ControlNode controlNode) {
		var count = 0
		var position = 0
		var bool = false
		for (childControlNode : controlNode.childNodes) {
			if (childControlNode === controlNode) {
				bool = true
				position = count
			}
			count++
		}
		if (bool)
			error("Child node cannot be same as the parent node", MncModelPackage.Literals.CONTROL_NODE__CHILD_NODES,
				position)
	}

	@Check
	def checkNoDuplicateParameter(SimpleType parameter) {

		// In Commands
		if (parameter.getContainerOfType((Command)).parameters.exists [
			if (it instanceof SimpleType)
				(it as SimpleType) != parameter && (it as SimpleType).name === parameter.name
			else {
			}
		])
			error("Duplicate Parameter '" + parameter.name + "'", DataModelPackage.eINSTANCE.simpleType_Name)
		// In Response
		else if (parameter.getContainerOfType((Response)).parameters.exists [
			if (it instanceof SimpleType)
				(it as SimpleType) != parameter && (it as SimpleType).name === parameter.name
			else {
			}
		])
			error("Duplicate Parameter '" + parameter.name + "'", DataModelPackage.eINSTANCE.simpleType_Name)
		else
			// In Systems
			(parameter.getContainerOfType((InterfaceDescription)).dataPoints.exists [
				it != parameter && it.name === parameter.name
			])
		error("Duplicate Parameter '" + parameter.name + "'", DataModelPackage.eINSTANCE.simpleType_Name)

	}

	@Check
	def checkNoDuplicateCommand(Command command) {
		var List<Command> listOfCommands = command.getContainerOfType(InterfaceDescription).commands
		if (!listOfCommands.isNullOrEmpty && listOfCommands.exists[it != command && it.name === command.name])
			error("Duplicate Command '" + command.name + "'", MncModelPackage.eINSTANCE.abstractInterfaceItems_Name)
	}

	@Check
	def checkNoDuplicateResponse(Response response) {
		var List<Response> listOfResponses = response.getContainerOfType((InterfaceDescription)).responses
		if (listOfResponses.exists[it != response && it.name === response.name])
			error("Duplicate Response '" + response.name + "'", MncModelPackage.eINSTANCE.abstractInterfaceItems_Name)
	}

	@Check
	def checkNoDuplicateAlarm(Alarm alarm) {
		var List<Alarm> listOfAlarms = alarm.getContainerOfType((InterfaceDescription)).alarms
		if (listOfAlarms.exists[it != alarm && it.name === alarm.name])
			error("Duplicate Alarm '" + alarm.name + "'", MncModelPackage.eINSTANCE.abstractInterfaceItems_Name)
	}

	@Check
	def checkNoDuplicateEvent(Event event) {
		var List<Event> listOfEvents = event.getContainerOfType((InterfaceDescription)).events
		if (listOfEvents.exists[it != event && it.name === event.name])
			error("Duplicate Event '" + event.name + "'", MncModelPackage.eINSTANCE.abstractInterfaceItems_Name)
	}

	@Check
	def checkNoDuplicateCommandResponse(InterfaceDescription interfaceDescription) {

		for (Command command : interfaceDescription.commands) {
			for (Response response : interfaceDescription.responses) {
				if (command.name === response.name) {
					error("Command '" + command.name + "' is duplicate of Response '" + response.name + "'", command,
						MncModelPackage.Literals.ABSTRACT_INTERFACE_ITEMS__NAME)
					error("Response '" + response.name + "' is duplicate of Command '" + command.name + "'", response,
						MncModelPackage.Literals.ABSTRACT_INTERFACE_ITEMS__NAME)
				}
			}

		}
	}

	@Check
	def checkNoDuplicateState(OperatingState state) {
		if (state.getContainerOfType((InterfaceDescription)).operatingStatesUtility.operatingStates.exists [
			it != state && it.name === state.name
		])
			error("Duplicate state '" + state.name + "'", MncModelPackage.eINSTANCE.operatingState_Name)
	}

//	@Check
//	def checkTranslatedCommandsInChildNodes(CommandTranslation commandTranslation) {
//		var count = 0
//		var bool = false
//		val listOfCommands = commandTranslation.translatedCommands
//		for (command : listOfCommands) {
//			for (controlNode : commandTranslation.getContainerOfType(ControlNode).childNodes) {
//				if (controlNode.interfaceDescription.commands.exists[it === command]) {
//					bool = true;
//				}
//				for (interfaceDescription : controlNode.interfaceDescription.uses) {
//					if (interfaceDescription.commands.exists[it === command]) {
//						bool = true;
//					}
//				}
//			}
//			if (!bool)
//				error("Command does not map to any child node commands.",
//					MncModelPackage.Literals.COMMAND_TRANSLATION__TRANSLATED_COMMANDS, count)
//			count++
//			bool = false
//		}
//
//	}

	static def getCandidateParametersForCheckParameterCondition(CheckParameterCondition checkParameterCondition) {
		var validation = checkParameterCondition
		var responseBlock = EcoreUtil2.getContainerOfType(validation, ResponseBlock)
		var commandBlock = EcoreUtil2.getContainerOfType(validation, CommandResponseBlock)
		var eventBlock = EcoreUtil2.getContainerOfType(validation, EventBlock)
		var alarmBlock = EcoreUtil2.getContainerOfType(validation, AlarmBlock)
		val List<Parameter> existingValidCheckParameterParameters = newArrayList()
		var existingValdationRules = new BasicEList<Validation>
		var List<Parameter> validListOfParameters = newArrayList()

		if (responseBlock !== null && responseBlock.validationRules !== null) {
			existingValdationRules.addAll(responseBlock.validationRules)
			if (responseBlock.response !== null && responseBlock.response.parameters !== null) {
				validListOfParameters.addAll(responseBlock.response.parameters)
			}
		} else if (commandBlock !== null && commandBlock.validationRules !== null) {
			existingValdationRules.addAll(commandBlock.validationRules)
			if (commandBlock.command !== null && commandBlock.command.parameters !== null) {
				validListOfParameters.addAll(commandBlock.command.parameters)
			}
		} else if (eventBlock !== null && eventBlock.validationRules !== null) {
			existingValdationRules.addAll(eventBlock.validationRules)
			if (eventBlock.event !== null && eventBlock.event.parameters !== null) {
				validListOfParameters.addAll(eventBlock.event.parameters)
			}

		} else if (alarmBlock !== null && alarmBlock.validationRules !== null) {
			existingValdationRules.addAll(alarmBlock.validationRules)
			if (alarmBlock.alarm !== null && alarmBlock.alarm.parameters !== null) {
				validListOfParameters.addAll(alarmBlock.alarm.parameters)
			}
		}

		for (rule : existingValdationRules) {
			rule.parametersValidationRules.forEach [ r |
				if (r !== null) { 
					existingValidCheckParameterParameters.addAll(r.parameter)
				}

			]

		}

//		validListOfParameters.removeAll(existingValidCheckParameterParameters)
		return validListOfParameters
	}

	@Check
	def checkParameterinCheckParameterCondition(CheckParameterCondition checkParameterCondition) {
		if (checkParameterCondition.parameter !== null) {

			var responseBlock = EcoreUtil2.getContainerOfType(checkParameterCondition, ResponseBlock)
			var commandBlock = EcoreUtil2.getContainerOfType(checkParameterCondition, CommandResponseBlock)
			var eventBlock = EcoreUtil2.getContainerOfType(checkParameterCondition, EventBlock)
			var alarmBlock = EcoreUtil2.getContainerOfType(checkParameterCondition, AlarmBlock)
			var dataPointBlock = EcoreUtil2.getContainerOfType(checkParameterCondition, DataPointBlock)
			var itemName = new ArrayList<String>
			var itemType = new String()
			if (responseBlock !== null) {
				itemName += responseBlock.response.name
				itemType = 'Response'
			} else if (commandBlock !== null) {
				itemName += commandBlock.command.name
				itemType = 'Command'
			} else if (eventBlock !== null) {
				itemName += eventBlock.event.name
				itemType = 'Event'
			} else if (alarmBlock !== null) {
				itemName += alarmBlock.alarm.name
				itemType = 'Alarm'
			} else if (dataPointBlock !== null) {
				for(dp:dataPointBlock.dataPoint)
				{
					itemName += dp.name
				}
				itemType = 'DataPoint'
			}

			if (!itemType.equals('DataPoint')) {
				var validParameters = getCandidateParametersForCheckParameterCondition(checkParameterCondition)
				if (!validParameters.containsAll(checkParameterCondition.parameter)) {
					error(
					'''Parameter «for(para:checkParameterCondition.parameter) para.fullyQualifiedName» does'nt belong to «itemType» «itemName» ''',
						MncModelPackage.Literals.CHECK_PARAMETER_CONDITION__PARAMETER)
				}
			} else {
//				var id = dataPointBlock.getContainerOfType(ControlNode).interfaceDescription
//				var listOfDatapoints = id.dataPoints !== null ? id.dataPoints : new BasicEList<DataPoint>
//				listOfDatapoints += id.subscribedItems!==null && id.subscribedItems.subscribedDataPoints!==null?
//				 id.subscribedItems.subscribedDataPoints: new BasicEList<DataPoint>
//				val dataPoints = dataPointBlock.dataPoint
//				if (!listOfDatapoints.containsAll(dataPoints) ){
//					error('''DataPoint «for(dp:dataPoints) dp.name» is unexpected here''',
//						MncModelPackage.Literals.CHECK_PARAMETER_CONDITION__PARAMETER)
//				}
			}

		}
	}

	@Check
	def checkValidIPAdrress(Address address) {
		val String[] segments = address.ipaddress.split("\\.")
		var bool = false
		for (j : 0 ..< segments.size) {
			var value = Integer.parseInt(segments.get(j))
			if (value < 0 || value > 255)
				bool = true
		}
		if (bool)
			error("IPAddress '" + address.ipaddress + "' is invalid.", MncModelPackage.Literals.ADDRESS__IPADDRESS)
	}

	@Check
	def checkPortNumber(Port port) {
		if (port.value < 1 || port.value > 65535)
			error("Port value '" + port.value + "' is invalid.", MncModelPackage.Literals.PORT__VALUE)
	}

	@Check
	def checkNoAssociatedInterfaceDescriptioninControlNode(ControlNode controlNode) {
		if (controlNode.interfaceDescription === null)
			error("Control Node must have an associated Interface Description.",
				MncModelPackage.Literals.CONTROL_NODE__NAME)
	}

	@Check
	def checkNoCommandCallsItSelfInTransition(Action action) {
		var commandResponseBlock = action.getContainerOfType(CommandResponseBlock)
		if (commandResponseBlock !== null && commandResponseBlock.action !== null && commandResponseBlock.action.transitionStates !== null) {
			var transitions = commandResponseBlock.action.transitionStates
			for (transition : transitions) {
				if (transition.entryAction !== null && transition.entryAction.fireCommand !== null) {
					if (transition.entryAction.fireCommand.contains(commandResponseBlock.command) ||
						transition.exitAction.fireCommand.contains(commandResponseBlock.command)) {
						warning("Command calls itself as part of transition actions.",
							MncModelPackage.Literals.ACTION__FIRE_COMMAND)
					}
				}

			}
		}

	}

	@Check
	def checkNoCommandCallsItAction(Action action) {
		var commandResponseBlock = EcoreUtil2.getContainerOfType(action, CommandResponseBlock)
		var eventBlock = EcoreUtil2.getContainerOfType(action, EventBlock)
		var alarmBlock = EcoreUtil2.getContainerOfType(action, AlarmBlock)
		var dataPointBlock = EcoreUtil2.getContainerOfType(action, DataPointBlock)

		if (commandResponseBlock !== null) {
			if (action.fireCommand !== null && action.fireCommand.contains(commandResponseBlock.command)) {
				warning("Command fired itself in actions.", MncModelPackage.Literals.ACTION__FIRE_COMMAND)
			}
		}
		if (eventBlock !== null) {
			if (action.publishEvent !== null && action.publishEvent.contains(eventBlock.event)) {
				warning("Event published itself in actions.", MncModelPackage.Literals.ACTION__PUBLISH_EVENT)
			}
		}
		if (alarmBlock !== null) {
			if (action.raiseAlarm !== null && action.raiseAlarm.contains(alarmBlock.alarm)) {
				warning("Alarm raises itself in actions.", MncModelPackage.Literals.ACTION__RAISE_ALARM)
			}
		}
		if (dataPointBlock !== null) {
			if (action.triggerDataPoint !== null && action.triggerDataPoint.contains(dataPointBlock.dataPoint)) {
				warning("DataPoint triggers itself in actions.", MncModelPackage.Literals.ACTION__TRIGGER_DATA_POINT)
			}
		}

	}

	@Check
	def checkNoDuplicateAlarmBlockInControlNode(AlarmBlock alarmBlock) {
		var listOfAlarmBlocks = alarmBlock.getContainerOfType((ControlNode)).alarmBlocks
		if (listOfAlarmBlocks.exists [
			it != alarmBlock && it.alarm === alarmBlock.alarm
		])
			error("Duplicate Alarm Block'" + alarmBlock.alarm.name + "'", MncModelPackage.Literals.ALARM_BLOCK__ALARM)
	}

	@Check
	def checkNoDuplicateCommandResponseBlockInControlNode(CommandResponseBlock commandResponseBlock) {
		if (commandResponseBlock.getContainerOfType((ControlNode)).commandResponseBlocks.exists [
			it != commandResponseBlock && it.command === commandResponseBlock.command
		])
			error("Duplicate Command Block'" + commandResponseBlock.command.name + "'",
				MncModelPackage.Literals.COMMAND_RESPONSE_BLOCK__COMMAND)
	}

	@Check
	def checkNoDuplicateEventBlockInControlNode(EventBlock eventBlock) {
		if (eventBlock.getContainerOfType((ControlNode)).eventBlocks.exists [
			it != eventBlock && it.event === eventBlock.event
		])
			error("Duplicate Event Block'" + eventBlock.event.name + "'", MncModelPackage.Literals.EVENT_BLOCK__EVENT)
	}

	@Check
	def checkNoDuplicateDataPointBlockInControlNode(DataPointBlock dataPointBlock) {
		if (dataPointBlock.getContainerOfType((ControlNode)).dataPointBlocks.exists [
			it != dataPointBlock && it.dataPoint === dataPointBlock.dataPoint
		])
			error('''Duplicate Alarm Block'" + «for(dp:dataPointBlock.dataPoint)dp.name»''',
				MncModelPackage.Literals.DATA_POINT_BLOCK__DATA_POINT)
	}

	@Check
	def checkNoEventBlockIsBlank(EventBlock eventBlock) {
		var event = eventBlock.event
		if (event.name === null) {
			error("Event Block Must Have a Event Name.", MncModelPackage.Literals.EVENT_BLOCK__EVENT)
		} else {
			if (eventBlock.validationRules === null)
				warning("Event Block Should Have Event Details.", MncModelPackage.Literals.EVENT_BLOCK__EVENT)
		}
	}

	@Check
	def checkNoAlarmBlockIsBlank(AlarmBlock alarmBlock) {
		var alarm = alarmBlock.alarm
		if (alarm.name === null) {
			error("Alarm Block Must Have a Alarm Name.", MncModelPackage.Literals.ALARM_BLOCK__ALARM)
		} else {
			if (alarmBlock.validationRules === null)
				warning("Alarm Block Should Have Alarm Details.", MncModelPackage.Literals.ALARM_BLOCK__ALARM)
		}
	}

	@Check
	def checkIfActionsAreRepeatedOrNot(Action action) {
		var actionEvents = action.publishEvent
		var actionAlarms = action.raiseAlarm
		var actionCommands = action.fireCommand

		for (var m = 0; m < actionCommands.size; m++) {
			for (var n = m + 1; n < actionCommands.size; n++) {
				if (actionCommands.get(n).equals(actionCommands.get(m))) {
					warning("Repeating Commands in Action", MncModelPackage.Literals.ACTION__FIRE_COMMAND)
				}
			}
		}

		for (var m = 0; m < actionEvents.size; m++) {
			for (var n = m + 1; n < actionEvents.size; n++) {
				if (actionEvents.get(n).equals(actionEvents.get(m))) {
					warning("Repeating Events in Action", MncModelPackage.Literals.ACTION__PUBLISH_EVENT)
				}
			}
		}

		for (var m = 0; m < actionAlarms.size; m++) {
			for (var n = m + 1; n < actionAlarms.size; n++) {
				if (actionAlarms.get(n).equals(actionAlarms.get(m))) {
					warning("Repeating Alarms in Action", MncModelPackage.Literals.ACTION__RAISE_ALARM)
				}
			}
		}
	}

//	@Check
//	def checkNoChildNodesOrCommandsForCommandTranslation(CommandTranslation commandTranslation) {
//		var controlNodes = commandTranslation.getContainerOfType(ControlNode).childNodes
//		if (controlNodes.size === 0)
//			warning(
//				"No Child Control Nodes to translate commands",
//				commandTranslation.getContainerOfType(CommandResponseBlock),
//				MncModelPackage.Literals.COMMAND_RESPONSE_BLOCK__COMMAND_TRANSLATION
//			)
//		else if (controlNodes.forall [
//			it.interfaceDescription.commands === null || it.interfaceDescription.commands.size === 0
//		])
//			warning(
//				"Child Control Node do not contain any commands for translation",
//				commandTranslation.getContainerOfType(CommandResponseBlock),
//				MncModelPackage.Literals.COMMAND_RESPONSE_BLOCK__COMMAND_TRANSLATION
//			)
//	}

//	@Check
//	def checkNoChildNodesOrCommandsForResponseTranslation(ResponseAggregation responseTranslation) {
//		var controlNodes = responseTranslation.getContainerOfType(ControlNode).childNodes
//		if (controlNodes.size === 0)
//			warning(
//				"No Child Control Nodes to translate commands",
//				responseTranslation.getContainerOfType(ResponseBlock),
//				MncModelPackage.Literals.RESPONSE_BLOCK__RESPONSE_AGGREGATION
//			)
//		else if (controlNodes.forall [
//			it.interfaceDescription.responses === null || it.interfaceDescription.responses.size === 0
//		])
//			warning(
//				"Child Control Node do not contain any commands for translation",
//				responseTranslation.getContainerOfType(ResponseBlock),
//				MncModelPackage.Literals.RESPONSE_BLOCK__RESPONSE_AGGREGATION
//			)
//	}
	@Check
	def checkSubscribedItemsDifferentFromInterfaceDescriptionItems(SubscribableItemList subscribableItemList) {
		val interfaceDescription = subscribableItemList.getContainerOfType(InterfaceDescription)
		// Validate for Subscribed Alarms
		if (subscribableItemList.subscribedAlarms !== null) {
			for (alarm : subscribableItemList.subscribedAlarms) {
				if (interfaceDescription.alarms.contains(alarm)) {
					error("Subscribed Alarms should be different from the alarm in Interface Description",
						MncModelPackage.Literals.SUBSCRIBABLE_ITEM_LIST__SUBSCRIBED_ALARMS,
						subscribableItemList.subscribedAlarms.indexOf(alarm))
				}
				if (!alarm.isPublish) {
					error("Alarm is not published", MncModelPackage.Literals.SUBSCRIBABLE_ITEM_LIST__SUBSCRIBED_ALARMS,
						subscribableItemList.subscribedAlarms.indexOf(alarm))
				}

			}
		}

		// Validate for Subscribed Events
		if (subscribableItemList.subscribedEvents !== null) {
			for (event : subscribableItemList.subscribedEvents) {
				if (interfaceDescription.events.contains(event)) {
					error("Subscribed Events should be different from the event in Interface Description",
						MncModelPackage.Literals.SUBSCRIBABLE_ITEM_LIST__SUBSCRIBED_EVENTS,
						subscribableItemList.subscribedEvents.indexOf(event))
				}
				if (!event.isPublish) {
					error("Event is not published", MncModelPackage.Literals.SUBSCRIBABLE_ITEM_LIST__SUBSCRIBED_ALARMS,
						subscribableItemList.subscribedEvents.indexOf(event))
				}

			}
		}

		// Validate for Subscribed DataPoints
		if (subscribableItemList.subscribedDataPoints !== null) {
			for (dataPoint : subscribableItemList.subscribedDataPoints) {
				if (interfaceDescription.dataPoints.contains(dataPoint)) {
					error("Subscribed DataPoints should be different from the datapoint in Interface Description",
						MncModelPackage.Literals.SUBSCRIBABLE_ITEM_LIST__SUBSCRIBED_DATA_POINTS,
						subscribableItemList.subscribedDataPoints.indexOf(dataPoint))
				}
				if (!dataPoint.publish) {
					error("Datapoint is not published",
						MncModelPackage.Literals.SUBSCRIBABLE_ITEM_LIST__SUBSCRIBED_ALARMS,
						subscribableItemList.subscribedDataPoints.indexOf(dataPoint))
				}

			}
		}

	}

}
