/**
 * generated by Xtext 2.15.0
 */
package com.mncml.dsl.scoping;

import com.google.common.base.Function;
import com.google.inject.Inject;
import dataModelPackage.Parameter;
import java.util.List;
import java.util.function.Consumer;
import mncModel.Action;
import mncModel.ActionCommand;
import mncModel.Alarm;
import mncModel.AlarmBlock;
import mncModel.CheckParameterCondition;
import mncModel.Command;
import mncModel.CommandResponseBlock;
import mncModel.ControlNode;
import mncModel.DataPoint;
import mncModel.DataPointBlock;
import mncModel.Event;
import mncModel.EventBlock;
import mncModel.InterfaceDescription;
import mncModel.MncModelPackage;
import mncModel.Model;
import mncModel.OperatingState;
import mncModel.ParameterTranslation;
import mncModel.Response;
import mncModel.ResponseAggregationRule;
import mncModel.ResponseBlock;
import mncModel.SubscribableItemList;
import mncModel.Transition;
import mncModel.utility.OperatingStateUtility;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.resource.impl.ResourceDescriptionsProvider;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;

@SuppressWarnings("all")
public class MncScopeProvider extends AbstractDeclarativeScopeProvider implements IScopeProvider {
  @Inject
  private IQualifiedNameProvider qualifiedNameProvider;
  
  @Inject
  private ResourceDescriptionsProvider resourceDescriptionsProvider;
  
  public List<ControlNode> getAllControlNode() {
    List<ControlNode> _xblockexpression = null;
    {
      List<ControlNode> listOfControlNodes = CollectionLiterals.<ControlNode>newArrayList();
      Iterable<IEObjectDescription> _exportedObjectsByType = this.resourceDescriptionsProvider.createResourceDescriptions().getExportedObjectsByType(
        MncModelPackage.Literals.CONTROL_NODE);
      for (final IEObjectDescription eObjectDescription : _exportedObjectsByType) {
        EObject _eObjectOrProxy = eObjectDescription.getEObjectOrProxy();
        listOfControlNodes.add(((ControlNode) _eObjectOrProxy));
      }
      _xblockexpression = listOfControlNodes;
    }
    return _xblockexpression;
  }
  
  public List<InterfaceDescription> getAllInterfaces() {
    List<InterfaceDescription> _xblockexpression = null;
    {
      List<InterfaceDescription> listOfId = CollectionLiterals.<InterfaceDescription>newArrayList();
      Iterable<IEObjectDescription> _exportedObjectsByType = this.resourceDescriptionsProvider.createResourceDescriptions().getExportedObjectsByType(
        MncModelPackage.Literals.INTERFACE_DESCRIPTION);
      for (final IEObjectDescription eObjectDescription : _exportedObjectsByType) {
        EObject _eObjectOrProxy = eObjectDescription.getEObjectOrProxy();
        listOfId.add(((InterfaceDescription) _eObjectOrProxy));
      }
      _xblockexpression = listOfId;
    }
    return _xblockexpression;
  }
  
  public List<OperatingState> getCandidateOperatingStatesForTransitions(final Transition transition) {
    List<OperatingState> _xblockexpression = null;
    {
      List<OperatingState> listOfOperatingStates = CollectionLiterals.<OperatingState>newArrayList();
      InterfaceDescription interfaceDescription = EcoreUtil2.<ControlNode>getContainerOfType(transition, ControlNode.class).getInterfaceDescription();
      OperatingStateUtility _operatingStatesUtility = interfaceDescription.getOperatingStatesUtility();
      boolean _tripleNotEquals = (_operatingStatesUtility != null);
      if (_tripleNotEquals) {
        listOfOperatingStates.addAll(interfaceDescription.getOperatingStatesUtility().getOperatingStates());
      }
      EList<InterfaceDescription> _uses = interfaceDescription.getUses();
      for (final InterfaceDescription interfaceDescriptionInUses : _uses) {
        OperatingStateUtility _operatingStatesUtility_1 = interfaceDescriptionInUses.getOperatingStatesUtility();
        boolean _tripleNotEquals_1 = (_operatingStatesUtility_1 != null);
        if (_tripleNotEquals_1) {
          listOfOperatingStates.addAll(interfaceDescriptionInUses.getOperatingStatesUtility().getOperatingStates());
        }
      }
      _xblockexpression = listOfOperatingStates;
    }
    return _xblockexpression;
  }
  
  public List<Command> getCandidateCommands(final ControlNode controlNode) {
    List<Command> _xblockexpression = null;
    {
      InterfaceDescription interfaceDescription = controlNode.getInterfaceDescription();
      List<Command> listOfCommands = CollectionLiterals.<Command>newArrayList();
      EList<Command> _commands = interfaceDescription.getCommands();
      boolean _tripleNotEquals = (_commands != null);
      if (_tripleNotEquals) {
        listOfCommands.addAll(interfaceDescription.getCommands());
      }
      EList<InterfaceDescription> _uses = interfaceDescription.getUses();
      for (final InterfaceDescription interfaceDescriptionInUses : _uses) {
        EList<Command> _commands_1 = interfaceDescriptionInUses.getCommands();
        boolean _tripleNotEquals_1 = (_commands_1 != null);
        if (_tripleNotEquals_1) {
          listOfCommands.addAll(interfaceDescriptionInUses.getCommands());
        }
      }
      _xblockexpression = listOfCommands;
    }
    return _xblockexpression;
  }
  
  public List<Alarm> getCandidateAlarms(final InterfaceDescription interfaceDescription) {
    List<Alarm> _xblockexpression = null;
    {
      List<Alarm> listOfAlarms = CollectionLiterals.<Alarm>newArrayList();
      EList<Alarm> _alarms = interfaceDescription.getAlarms();
      boolean _tripleNotEquals = (_alarms != null);
      if (_tripleNotEquals) {
        listOfAlarms.addAll(interfaceDescription.getAlarms());
      }
      SubscribableItemList _subscribedItems = interfaceDescription.getSubscribedItems();
      boolean _tripleNotEquals_1 = (_subscribedItems != null);
      if (_tripleNotEquals_1) {
        EList<Alarm> _subscribedAlarms = interfaceDescription.getSubscribedItems().getSubscribedAlarms();
        boolean _tripleNotEquals_2 = (_subscribedAlarms != null);
        if (_tripleNotEquals_2) {
          listOfAlarms.addAll(interfaceDescription.getSubscribedItems().getSubscribedAlarms());
        }
      }
      EList<InterfaceDescription> _uses = interfaceDescription.getUses();
      for (final InterfaceDescription interfaceDescriptionInUses : _uses) {
        EList<Alarm> _alarms_1 = interfaceDescriptionInUses.getAlarms();
        boolean _tripleNotEquals_3 = (_alarms_1 != null);
        if (_tripleNotEquals_3) {
          listOfAlarms.addAll(interfaceDescriptionInUses.getAlarms());
        }
      }
      _xblockexpression = listOfAlarms;
    }
    return _xblockexpression;
  }
  
  public List<Event> getCandidateEvents(final InterfaceDescription interfaceDescription) {
    List<Event> _xblockexpression = null;
    {
      List<Event> listOfEvents = CollectionLiterals.<Event>newArrayList();
      EList<Event> _events = interfaceDescription.getEvents();
      boolean _tripleNotEquals = (_events != null);
      if (_tripleNotEquals) {
        listOfEvents.addAll(interfaceDescription.getEvents());
      }
      SubscribableItemList _subscribedItems = interfaceDescription.getSubscribedItems();
      boolean _tripleNotEquals_1 = (_subscribedItems != null);
      if (_tripleNotEquals_1) {
        EList<Event> _subscribedEvents = interfaceDescription.getSubscribedItems().getSubscribedEvents();
        boolean _tripleNotEquals_2 = (_subscribedEvents != null);
        if (_tripleNotEquals_2) {
          listOfEvents.addAll(interfaceDescription.getSubscribedItems().getSubscribedEvents());
        }
      }
      EList<InterfaceDescription> _uses = interfaceDescription.getUses();
      for (final InterfaceDescription interfaceDescriptionInUses : _uses) {
        EList<Event> _events_1 = interfaceDescriptionInUses.getEvents();
        boolean _tripleNotEquals_3 = (_events_1 != null);
        if (_tripleNotEquals_3) {
          listOfEvents.addAll(interfaceDescriptionInUses.getEvents());
        }
      }
      _xblockexpression = listOfEvents;
    }
    return _xblockexpression;
  }
  
  public List<Response> getCandidateResponses(final InterfaceDescription interfaceDescription) {
    List<Response> _xblockexpression = null;
    {
      List<Response> listOfResponses = CollectionLiterals.<Response>newArrayList();
      EList<Response> _responses = interfaceDescription.getResponses();
      boolean _tripleNotEquals = (_responses != null);
      if (_tripleNotEquals) {
        listOfResponses.addAll(interfaceDescription.getResponses());
      }
      EList<InterfaceDescription> _uses = interfaceDescription.getUses();
      for (final InterfaceDescription interfaceDescriptionInUses : _uses) {
        EList<Response> _responses_1 = interfaceDescriptionInUses.getResponses();
        boolean _tripleNotEquals_1 = (_responses_1 != null);
        if (_tripleNotEquals_1) {
          listOfResponses.addAll(interfaceDescriptionInUses.getResponses());
        }
      }
      _xblockexpression = listOfResponses;
    }
    return _xblockexpression;
  }
  
  public List<DataPoint> getCandidateDataPoints(final InterfaceDescription interfaceDescription) {
    List<DataPoint> _xblockexpression = null;
    {
      List<DataPoint> listOfDataPoints = CollectionLiterals.<DataPoint>newArrayList();
      EList<DataPoint> _dataPoints = interfaceDescription.getDataPoints();
      boolean _tripleNotEquals = (_dataPoints != null);
      if (_tripleNotEquals) {
        listOfDataPoints.addAll(interfaceDescription.getDataPoints());
      }
      SubscribableItemList _subscribedItems = interfaceDescription.getSubscribedItems();
      boolean _tripleNotEquals_1 = (_subscribedItems != null);
      if (_tripleNotEquals_1) {
        EList<DataPoint> _subscribedDataPoints = interfaceDescription.getSubscribedItems().getSubscribedDataPoints();
        boolean _tripleNotEquals_2 = (_subscribedDataPoints != null);
        if (_tripleNotEquals_2) {
          listOfDataPoints.addAll(interfaceDescription.getSubscribedItems().getSubscribedDataPoints());
        }
      }
      EList<InterfaceDescription> _uses = interfaceDescription.getUses();
      for (final InterfaceDescription interfaceDescriptionInUses : _uses) {
        EList<DataPoint> _dataPoints_1 = interfaceDescriptionInUses.getDataPoints();
        boolean _tripleNotEquals_3 = (_dataPoints_1 != null);
        if (_tripleNotEquals_3) {
          listOfDataPoints.addAll(interfaceDescriptionInUses.getDataPoints());
        }
      }
      _xblockexpression = listOfDataPoints;
    }
    return _xblockexpression;
  }
  
  public List<ControlNode> getCandidateChildNodes(final ControlNode controlNode) {
    List<ControlNode> _xblockexpression = null;
    {
      List<ControlNode> listOfControlNodes = CollectionLiterals.<ControlNode>newArrayList();
      Model model = EcoreUtil2.<Model>getContainerOfType(controlNode, Model.class);
      EList<mncModel.System> _systems = model.getSystems();
      for (final mncModel.System system : _systems) {
        if (((system instanceof ControlNode) && (system != controlNode))) {
          listOfControlNodes.add(((ControlNode) system));
        }
      }
      _xblockexpression = listOfControlNodes;
    }
    return _xblockexpression;
  }
  
  public List<Response> getCandidateResponsesFromChildNode(final ControlNode controlNode) {
    List<Response> _xblockexpression = null;
    {
      List<Response> listOfResponses = CollectionLiterals.<Response>newArrayList();
      EList<ControlNode> _childNodes = controlNode.getChildNodes();
      for (final ControlNode ccn : _childNodes) {
        {
          EList<Response> _responses = ccn.getInterfaceDescription().getResponses();
          boolean _tripleNotEquals = (_responses != null);
          if (_tripleNotEquals) {
            listOfResponses.addAll(ccn.getInterfaceDescription().getResponses());
          }
          EList<InterfaceDescription> _uses = ccn.getInterfaceDescription().getUses();
          for (final InterfaceDescription interfaceDescriptionInUses : _uses) {
            listOfResponses.addAll(interfaceDescriptionInUses.getResponses());
          }
        }
      }
      _xblockexpression = listOfResponses;
    }
    return _xblockexpression;
  }
  
  public List<Command> getCandidateCommandsFromChildNode(final ControlNode controlNode) {
    List<Command> _xblockexpression = null;
    {
      List<Command> listOfCommands = CollectionLiterals.<Command>newArrayList();
      EList<ControlNode> _childNodes = controlNode.getChildNodes();
      for (final ControlNode childControlNode : _childNodes) {
        {
          EList<Command> _commands = childControlNode.getInterfaceDescription().getCommands();
          boolean _tripleNotEquals = (_commands != null);
          if (_tripleNotEquals) {
            listOfCommands.addAll(childControlNode.getInterfaceDescription().getCommands());
          }
          EList<InterfaceDescription> _uses = childControlNode.getInterfaceDescription().getUses();
          for (final InterfaceDescription interfaceDescriptionInUses : _uses) {
            listOfCommands.addAll(interfaceDescriptionInUses.getCommands());
          }
        }
      }
      _xblockexpression = listOfCommands;
    }
    return _xblockexpression;
  }
  
  public IScope scope_Transition_currentState(final Transition transition, final EReference ref) {
    return Scopes.scopeFor(
      this.getCandidateOperatingStatesForTransitions(transition), 
      IScope.NULLSCOPE);
  }
  
  public IScope scope_Transition_nextState(final Transition transition, final EReference ref) {
    return Scopes.scopeFor(
      this.getCandidateOperatingStatesForTransitions(transition), 
      IScope.NULLSCOPE);
  }
  
  public IScope scope_Action_command(final Action action, final EReference ref) {
    IScope _xblockexpression = null;
    {
      ControlNode controlNode = EcoreUtil2.<ControlNode>getContainerOfType(action, ControlNode.class);
      List<Command> listOfCommands = this.getCandidateCommands(controlNode);
      listOfCommands.addAll(this.getCandidateCommandsFromChildNode(controlNode));
      _xblockexpression = Scopes.<Command>scopeFor(listOfCommands, 
        new Function<Command, QualifiedName>() {
          @Override
          public QualifiedName apply(final Command input) {
            return MncScopeProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
          }
          
          @Override
          public boolean equals(final Object object) {
            throw new UnsupportedOperationException("TODO: auto-generated method stub");
          }
        }, 
        IScope.NULLSCOPE);
    }
    return _xblockexpression;
  }
  
  public IScope scope_ResponseBlock_response(final ResponseBlock responseBlock, final EReference ref) {
    IScope _xblockexpression = null;
    {
      ControlNode controlNode = EcoreUtil2.<ControlNode>getContainerOfType(responseBlock, ControlNode.class);
      List<Response> _candidateResponses = this.getCandidateResponses(controlNode.getInterfaceDescription());
      _xblockexpression = Scopes.<Response>scopeFor(_candidateResponses, 
        new Function<Response, QualifiedName>() {
          @Override
          public QualifiedName apply(final Response input) {
            return MncScopeProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
          }
          
          @Override
          public boolean equals(final Object object) {
            throw new UnsupportedOperationException("TODO: auto-generated method stub");
          }
        }, 
        IScope.NULLSCOPE);
    }
    return _xblockexpression;
  }
  
  public IScope scope_CheckParameterCondition_parameter(final CheckParameterCondition checkParameterCondition, final EReference ref) {
    IScope _xblockexpression = null;
    {
      CheckParameterCondition validation = checkParameterCondition;
      ResponseBlock responseBlock = EcoreUtil2.<ResponseBlock>getContainerOfType(validation, ResponseBlock.class);
      CommandResponseBlock commandBlock = EcoreUtil2.<CommandResponseBlock>getContainerOfType(validation, CommandResponseBlock.class);
      EventBlock eventBlock = EcoreUtil2.<EventBlock>getContainerOfType(validation, EventBlock.class);
      AlarmBlock alarmBlock = EcoreUtil2.<AlarmBlock>getContainerOfType(validation, AlarmBlock.class);
      DataPointBlock dataBlock = EcoreUtil2.<DataPointBlock>getContainerOfType(validation, DataPointBlock.class);
      final List<Parameter> validListOfParameters = CollectionLiterals.<Parameter>newArrayList();
      if (((responseBlock != null) && (responseBlock.getValidationRules() != null))) {
        if (((responseBlock.getResponse() != null) && (responseBlock.getResponse().getParameters() != null))) {
          validListOfParameters.addAll(responseBlock.getResponse().getParameters());
        }
      } else {
        if (((commandBlock != null) && (commandBlock.getValidationRules() != null))) {
          if (((commandBlock.getCommand() != null) && (commandBlock.getCommand().getParameters() != null))) {
            validListOfParameters.addAll(commandBlock.getCommand().getParameters());
          }
        }
      }
      if (((eventBlock != null) && (eventBlock.getValidationRules() != null))) {
        if (((eventBlock.getEvent() != null) && (eventBlock.getEvent().getParameters() != null))) {
          validListOfParameters.addAll(eventBlock.getEvent().getParameters());
        }
      }
      if (((alarmBlock != null) && (alarmBlock.getValidationRules() != null))) {
        if (((alarmBlock.getAlarm() != null) && (alarmBlock.getAlarm().getParameters() != null))) {
          validListOfParameters.addAll(alarmBlock.getAlarm().getParameters());
        }
      }
      if (((dataBlock != null) && (dataBlock.getValidationRules() != null))) {
        EList<DataPoint> _dataPoint = dataBlock.getDataPoint();
        boolean _tripleNotEquals = (_dataPoint != null);
        if (_tripleNotEquals) {
          final Consumer<DataPoint> _function = (DataPoint dP) -> {
            validListOfParameters.addAll(dP.getParameters());
          };
          dataBlock.getDataPoint().forEach(_function);
        }
      }
      _xblockexpression = Scopes.<Parameter>scopeFor(validListOfParameters, 
        new Function<Parameter, QualifiedName>() {
          @Override
          public QualifiedName apply(final Parameter input) {
            return MncScopeProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
          }
          
          @Override
          public boolean equals(final Object object) {
            throw new UnsupportedOperationException("TODO: auto-generated method stub");
          }
        }, 
        IScope.NULLSCOPE);
    }
    return _xblockexpression;
  }
  
  public IScope scope_CommandResponseBlock_command(final CommandResponseBlock commandResponseBlock, final EReference ref) {
    List<Command> _candidateCommands = this.getCandidateCommands(EcoreUtil2.<ControlNode>getContainerOfType(commandResponseBlock, ControlNode.class));
    return Scopes.<Command>scopeFor(_candidateCommands, 
      new Function<Command, QualifiedName>() {
        @Override
        public QualifiedName apply(final Command input) {
          return MncScopeProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
        }
        
        @Override
        public boolean equals(final Object object) {
          throw new UnsupportedOperationException("TODO: auto-generated method stub");
        }
      }, 
      IScope.NULLSCOPE);
  }
  
  public IScope scope_EventBlock_event(final EventBlock eventBlock, final EReference ref) {
    List<Event> _candidateEvents = this.getCandidateEvents(EcoreUtil2.<ControlNode>getContainerOfType(eventBlock, ControlNode.class).getInterfaceDescription());
    return Scopes.<Event>scopeFor(_candidateEvents, 
      new Function<Event, QualifiedName>() {
        @Override
        public QualifiedName apply(final Event input) {
          return MncScopeProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
        }
        
        @Override
        public boolean equals(final Object object) {
          throw new UnsupportedOperationException("TODO: auto-generated method stub");
        }
      }, 
      IScope.NULLSCOPE);
  }
  
  public IScope scope_AlarmBlock_alarm(final AlarmBlock alarmBlock, final EReference ref) {
    List<Alarm> _candidateAlarms = this.getCandidateAlarms(EcoreUtil2.<ControlNode>getContainerOfType(alarmBlock, ControlNode.class).getInterfaceDescription());
    return Scopes.<Alarm>scopeFor(_candidateAlarms, 
      new Function<Alarm, QualifiedName>() {
        @Override
        public QualifiedName apply(final Alarm input) {
          return MncScopeProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
        }
        
        @Override
        public boolean equals(final Object object) {
          throw new UnsupportedOperationException("TODO: auto-generated method stub");
        }
      }, 
      IScope.NULLSCOPE);
  }
  
  public IScope scope_CommandResponseBlock_triggeredEvents(final CommandResponseBlock commandResponseBlock, final EReference ref) {
    List<Event> _candidateEvents = this.getCandidateEvents(EcoreUtil2.<ControlNode>getContainerOfType(commandResponseBlock, ControlNode.class).getInterfaceDescription());
    return Scopes.<Event>scopeFor(_candidateEvents, 
      new Function<Event, QualifiedName>() {
        @Override
        public QualifiedName apply(final Event input) {
          return MncScopeProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
        }
        
        @Override
        public boolean equals(final Object object) {
          throw new UnsupportedOperationException("TODO: auto-generated method stub");
        }
      }, 
      IScope.NULLSCOPE);
  }
  
  public IScope scope_ParameterTranslation_inputParameters(final ParameterTranslation parameterTranslation, final EReference ref) {
    IScope _xifexpression = null;
    CommandResponseBlock _containerOfType = EcoreUtil2.<CommandResponseBlock>getContainerOfType(parameterTranslation, CommandResponseBlock.class);
    boolean _tripleNotEquals = (_containerOfType != null);
    if (_tripleNotEquals) {
      _xifexpression = Scopes.scopeFor(EcoreUtil2.<CommandResponseBlock>getContainerOfType(parameterTranslation, CommandResponseBlock.class).getCommand().getParameters());
    } else {
      IScope _xblockexpression = null;
      {
        List<Parameter> listOfParameters = CollectionLiterals.<Parameter>newArrayList();
        EList<Response> _inputResponses = EcoreUtil2.<ResponseAggregationRule>getContainerOfType(parameterTranslation, ResponseAggregationRule.class).getInputResponses();
        for (final Response response : _inputResponses) {
          listOfParameters.addAll(response.getParameters());
        }
        _xblockexpression = Scopes.<Parameter>scopeFor(listOfParameters, 
          new Function<Parameter, QualifiedName>() {
            @Override
            public QualifiedName apply(final Parameter input) {
              return MncScopeProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
            }
            
            @Override
            public boolean equals(final Object object) {
              throw new UnsupportedOperationException("TODO: auto-generated method stub");
            }
          }, 
          IScope.NULLSCOPE);
      }
      _xifexpression = _xblockexpression;
    }
    return _xifexpression;
  }
  
  public IScope scope_ParameterTranslation_translatedParameters(final ParameterTranslation parameterTranslation, final EReference ref) {
    IScope _xblockexpression = null;
    {
      List<Parameter> listOfParameters = CollectionLiterals.<Parameter>newArrayList();
      IScope _xifexpression = null;
      ActionCommand _containerOfType = EcoreUtil2.<ActionCommand>getContainerOfType(parameterTranslation, ActionCommand.class);
      boolean _tripleNotEquals = (_containerOfType != null);
      if (_tripleNotEquals) {
        IScope _xblockexpression_1 = null;
        {
          listOfParameters.addAll(EcoreUtil2.<ActionCommand>getContainerOfType(parameterTranslation, ActionCommand.class).getCommand().getParameters());
          _xblockexpression_1 = Scopes.<Parameter>scopeFor(listOfParameters, 
            new Function<Parameter, QualifiedName>() {
              @Override
              public QualifiedName apply(final Parameter input) {
                return MncScopeProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
              }
              
              @Override
              public boolean equals(final Object object) {
                throw new UnsupportedOperationException("TODO: auto-generated method stub");
              }
            }, 
            IScope.NULLSCOPE);
        }
        _xifexpression = _xblockexpression_1;
      } else {
        _xifexpression = Scopes.<Parameter>scopeFor(listOfParameters, 
          new Function<Parameter, QualifiedName>() {
            @Override
            public QualifiedName apply(final Parameter input) {
              return MncScopeProvider.this.qualifiedNameProvider.getFullyQualifiedName(input);
            }
            
            @Override
            public boolean equals(final Object object) {
              throw new UnsupportedOperationException("TODO: auto-generated method stub");
            }
          }, 
          IScope.NULLSCOPE);
      }
      _xblockexpression = _xifexpression;
    }
    return _xblockexpression;
  }
}
