/*
 * generated by Xtext 2.18.0
 */
package com.operation.dsl.serializer;

import com.google.inject.Inject;
import com.operation.dsl.services.OperationGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class OperationSyntacticSequencer extends AbstractSyntacticSequencer {

	protected OperationGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ArrayType___EqualsSignKeyword_5_0_LeftSquareBracketKeyword_5_1_RightSquareBracketKeyword_5_3__q;
	protected AbstractElementAlias match_DataModel_RightCurlyBracketKeyword_1_1_a;
	protected AbstractElementAlias match_DataModel_RightCurlyBracketKeyword_1_1_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (OperationGrammarAccess) access;
		match_ArrayType___EqualsSignKeyword_5_0_LeftSquareBracketKeyword_5_1_RightSquareBracketKeyword_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getArrayTypeAccess().getEqualsSignKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getArrayTypeAccess().getLeftSquareBracketKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getArrayTypeAccess().getRightSquareBracketKeyword_5_3()));
		match_DataModel_RightCurlyBracketKeyword_1_1_a = new TokenAlias(true, true, grammarAccess.getDataModelAccess().getRightCurlyBracketKeyword_1_1());
		match_DataModel_RightCurlyBracketKeyword_1_1_p = new TokenAlias(true, false, grammarAccess.getDataModelAccess().getRightCurlyBracketKeyword_1_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_ArrayType___EqualsSignKeyword_5_0_LeftSquareBracketKeyword_5_1_RightSquareBracketKeyword_5_3__q.equals(syntax))
				emit_ArrayType___EqualsSignKeyword_5_0_LeftSquareBracketKeyword_5_1_RightSquareBracketKeyword_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DataModel_RightCurlyBracketKeyword_1_1_a.equals(syntax))
				emit_DataModel_RightCurlyBracketKeyword_1_1_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DataModel_RightCurlyBracketKeyword_1_1_p.equals(syntax))
				emit_DataModel_RightCurlyBracketKeyword_1_1_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('=' '[' ']')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=EString (ambiguity) (rule end)
	 */
	protected void emit_ArrayType___EqualsSignKeyword_5_0_LeftSquareBracketKeyword_5_1_RightSquareBracketKeyword_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '}'*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'DataModel' name=EString
	 *     (rule start) (ambiguity) 'composites' '{' composites+=[DataModel|ID]
	 *     name=EString '{' (ambiguity) 'DataModel' name=EString
	 *     name=EString '{' (ambiguity) 'composites' '{' composites+=[DataModel|ID]
	 *     name=EString '{' (ambiguity) (rule end)
	 *     primitives+=Parameter '}' (ambiguity) 'DataModel' name=EString
	 *     primitives+=Parameter '}' (ambiguity) 'composites' '{' composites+=[DataModel|ID]
	 *     primitives+=Parameter '}' (ambiguity) (rule end)
	 */
	protected void emit_DataModel_RightCurlyBracketKeyword_1_1_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '}'+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     composites+=[DataModel|ID] '}' (ambiguity) 'DataModel' name=EString
	 *     composites+=[DataModel|ID] '}' (ambiguity) 'composites' '{' composites+=[DataModel|ID]
	 *     composites+=[DataModel|ID] '}' (ambiguity) (rule end)
	 */
	protected void emit_DataModel_RightCurlyBracketKeyword_1_1_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
