/*
 * generated by Xtext 2.15.0
 */
package com.mncml.dsl

import com.google.inject.Binder
import com.mncml.dsl.scoping.MncScopeProvider
import com.mncml.dsl.resource.MncResourceDescriptionStrategy
import org.eclipse.xtext.linking.LinkingScopeProviderBinding
import org.eclipse.xtext.scoping.IScopeProvider
import org.eclipse.xtext.serializer.tokens.ICrossReferenceSerializer
import com.mncml.dsl.serializer.MncCrossReferenceSerializer
import org.eclipse.xtext.serializer.ISerializer
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy
import com.mncml.dsl.serializer.MncCustomSerializer

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MncRuntimeModule extends AbstractMncRuntimeModule  {
	
	override Class<? extends IScopeProvider> bindIScopeProvider() {
		MncScopeProvider;
	}
	
	override void configureLinkingIScopeProvider(Binder binder) {
		binder.bind(IScopeProvider).annotatedWith(LinkingScopeProviderBinding).to(MncScopeProvider);
	}
	
	def Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		MncResourceDescriptionStrategy
	}

	def Class<? extends ICrossReferenceSerializer> bindICrossReferenceSerializer() {
		MncCrossReferenceSerializer
	}
	
	override Class<? extends ISerializer> bindISerializer() {
		MncCustomSerializer
	}	
	
}
