/*
 * generated by Xtext 2.15.0
 */
package com.mncml.dsl

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
 
 
 
class MncStandaloneSetup extends MncStandaloneSetupGenerated {

	def static void doSetup() {
		new MncStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
