/**
 * generated by Xtext 2.13.0
 */
package com.dml.dsl.ui.contentassist;

import com.dml.dsl.ui.contentassist.AbstractDmlProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DmlProposalProvider extends AbstractDmlProposalProvider {
}
