/*
 * generated by Xtext 2.18.0
 */
package com.capability.services;

import com.dml.dsl.services.DmlGrammarAccess;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CapabilityGrammarAccess extends AbstractGrammarElementFinder {
	
	public class CapabilityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.Capability");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCapabilityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCapabilityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cCompatibleKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cComponentKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cInterfaceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cComponentInterfaceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cComponentInterfaceInterfaceDescriptionCrossReference_6_0 = (CrossReference)cComponentInterfaceAssignment_6.eContents().get(0);
		private final RuleCall cComponentInterfaceInterfaceDescriptionQualifiedNameParserRuleCall_6_0_1 = (RuleCall)cComponentInterfaceInterfaceDescriptionCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cComponentInterfaceAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cComponentInterfaceInterfaceDescriptionCrossReference_7_1_0 = (CrossReference)cComponentInterfaceAssignment_7_1.eContents().get(0);
		private final RuleCall cComponentInterfaceInterfaceDescriptionQualifiedNameParserRuleCall_7_1_0_1 = (RuleCall)cComponentInterfaceInterfaceDescriptionCrossReference_7_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cRequiredINITProcessAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cRequiredINITProcessActionParserRuleCall_9_0 = (RuleCall)cRequiredINITProcessAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cProvidesControlCapabilitiesKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cProvidesControlCapabilitiesAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cProvidesControlCapabilitiesControlCapabilitiesParserRuleCall_10_1_0 = (RuleCall)cProvidesControlCapabilitiesAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cProvidesOutcomesKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cProvidesOutcomesAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cProvidesOutcomesCapabilitiesOutcomeParserRuleCall_11_1_0 = (RuleCall)cProvidesOutcomesAssignment_11_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Capability capabilityModel::Capability:
		//	{capabilityModel::Capability}
		//	'Capability' name=EString 'compatible' 'component' 'interface'
		//	componentInterface+=[mncModel::InterfaceDescription|QualifiedName] (","
		//	componentInterface+=[mncModel::InterfaceDescription|QualifiedName]*)?
		//	'{'
		//	requiredINITProcess=Action? ('providesControlCapabilities'
		//	providesControlCapabilities=ControlCapabilities)? ('providesOutcomes'
		//	providesOutcomes=CapabilitiesOutcome)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{capabilityModel::Capability} 'Capability' name=EString 'compatible' 'component' 'interface'
		//componentInterface+=[mncModel::InterfaceDescription|QualifiedName] (","
		//componentInterface+=[mncModel::InterfaceDescription|QualifiedName]*)? '{' requiredINITProcess=Action?
		//('providesControlCapabilities' providesControlCapabilities=ControlCapabilities)? ('providesOutcomes'
		//providesOutcomes=CapabilitiesOutcome)? '}'
		public Group getGroup() { return cGroup; }
		
		//{capabilityModel::Capability}
		public Action getCapabilityAction_0() { return cCapabilityAction_0; }
		
		//'Capability'
		public Keyword getCapabilityKeyword_1() { return cCapabilityKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'compatible'
		public Keyword getCompatibleKeyword_3() { return cCompatibleKeyword_3; }
		
		//'component'
		public Keyword getComponentKeyword_4() { return cComponentKeyword_4; }
		
		//'interface'
		public Keyword getInterfaceKeyword_5() { return cInterfaceKeyword_5; }
		
		//componentInterface+=[mncModel::InterfaceDescription|QualifiedName]
		public Assignment getComponentInterfaceAssignment_6() { return cComponentInterfaceAssignment_6; }
		
		//[mncModel::InterfaceDescription|QualifiedName]
		public CrossReference getComponentInterfaceInterfaceDescriptionCrossReference_6_0() { return cComponentInterfaceInterfaceDescriptionCrossReference_6_0; }
		
		//QualifiedName
		public RuleCall getComponentInterfaceInterfaceDescriptionQualifiedNameParserRuleCall_6_0_1() { return cComponentInterfaceInterfaceDescriptionQualifiedNameParserRuleCall_6_0_1; }
		
		//("," componentInterface+=[mncModel::InterfaceDescription|QualifiedName]*)?
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//componentInterface+=[mncModel::InterfaceDescription|QualifiedName]*
		public Assignment getComponentInterfaceAssignment_7_1() { return cComponentInterfaceAssignment_7_1; }
		
		//[mncModel::InterfaceDescription|QualifiedName]
		public CrossReference getComponentInterfaceInterfaceDescriptionCrossReference_7_1_0() { return cComponentInterfaceInterfaceDescriptionCrossReference_7_1_0; }
		
		//QualifiedName
		public RuleCall getComponentInterfaceInterfaceDescriptionQualifiedNameParserRuleCall_7_1_0_1() { return cComponentInterfaceInterfaceDescriptionQualifiedNameParserRuleCall_7_1_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//requiredINITProcess=Action?
		public Assignment getRequiredINITProcessAssignment_9() { return cRequiredINITProcessAssignment_9; }
		
		//Action
		public RuleCall getRequiredINITProcessActionParserRuleCall_9_0() { return cRequiredINITProcessActionParserRuleCall_9_0; }
		
		//('providesControlCapabilities' providesControlCapabilities=ControlCapabilities)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'providesControlCapabilities'
		public Keyword getProvidesControlCapabilitiesKeyword_10_0() { return cProvidesControlCapabilitiesKeyword_10_0; }
		
		//providesControlCapabilities=ControlCapabilities
		public Assignment getProvidesControlCapabilitiesAssignment_10_1() { return cProvidesControlCapabilitiesAssignment_10_1; }
		
		//ControlCapabilities
		public RuleCall getProvidesControlCapabilitiesControlCapabilitiesParserRuleCall_10_1_0() { return cProvidesControlCapabilitiesControlCapabilitiesParserRuleCall_10_1_0; }
		
		//('providesOutcomes' providesOutcomes=CapabilitiesOutcome)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'providesOutcomes'
		public Keyword getProvidesOutcomesKeyword_11_0() { return cProvidesOutcomesKeyword_11_0; }
		
		//providesOutcomes=CapabilitiesOutcome
		public Assignment getProvidesOutcomesAssignment_11_1() { return cProvidesOutcomesAssignment_11_1; }
		
		//CapabilitiesOutcome
		public RuleCall getProvidesOutcomesCapabilitiesOutcomeParserRuleCall_11_1_0() { return cProvidesOutcomesCapabilitiesOutcomeParserRuleCall_11_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class ControlCapabilitiesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.ControlCapabilities");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cControlCapabilitiesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cFireableKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Keyword cCommandsKeyword_2_0_1 = (Keyword)cGroup_2_0.eContents().get(1);
		private final Keyword cColonKeyword_2_0_2 = (Keyword)cGroup_2_0.eContents().get(2);
		private final Assignment cCommandsAssignment_2_0_3 = (Assignment)cGroup_2_0.eContents().get(3);
		private final CrossReference cCommandsCommandCrossReference_2_0_3_0 = (CrossReference)cCommandsAssignment_2_0_3.eContents().get(0);
		private final RuleCall cCommandsCommandQualifiedNameParserRuleCall_2_0_3_0_1 = (RuleCall)cCommandsCommandCrossReference_2_0_3_0.eContents().get(1);
		private final Group cGroup_2_0_4 = (Group)cGroup_2_0.eContents().get(4);
		private final Keyword cCommaKeyword_2_0_4_0 = (Keyword)cGroup_2_0_4.eContents().get(0);
		private final Assignment cCommandsAssignment_2_0_4_1 = (Assignment)cGroup_2_0_4.eContents().get(1);
		private final CrossReference cCommandsCommandCrossReference_2_0_4_1_0 = (CrossReference)cCommandsAssignment_2_0_4_1.eContents().get(0);
		private final RuleCall cCommandsCommandQualifiedNameParserRuleCall_2_0_4_1_0_1 = (RuleCall)cCommandsCommandCrossReference_2_0_4_1_0.eContents().get(1);
		private final Group cGroup_2_1 = (Group)cUnorderedGroup_2.eContents().get(1);
		private final Keyword cReceivableKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cEventsKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Keyword cColonKeyword_2_1_2 = (Keyword)cGroup_2_1.eContents().get(2);
		private final Assignment cEventsAssignment_2_1_3 = (Assignment)cGroup_2_1.eContents().get(3);
		private final CrossReference cEventsEventCrossReference_2_1_3_0 = (CrossReference)cEventsAssignment_2_1_3.eContents().get(0);
		private final RuleCall cEventsEventQualifiedNameParserRuleCall_2_1_3_0_1 = (RuleCall)cEventsEventCrossReference_2_1_3_0.eContents().get(1);
		private final Group cGroup_2_1_4 = (Group)cGroup_2_1.eContents().get(4);
		private final Keyword cCommaKeyword_2_1_4_0 = (Keyword)cGroup_2_1_4.eContents().get(0);
		private final Assignment cEventsAssignment_2_1_4_1 = (Assignment)cGroup_2_1_4.eContents().get(1);
		private final CrossReference cEventsEventCrossReference_2_1_4_1_0 = (CrossReference)cEventsAssignment_2_1_4_1.eContents().get(0);
		private final RuleCall cEventsEventQualifiedNameParserRuleCall_2_1_4_1_0_1 = (RuleCall)cEventsEventCrossReference_2_1_4_1_0.eContents().get(1);
		private final Group cGroup_2_2 = (Group)cUnorderedGroup_2.eContents().get(2);
		private final Keyword cRaisedKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Keyword cAlarmsKeyword_2_2_1 = (Keyword)cGroup_2_2.eContents().get(1);
		private final Keyword cColonKeyword_2_2_2 = (Keyword)cGroup_2_2.eContents().get(2);
		private final Assignment cAlarmsAssignment_2_2_3 = (Assignment)cGroup_2_2.eContents().get(3);
		private final CrossReference cAlarmsAlarmCrossReference_2_2_3_0 = (CrossReference)cAlarmsAssignment_2_2_3.eContents().get(0);
		private final RuleCall cAlarmsAlarmQualifiedNameParserRuleCall_2_2_3_0_1 = (RuleCall)cAlarmsAlarmCrossReference_2_2_3_0.eContents().get(1);
		private final Group cGroup_2_2_4 = (Group)cGroup_2_2.eContents().get(4);
		private final Keyword cCommaKeyword_2_2_4_0 = (Keyword)cGroup_2_2_4.eContents().get(0);
		private final Assignment cAlarmsAssignment_2_2_4_1 = (Assignment)cGroup_2_2_4.eContents().get(1);
		private final CrossReference cAlarmsAlarmCrossReference_2_2_4_1_0 = (CrossReference)cAlarmsAssignment_2_2_4_1.eContents().get(0);
		private final RuleCall cAlarmsAlarmQualifiedNameParserRuleCall_2_2_4_1_0_1 = (RuleCall)cAlarmsAlarmCrossReference_2_2_4_1_0.eContents().get(1);
		private final Group cGroup_2_3 = (Group)cUnorderedGroup_2.eContents().get(3);
		private final Keyword cSubscribableKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Keyword cDataPointsKeyword_2_3_1 = (Keyword)cGroup_2_3.eContents().get(1);
		private final Keyword cColonKeyword_2_3_2 = (Keyword)cGroup_2_3.eContents().get(2);
		private final Assignment cDataPointsAssignment_2_3_3 = (Assignment)cGroup_2_3.eContents().get(3);
		private final CrossReference cDataPointsDataPointCrossReference_2_3_3_0 = (CrossReference)cDataPointsAssignment_2_3_3.eContents().get(0);
		private final RuleCall cDataPointsDataPointQualifiedNameParserRuleCall_2_3_3_0_1 = (RuleCall)cDataPointsDataPointCrossReference_2_3_3_0.eContents().get(1);
		private final Group cGroup_2_3_4 = (Group)cGroup_2_3.eContents().get(4);
		private final Keyword cCommaKeyword_2_3_4_0 = (Keyword)cGroup_2_3_4.eContents().get(0);
		private final Assignment cDataPointsAssignment_2_3_4_1 = (Assignment)cGroup_2_3_4.eContents().get(1);
		private final CrossReference cDataPointsDataPointCrossReference_2_3_4_1_0 = (CrossReference)cDataPointsAssignment_2_3_4_1.eContents().get(0);
		private final RuleCall cDataPointsDataPointQualifiedNameParserRuleCall_2_3_4_1_0_1 = (RuleCall)cDataPointsDataPointCrossReference_2_3_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ControlCapabilities capabilityModel::ControlCapabilities:
		//	{capabilityModel::ControlCapabilities}
		//	'{' (('fireable' 'commands' ':' commands+=[mncModel::Command|QualifiedName] (","
		//	commands+=[mncModel::Command|QualifiedName])*)? & ('receivable' 'events' ':' events+=[mncModel::Event|QualifiedName]
		//	("," events+=[mncModel::Event|QualifiedName])*)? & ('raised' 'alarms' ':' alarms+=[mncModel::Alarm|QualifiedName] (","
		//	alarms+=[mncModel::Alarm|QualifiedName])*)? & ('subscribable' 'DataPoints' ':'
		//	dataPoints+=[mncModel::DataPoint|QualifiedName] ("," dataPoints+=[mncModel::DataPoint|QualifiedName])*)?)
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{capabilityModel::ControlCapabilities} '{' (('fireable' 'commands' ':' commands+=[mncModel::Command|QualifiedName] (","
		//commands+=[mncModel::Command|QualifiedName])*)? & ('receivable' 'events' ':' events+=[mncModel::Event|QualifiedName]
		//("," events+=[mncModel::Event|QualifiedName])*)? & ('raised' 'alarms' ':' alarms+=[mncModel::Alarm|QualifiedName] (","
		//alarms+=[mncModel::Alarm|QualifiedName])*)? & ('subscribable' 'DataPoints' ':'
		//dataPoints+=[mncModel::DataPoint|QualifiedName] ("," dataPoints+=[mncModel::DataPoint|QualifiedName])*)?) '}'
		public Group getGroup() { return cGroup; }
		
		//{capabilityModel::ControlCapabilities}
		public Action getControlCapabilitiesAction_0() { return cControlCapabilitiesAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('fireable' 'commands' ':' commands+=[mncModel::Command|QualifiedName] (","
		//commands+=[mncModel::Command|QualifiedName])*)? & ('receivable' 'events' ':' events+=[mncModel::Event|QualifiedName]
		//("," events+=[mncModel::Event|QualifiedName])*)? & ('raised' 'alarms' ':' alarms+=[mncModel::Alarm|QualifiedName] (","
		//alarms+=[mncModel::Alarm|QualifiedName])*)? & ('subscribable' 'DataPoints' ':'
		//dataPoints+=[mncModel::DataPoint|QualifiedName] ("," dataPoints+=[mncModel::DataPoint|QualifiedName])*)?
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//('fireable' 'commands' ':' commands+=[mncModel::Command|QualifiedName] (","
		//commands+=[mncModel::Command|QualifiedName])*)?
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//'fireable'
		public Keyword getFireableKeyword_2_0_0() { return cFireableKeyword_2_0_0; }
		
		//'commands'
		public Keyword getCommandsKeyword_2_0_1() { return cCommandsKeyword_2_0_1; }
		
		//':'
		public Keyword getColonKeyword_2_0_2() { return cColonKeyword_2_0_2; }
		
		//commands+=[mncModel::Command|QualifiedName]
		public Assignment getCommandsAssignment_2_0_3() { return cCommandsAssignment_2_0_3; }
		
		//[mncModel::Command|QualifiedName]
		public CrossReference getCommandsCommandCrossReference_2_0_3_0() { return cCommandsCommandCrossReference_2_0_3_0; }
		
		//QualifiedName
		public RuleCall getCommandsCommandQualifiedNameParserRuleCall_2_0_3_0_1() { return cCommandsCommandQualifiedNameParserRuleCall_2_0_3_0_1; }
		
		//("," commands+=[mncModel::Command|QualifiedName])*
		public Group getGroup_2_0_4() { return cGroup_2_0_4; }
		
		//","
		public Keyword getCommaKeyword_2_0_4_0() { return cCommaKeyword_2_0_4_0; }
		
		//commands+=[mncModel::Command|QualifiedName]
		public Assignment getCommandsAssignment_2_0_4_1() { return cCommandsAssignment_2_0_4_1; }
		
		//[mncModel::Command|QualifiedName]
		public CrossReference getCommandsCommandCrossReference_2_0_4_1_0() { return cCommandsCommandCrossReference_2_0_4_1_0; }
		
		//QualifiedName
		public RuleCall getCommandsCommandQualifiedNameParserRuleCall_2_0_4_1_0_1() { return cCommandsCommandQualifiedNameParserRuleCall_2_0_4_1_0_1; }
		
		//('receivable' 'events' ':' events+=[mncModel::Event|QualifiedName] ("," events+=[mncModel::Event|QualifiedName])*)?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'receivable'
		public Keyword getReceivableKeyword_2_1_0() { return cReceivableKeyword_2_1_0; }
		
		//'events'
		public Keyword getEventsKeyword_2_1_1() { return cEventsKeyword_2_1_1; }
		
		//':'
		public Keyword getColonKeyword_2_1_2() { return cColonKeyword_2_1_2; }
		
		//events+=[mncModel::Event|QualifiedName]
		public Assignment getEventsAssignment_2_1_3() { return cEventsAssignment_2_1_3; }
		
		//[mncModel::Event|QualifiedName]
		public CrossReference getEventsEventCrossReference_2_1_3_0() { return cEventsEventCrossReference_2_1_3_0; }
		
		//QualifiedName
		public RuleCall getEventsEventQualifiedNameParserRuleCall_2_1_3_0_1() { return cEventsEventQualifiedNameParserRuleCall_2_1_3_0_1; }
		
		//("," events+=[mncModel::Event|QualifiedName])*
		public Group getGroup_2_1_4() { return cGroup_2_1_4; }
		
		//","
		public Keyword getCommaKeyword_2_1_4_0() { return cCommaKeyword_2_1_4_0; }
		
		//events+=[mncModel::Event|QualifiedName]
		public Assignment getEventsAssignment_2_1_4_1() { return cEventsAssignment_2_1_4_1; }
		
		//[mncModel::Event|QualifiedName]
		public CrossReference getEventsEventCrossReference_2_1_4_1_0() { return cEventsEventCrossReference_2_1_4_1_0; }
		
		//QualifiedName
		public RuleCall getEventsEventQualifiedNameParserRuleCall_2_1_4_1_0_1() { return cEventsEventQualifiedNameParserRuleCall_2_1_4_1_0_1; }
		
		//('raised' 'alarms' ':' alarms+=[mncModel::Alarm|QualifiedName] ("," alarms+=[mncModel::Alarm|QualifiedName])*)?
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//'raised'
		public Keyword getRaisedKeyword_2_2_0() { return cRaisedKeyword_2_2_0; }
		
		//'alarms'
		public Keyword getAlarmsKeyword_2_2_1() { return cAlarmsKeyword_2_2_1; }
		
		//':'
		public Keyword getColonKeyword_2_2_2() { return cColonKeyword_2_2_2; }
		
		//alarms+=[mncModel::Alarm|QualifiedName]
		public Assignment getAlarmsAssignment_2_2_3() { return cAlarmsAssignment_2_2_3; }
		
		//[mncModel::Alarm|QualifiedName]
		public CrossReference getAlarmsAlarmCrossReference_2_2_3_0() { return cAlarmsAlarmCrossReference_2_2_3_0; }
		
		//QualifiedName
		public RuleCall getAlarmsAlarmQualifiedNameParserRuleCall_2_2_3_0_1() { return cAlarmsAlarmQualifiedNameParserRuleCall_2_2_3_0_1; }
		
		//("," alarms+=[mncModel::Alarm|QualifiedName])*
		public Group getGroup_2_2_4() { return cGroup_2_2_4; }
		
		//","
		public Keyword getCommaKeyword_2_2_4_0() { return cCommaKeyword_2_2_4_0; }
		
		//alarms+=[mncModel::Alarm|QualifiedName]
		public Assignment getAlarmsAssignment_2_2_4_1() { return cAlarmsAssignment_2_2_4_1; }
		
		//[mncModel::Alarm|QualifiedName]
		public CrossReference getAlarmsAlarmCrossReference_2_2_4_1_0() { return cAlarmsAlarmCrossReference_2_2_4_1_0; }
		
		//QualifiedName
		public RuleCall getAlarmsAlarmQualifiedNameParserRuleCall_2_2_4_1_0_1() { return cAlarmsAlarmQualifiedNameParserRuleCall_2_2_4_1_0_1; }
		
		//('subscribable' 'DataPoints' ':' dataPoints+=[mncModel::DataPoint|QualifiedName] (","
		//dataPoints+=[mncModel::DataPoint|QualifiedName])*)?
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//'subscribable'
		public Keyword getSubscribableKeyword_2_3_0() { return cSubscribableKeyword_2_3_0; }
		
		//'DataPoints'
		public Keyword getDataPointsKeyword_2_3_1() { return cDataPointsKeyword_2_3_1; }
		
		//':'
		public Keyword getColonKeyword_2_3_2() { return cColonKeyword_2_3_2; }
		
		//dataPoints+=[mncModel::DataPoint|QualifiedName]
		public Assignment getDataPointsAssignment_2_3_3() { return cDataPointsAssignment_2_3_3; }
		
		//[mncModel::DataPoint|QualifiedName]
		public CrossReference getDataPointsDataPointCrossReference_2_3_3_0() { return cDataPointsDataPointCrossReference_2_3_3_0; }
		
		//QualifiedName
		public RuleCall getDataPointsDataPointQualifiedNameParserRuleCall_2_3_3_0_1() { return cDataPointsDataPointQualifiedNameParserRuleCall_2_3_3_0_1; }
		
		//("," dataPoints+=[mncModel::DataPoint|QualifiedName])*
		public Group getGroup_2_3_4() { return cGroup_2_3_4; }
		
		//","
		public Keyword getCommaKeyword_2_3_4_0() { return cCommaKeyword_2_3_4_0; }
		
		//dataPoints+=[mncModel::DataPoint|QualifiedName]
		public Assignment getDataPointsAssignment_2_3_4_1() { return cDataPointsAssignment_2_3_4_1; }
		
		//[mncModel::DataPoint|QualifiedName]
		public CrossReference getDataPointsDataPointCrossReference_2_3_4_1_0() { return cDataPointsDataPointCrossReference_2_3_4_1_0; }
		
		//QualifiedName
		public RuleCall getDataPointsDataPointQualifiedNameParserRuleCall_2_3_4_1_0_1() { return cDataPointsDataPointQualifiedNameParserRuleCall_2_3_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class CapabilitiesOutcomeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.CapabilitiesOutcome");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCapabilitiesOutcomeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cReceivableKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Keyword cResponsesKeyword_2_0_1 = (Keyword)cGroup_2_0.eContents().get(1);
		private final Assignment cResponsesAssignment_2_0_2 = (Assignment)cGroup_2_0.eContents().get(2);
		private final CrossReference cResponsesResponseCrossReference_2_0_2_0 = (CrossReference)cResponsesAssignment_2_0_2.eContents().get(0);
		private final RuleCall cResponsesResponseQualifiedNameParserRuleCall_2_0_2_0_1 = (RuleCall)cResponsesResponseCrossReference_2_0_2_0.eContents().get(1);
		private final Group cGroup_2_0_3 = (Group)cGroup_2_0.eContents().get(3);
		private final Keyword cCommaKeyword_2_0_3_0 = (Keyword)cGroup_2_0_3.eContents().get(0);
		private final Assignment cResponsesAssignment_2_0_3_1 = (Assignment)cGroup_2_0_3.eContents().get(1);
		private final CrossReference cResponsesResponseCrossReference_2_0_3_1_0 = (CrossReference)cResponsesAssignment_2_0_3_1.eContents().get(0);
		private final RuleCall cResponsesResponseQualifiedNameParserRuleCall_2_0_3_1_0_1 = (RuleCall)cResponsesResponseCrossReference_2_0_3_1_0.eContents().get(1);
		private final Group cGroup_2_1 = (Group)cUnorderedGroup_2.eContents().get(1);
		private final Keyword cReceivableKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cEventsKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cEventsAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final CrossReference cEventsEventCrossReference_2_1_2_0 = (CrossReference)cEventsAssignment_2_1_2.eContents().get(0);
		private final RuleCall cEventsEventQualifiedNameParserRuleCall_2_1_2_0_1 = (RuleCall)cEventsEventCrossReference_2_1_2_0.eContents().get(1);
		private final Group cGroup_2_1_3 = (Group)cGroup_2_1.eContents().get(3);
		private final Keyword cCommaKeyword_2_1_3_0 = (Keyword)cGroup_2_1_3.eContents().get(0);
		private final Assignment cEventsAssignment_2_1_3_1 = (Assignment)cGroup_2_1_3.eContents().get(1);
		private final CrossReference cEventsEventCrossReference_2_1_3_1_0 = (CrossReference)cEventsAssignment_2_1_3_1.eContents().get(0);
		private final RuleCall cEventsEventQualifiedNameParserRuleCall_2_1_3_1_0_1 = (RuleCall)cEventsEventCrossReference_2_1_3_1_0.eContents().get(1);
		private final Group cGroup_2_2 = (Group)cUnorderedGroup_2.eContents().get(2);
		private final Keyword cReceivableKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Keyword cAlarmsKeyword_2_2_1 = (Keyword)cGroup_2_2.eContents().get(1);
		private final Assignment cAlarmsAssignment_2_2_2 = (Assignment)cGroup_2_2.eContents().get(2);
		private final CrossReference cAlarmsAlarmCrossReference_2_2_2_0 = (CrossReference)cAlarmsAssignment_2_2_2.eContents().get(0);
		private final RuleCall cAlarmsAlarmQualifiedNameParserRuleCall_2_2_2_0_1 = (RuleCall)cAlarmsAlarmCrossReference_2_2_2_0.eContents().get(1);
		private final Group cGroup_2_2_3 = (Group)cGroup_2_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_2_3_0 = (Keyword)cGroup_2_2_3.eContents().get(0);
		private final Assignment cAlarmsAssignment_2_2_3_1 = (Assignment)cGroup_2_2_3.eContents().get(1);
		private final CrossReference cAlarmsAlarmCrossReference_2_2_3_1_0 = (CrossReference)cAlarmsAssignment_2_2_3_1.eContents().get(0);
		private final RuleCall cAlarmsAlarmQualifiedNameParserRuleCall_2_2_3_1_0_1 = (RuleCall)cAlarmsAlarmCrossReference_2_2_3_1_0.eContents().get(1);
		private final Group cGroup_2_3 = (Group)cUnorderedGroup_2.eContents().get(3);
		private final Keyword cReceivableKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Keyword cDataPointsKeyword_2_3_1 = (Keyword)cGroup_2_3.eContents().get(1);
		private final Assignment cDataPointsAssignment_2_3_2 = (Assignment)cGroup_2_3.eContents().get(2);
		private final CrossReference cDataPointsDataPointCrossReference_2_3_2_0 = (CrossReference)cDataPointsAssignment_2_3_2.eContents().get(0);
		private final RuleCall cDataPointsDataPointQualifiedNameParserRuleCall_2_3_2_0_1 = (RuleCall)cDataPointsDataPointCrossReference_2_3_2_0.eContents().get(1);
		private final Group cGroup_2_3_3 = (Group)cGroup_2_3.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_3_0 = (Keyword)cGroup_2_3_3.eContents().get(0);
		private final Assignment cDataPointsAssignment_2_3_3_1 = (Assignment)cGroup_2_3_3.eContents().get(1);
		private final CrossReference cDataPointsDataPointCrossReference_2_3_3_1_0 = (CrossReference)cDataPointsAssignment_2_3_3_1.eContents().get(0);
		private final RuleCall cDataPointsDataPointQualifiedNameParserRuleCall_2_3_3_1_0_1 = (RuleCall)cDataPointsDataPointCrossReference_2_3_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//CapabilitiesOutcome capabilityModel::CapabilitiesOutcome:
		//	{capabilityModel::CapabilitiesOutcome}
		//	'{' (('receivable' 'responses' responses+=[mncModel::Response|QualifiedName] (','
		//	responses+=[mncModel::Response|QualifiedName]*)?)? & ('receivable' 'events' events+=[mncModel::Event|QualifiedName]
		//	(',' events+=[mncModel::Event|QualifiedName]*)?)? & ('receivable' 'alarms' alarms+=[mncModel::Alarm|QualifiedName]
		//	(',' alarms+=[mncModel::Alarm|QualifiedName]*)?)? & ('receivable' 'dataPoints'
		//	dataPoints+=[mncModel::DataPoint|QualifiedName] (',' dataPoints+=[mncModel::DataPoint|QualifiedName])*)?)
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{capabilityModel::CapabilitiesOutcome} '{' (('receivable' 'responses' responses+=[mncModel::Response|QualifiedName] (','
		//responses+=[mncModel::Response|QualifiedName]*)?)? & ('receivable' 'events' events+=[mncModel::Event|QualifiedName]
		//(',' events+=[mncModel::Event|QualifiedName]*)?)? & ('receivable' 'alarms' alarms+=[mncModel::Alarm|QualifiedName] (','
		//alarms+=[mncModel::Alarm|QualifiedName]*)?)? & ('receivable' 'dataPoints'
		//dataPoints+=[mncModel::DataPoint|QualifiedName] (',' dataPoints+=[mncModel::DataPoint|QualifiedName])*)?) '}'
		public Group getGroup() { return cGroup; }
		
		//{capabilityModel::CapabilitiesOutcome}
		public Action getCapabilitiesOutcomeAction_0() { return cCapabilitiesOutcomeAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('receivable' 'responses' responses+=[mncModel::Response|QualifiedName] (','
		//responses+=[mncModel::Response|QualifiedName]*)?)? & ('receivable' 'events' events+=[mncModel::Event|QualifiedName]
		//(',' events+=[mncModel::Event|QualifiedName]*)?)? & ('receivable' 'alarms' alarms+=[mncModel::Alarm|QualifiedName] (','
		//alarms+=[mncModel::Alarm|QualifiedName]*)?)? & ('receivable' 'dataPoints'
		//dataPoints+=[mncModel::DataPoint|QualifiedName] (',' dataPoints+=[mncModel::DataPoint|QualifiedName])*)?
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//('receivable' 'responses' responses+=[mncModel::Response|QualifiedName] (','
		//responses+=[mncModel::Response|QualifiedName]*)?)?
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//'receivable'
		public Keyword getReceivableKeyword_2_0_0() { return cReceivableKeyword_2_0_0; }
		
		//'responses'
		public Keyword getResponsesKeyword_2_0_1() { return cResponsesKeyword_2_0_1; }
		
		//responses+=[mncModel::Response|QualifiedName]
		public Assignment getResponsesAssignment_2_0_2() { return cResponsesAssignment_2_0_2; }
		
		//[mncModel::Response|QualifiedName]
		public CrossReference getResponsesResponseCrossReference_2_0_2_0() { return cResponsesResponseCrossReference_2_0_2_0; }
		
		//QualifiedName
		public RuleCall getResponsesResponseQualifiedNameParserRuleCall_2_0_2_0_1() { return cResponsesResponseQualifiedNameParserRuleCall_2_0_2_0_1; }
		
		//(',' responses+=[mncModel::Response|QualifiedName]*)?
		public Group getGroup_2_0_3() { return cGroup_2_0_3; }
		
		//','
		public Keyword getCommaKeyword_2_0_3_0() { return cCommaKeyword_2_0_3_0; }
		
		//responses+=[mncModel::Response|QualifiedName]*
		public Assignment getResponsesAssignment_2_0_3_1() { return cResponsesAssignment_2_0_3_1; }
		
		//[mncModel::Response|QualifiedName]
		public CrossReference getResponsesResponseCrossReference_2_0_3_1_0() { return cResponsesResponseCrossReference_2_0_3_1_0; }
		
		//QualifiedName
		public RuleCall getResponsesResponseQualifiedNameParserRuleCall_2_0_3_1_0_1() { return cResponsesResponseQualifiedNameParserRuleCall_2_0_3_1_0_1; }
		
		//('receivable' 'events' events+=[mncModel::Event|QualifiedName] (',' events+=[mncModel::Event|QualifiedName]*)?)?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'receivable'
		public Keyword getReceivableKeyword_2_1_0() { return cReceivableKeyword_2_1_0; }
		
		//'events'
		public Keyword getEventsKeyword_2_1_1() { return cEventsKeyword_2_1_1; }
		
		//events+=[mncModel::Event|QualifiedName]
		public Assignment getEventsAssignment_2_1_2() { return cEventsAssignment_2_1_2; }
		
		//[mncModel::Event|QualifiedName]
		public CrossReference getEventsEventCrossReference_2_1_2_0() { return cEventsEventCrossReference_2_1_2_0; }
		
		//QualifiedName
		public RuleCall getEventsEventQualifiedNameParserRuleCall_2_1_2_0_1() { return cEventsEventQualifiedNameParserRuleCall_2_1_2_0_1; }
		
		//(',' events+=[mncModel::Event|QualifiedName]*)?
		public Group getGroup_2_1_3() { return cGroup_2_1_3; }
		
		//','
		public Keyword getCommaKeyword_2_1_3_0() { return cCommaKeyword_2_1_3_0; }
		
		//events+=[mncModel::Event|QualifiedName]*
		public Assignment getEventsAssignment_2_1_3_1() { return cEventsAssignment_2_1_3_1; }
		
		//[mncModel::Event|QualifiedName]
		public CrossReference getEventsEventCrossReference_2_1_3_1_0() { return cEventsEventCrossReference_2_1_3_1_0; }
		
		//QualifiedName
		public RuleCall getEventsEventQualifiedNameParserRuleCall_2_1_3_1_0_1() { return cEventsEventQualifiedNameParserRuleCall_2_1_3_1_0_1; }
		
		//('receivable' 'alarms' alarms+=[mncModel::Alarm|QualifiedName] (',' alarms+=[mncModel::Alarm|QualifiedName]*)?)?
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//'receivable'
		public Keyword getReceivableKeyword_2_2_0() { return cReceivableKeyword_2_2_0; }
		
		//'alarms'
		public Keyword getAlarmsKeyword_2_2_1() { return cAlarmsKeyword_2_2_1; }
		
		//alarms+=[mncModel::Alarm|QualifiedName]
		public Assignment getAlarmsAssignment_2_2_2() { return cAlarmsAssignment_2_2_2; }
		
		//[mncModel::Alarm|QualifiedName]
		public CrossReference getAlarmsAlarmCrossReference_2_2_2_0() { return cAlarmsAlarmCrossReference_2_2_2_0; }
		
		//QualifiedName
		public RuleCall getAlarmsAlarmQualifiedNameParserRuleCall_2_2_2_0_1() { return cAlarmsAlarmQualifiedNameParserRuleCall_2_2_2_0_1; }
		
		//(',' alarms+=[mncModel::Alarm|QualifiedName]*)?
		public Group getGroup_2_2_3() { return cGroup_2_2_3; }
		
		//','
		public Keyword getCommaKeyword_2_2_3_0() { return cCommaKeyword_2_2_3_0; }
		
		//alarms+=[mncModel::Alarm|QualifiedName]*
		public Assignment getAlarmsAssignment_2_2_3_1() { return cAlarmsAssignment_2_2_3_1; }
		
		//[mncModel::Alarm|QualifiedName]
		public CrossReference getAlarmsAlarmCrossReference_2_2_3_1_0() { return cAlarmsAlarmCrossReference_2_2_3_1_0; }
		
		//QualifiedName
		public RuleCall getAlarmsAlarmQualifiedNameParserRuleCall_2_2_3_1_0_1() { return cAlarmsAlarmQualifiedNameParserRuleCall_2_2_3_1_0_1; }
		
		//('receivable' 'dataPoints' dataPoints+=[mncModel::DataPoint|QualifiedName] (','
		//dataPoints+=[mncModel::DataPoint|QualifiedName])*)?
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//'receivable'
		public Keyword getReceivableKeyword_2_3_0() { return cReceivableKeyword_2_3_0; }
		
		//'dataPoints'
		public Keyword getDataPointsKeyword_2_3_1() { return cDataPointsKeyword_2_3_1; }
		
		//dataPoints+=[mncModel::DataPoint|QualifiedName]
		public Assignment getDataPointsAssignment_2_3_2() { return cDataPointsAssignment_2_3_2; }
		
		//[mncModel::DataPoint|QualifiedName]
		public CrossReference getDataPointsDataPointCrossReference_2_3_2_0() { return cDataPointsDataPointCrossReference_2_3_2_0; }
		
		//QualifiedName
		public RuleCall getDataPointsDataPointQualifiedNameParserRuleCall_2_3_2_0_1() { return cDataPointsDataPointQualifiedNameParserRuleCall_2_3_2_0_1; }
		
		//(',' dataPoints+=[mncModel::DataPoint|QualifiedName])*
		public Group getGroup_2_3_3() { return cGroup_2_3_3; }
		
		//','
		public Keyword getCommaKeyword_2_3_3_0() { return cCommaKeyword_2_3_3_0; }
		
		//dataPoints+=[mncModel::DataPoint|QualifiedName]
		public Assignment getDataPointsAssignment_2_3_3_1() { return cDataPointsAssignment_2_3_3_1; }
		
		//[mncModel::DataPoint|QualifiedName]
		public CrossReference getDataPointsDataPointCrossReference_2_3_3_1_0() { return cDataPointsDataPointCrossReference_2_3_3_1_0; }
		
		//QualifiedName
		public RuleCall getDataPointsDataPointQualifiedNameParserRuleCall_2_3_3_1_0_1() { return cDataPointsDataPointQualifiedNameParserRuleCall_2_3_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInitKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final UnorderedGroup cUnorderedGroup_3 = (UnorderedGroup)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cUnorderedGroup_3.eContents().get(0);
		private final Keyword cSubscribeKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Keyword cAlarmsKeyword_3_0_1 = (Keyword)cGroup_3_0.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_3_0_2 = (Keyword)cGroup_3_0.eContents().get(2);
		private final Assignment cRaiseAlarmAssignment_3_0_3 = (Assignment)cGroup_3_0.eContents().get(3);
		private final RuleCall cRaiseAlarmActionAlarmParserRuleCall_3_0_3_0 = (RuleCall)cRaiseAlarmAssignment_3_0_3.eContents().get(0);
		private final Group cGroup_3_0_4 = (Group)cGroup_3_0.eContents().get(4);
		private final Keyword cCommaKeyword_3_0_4_0 = (Keyword)cGroup_3_0_4.eContents().get(0);
		private final Assignment cRaiseAlarmAssignment_3_0_4_1 = (Assignment)cGroup_3_0_4.eContents().get(1);
		private final RuleCall cRaiseAlarmActionAlarmParserRuleCall_3_0_4_1_0 = (RuleCall)cRaiseAlarmAssignment_3_0_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_0_5 = (Keyword)cGroup_3_0.eContents().get(5);
		private final Group cGroup_3_1 = (Group)cUnorderedGroup_3.eContents().get(1);
		private final Keyword cFireKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Keyword cCommandsKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_3_1_2 = (Keyword)cGroup_3_1.eContents().get(2);
		private final Assignment cFireCommandAssignment_3_1_3 = (Assignment)cGroup_3_1.eContents().get(3);
		private final RuleCall cFireCommandActionCommandParserRuleCall_3_1_3_0 = (RuleCall)cFireCommandAssignment_3_1_3.eContents().get(0);
		private final Group cGroup_3_1_4 = (Group)cGroup_3_1.eContents().get(4);
		private final Keyword cCommaKeyword_3_1_4_0 = (Keyword)cGroup_3_1_4.eContents().get(0);
		private final Assignment cFireCommandAssignment_3_1_4_1 = (Assignment)cGroup_3_1_4.eContents().get(1);
		private final RuleCall cFireCommandActionCommandParserRuleCall_3_1_4_1_0 = (RuleCall)cFireCommandAssignment_3_1_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_1_5 = (Keyword)cGroup_3_1.eContents().get(5);
		private final Group cGroup_3_2 = (Group)cUnorderedGroup_3.eContents().get(2);
		private final Keyword cSubscribeKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Keyword cEventsKeyword_3_2_1 = (Keyword)cGroup_3_2.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_3_2_2 = (Keyword)cGroup_3_2.eContents().get(2);
		private final Assignment cPublishEventAssignment_3_2_3 = (Assignment)cGroup_3_2.eContents().get(3);
		private final RuleCall cPublishEventActionEventParserRuleCall_3_2_3_0 = (RuleCall)cPublishEventAssignment_3_2_3.eContents().get(0);
		private final Group cGroup_3_2_4 = (Group)cGroup_3_2.eContents().get(4);
		private final Keyword cCommaKeyword_3_2_4_0 = (Keyword)cGroup_3_2_4.eContents().get(0);
		private final Assignment cPublishEventAssignment_3_2_4_1 = (Assignment)cGroup_3_2_4.eContents().get(1);
		private final RuleCall cPublishEventActionEventParserRuleCall_3_2_4_1_0 = (RuleCall)cPublishEventAssignment_3_2_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_2_5 = (Keyword)cGroup_3_2.eContents().get(5);
		private final Group cGroup_3_3 = (Group)cUnorderedGroup_3.eContents().get(3);
		private final Keyword cSubscribeKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Keyword cDataKeyword_3_3_1 = (Keyword)cGroup_3_3.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_3_3_2 = (Keyword)cGroup_3_3.eContents().get(2);
		private final Assignment cTriggerDataPointAssignment_3_3_3 = (Assignment)cGroup_3_3.eContents().get(3);
		private final RuleCall cTriggerDataPointActionDataPointParserRuleCall_3_3_3_0 = (RuleCall)cTriggerDataPointAssignment_3_3_3.eContents().get(0);
		private final Group cGroup_3_3_4 = (Group)cGroup_3_3.eContents().get(4);
		private final Keyword cCommaKeyword_3_3_4_0 = (Keyword)cGroup_3_3_4.eContents().get(0);
		private final Assignment cTriggerDataPointAssignment_3_3_4_1 = (Assignment)cGroup_3_3_4.eContents().get(1);
		private final RuleCall cTriggerDataPointActionDataPointParserRuleCall_3_3_4_1_0 = (RuleCall)cTriggerDataPointAssignment_3_3_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_3_5 = (Keyword)cGroup_3_3.eContents().get(5);
		private final Group cGroup_3_4 = (Group)cUnorderedGroup_3.eContents().get(4);
		private final Keyword cExecuteKeyword_3_4_0 = (Keyword)cGroup_3_4.eContents().get(0);
		private final Keyword cOperationsKeyword_3_4_1 = (Keyword)cGroup_3_4.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_3_4_2 = (Keyword)cGroup_3_4.eContents().get(2);
		private final Assignment cExecuteOperationAssignment_3_4_3 = (Assignment)cGroup_3_4.eContents().get(3);
		private final RuleCall cExecuteOperationActionOperationParserRuleCall_3_4_3_0 = (RuleCall)cExecuteOperationAssignment_3_4_3.eContents().get(0);
		private final Group cGroup_3_4_4 = (Group)cGroup_3_4.eContents().get(4);
		private final Keyword cCommaKeyword_3_4_4_0 = (Keyword)cGroup_3_4_4.eContents().get(0);
		private final Assignment cExecuteOperationAssignment_3_4_4_1 = (Assignment)cGroup_3_4_4.eContents().get(1);
		private final RuleCall cExecuteOperationActionOperationParserRuleCall_3_4_4_1_0 = (RuleCall)cExecuteOperationAssignment_3_4_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_4_5 = (Keyword)cGroup_3_4.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Action mncModel::Action:
		//	{mncModel::Action}
		//	'Init'
		//	'{' (('subscribe' 'alarms' '[' raiseAlarm+=ActionAlarm (',' raiseAlarm+=ActionAlarm)* ']')? & ('fire' 'Commands' '['
		//	fireCommand+=ActionCommand (',' fireCommand+=ActionCommand)* ']')? & ('subscribe' 'events' '['
		//	publishEvent+=ActionEvent (',' publishEvent+=ActionEvent)* ']')? & ('subscribe' 'data' '['
		//	triggerDataPoint+=ActionDataPoint (',' triggerDataPoint+=ActionDataPoint)* ']')? & ('execute' 'Operations' '['
		//	executeOperation+=ActionOperation (',' executeOperation+=ActionOperation)* ']')?)
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{mncModel::Action} 'Init' '{' (('subscribe' 'alarms' '[' raiseAlarm+=ActionAlarm (',' raiseAlarm+=ActionAlarm)* ']')? &
		//('fire' 'Commands' '[' fireCommand+=ActionCommand (',' fireCommand+=ActionCommand)* ']')? & ('subscribe' 'events' '['
		//publishEvent+=ActionEvent (',' publishEvent+=ActionEvent)* ']')? & ('subscribe' 'data' '['
		//triggerDataPoint+=ActionDataPoint (',' triggerDataPoint+=ActionDataPoint)* ']')? & ('execute' 'Operations' '['
		//executeOperation+=ActionOperation (',' executeOperation+=ActionOperation)* ']')?) '}'
		public Group getGroup() { return cGroup; }
		
		//{mncModel::Action}
		public Action getActionAction_0() { return cActionAction_0; }
		
		//'Init'
		public Keyword getInitKeyword_1() { return cInitKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('subscribe' 'alarms' '[' raiseAlarm+=ActionAlarm (',' raiseAlarm+=ActionAlarm)* ']')? & ('fire' 'Commands' '['
		//fireCommand+=ActionCommand (',' fireCommand+=ActionCommand)* ']')? & ('subscribe' 'events' '['
		//publishEvent+=ActionEvent (',' publishEvent+=ActionEvent)* ']')? & ('subscribe' 'data' '['
		//triggerDataPoint+=ActionDataPoint (',' triggerDataPoint+=ActionDataPoint)* ']')? & ('execute' 'Operations' '['
		//executeOperation+=ActionOperation (',' executeOperation+=ActionOperation)* ']')?
		public UnorderedGroup getUnorderedGroup_3() { return cUnorderedGroup_3; }
		
		//('subscribe' 'alarms' '[' raiseAlarm+=ActionAlarm (',' raiseAlarm+=ActionAlarm)* ']')?
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//'subscribe'
		public Keyword getSubscribeKeyword_3_0_0() { return cSubscribeKeyword_3_0_0; }
		
		//'alarms'
		public Keyword getAlarmsKeyword_3_0_1() { return cAlarmsKeyword_3_0_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_0_2() { return cLeftSquareBracketKeyword_3_0_2; }
		
		//raiseAlarm+=ActionAlarm
		public Assignment getRaiseAlarmAssignment_3_0_3() { return cRaiseAlarmAssignment_3_0_3; }
		
		//ActionAlarm
		public RuleCall getRaiseAlarmActionAlarmParserRuleCall_3_0_3_0() { return cRaiseAlarmActionAlarmParserRuleCall_3_0_3_0; }
		
		//(',' raiseAlarm+=ActionAlarm)*
		public Group getGroup_3_0_4() { return cGroup_3_0_4; }
		
		//','
		public Keyword getCommaKeyword_3_0_4_0() { return cCommaKeyword_3_0_4_0; }
		
		//raiseAlarm+=ActionAlarm
		public Assignment getRaiseAlarmAssignment_3_0_4_1() { return cRaiseAlarmAssignment_3_0_4_1; }
		
		//ActionAlarm
		public RuleCall getRaiseAlarmActionAlarmParserRuleCall_3_0_4_1_0() { return cRaiseAlarmActionAlarmParserRuleCall_3_0_4_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_0_5() { return cRightSquareBracketKeyword_3_0_5; }
		
		//('fire' 'Commands' '[' fireCommand+=ActionCommand (',' fireCommand+=ActionCommand)* ']')?
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'fire'
		public Keyword getFireKeyword_3_1_0() { return cFireKeyword_3_1_0; }
		
		//'Commands'
		public Keyword getCommandsKeyword_3_1_1() { return cCommandsKeyword_3_1_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_1_2() { return cLeftSquareBracketKeyword_3_1_2; }
		
		//fireCommand+=ActionCommand
		public Assignment getFireCommandAssignment_3_1_3() { return cFireCommandAssignment_3_1_3; }
		
		//ActionCommand
		public RuleCall getFireCommandActionCommandParserRuleCall_3_1_3_0() { return cFireCommandActionCommandParserRuleCall_3_1_3_0; }
		
		//(',' fireCommand+=ActionCommand)*
		public Group getGroup_3_1_4() { return cGroup_3_1_4; }
		
		//','
		public Keyword getCommaKeyword_3_1_4_0() { return cCommaKeyword_3_1_4_0; }
		
		//fireCommand+=ActionCommand
		public Assignment getFireCommandAssignment_3_1_4_1() { return cFireCommandAssignment_3_1_4_1; }
		
		//ActionCommand
		public RuleCall getFireCommandActionCommandParserRuleCall_3_1_4_1_0() { return cFireCommandActionCommandParserRuleCall_3_1_4_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_1_5() { return cRightSquareBracketKeyword_3_1_5; }
		
		//('subscribe' 'events' '[' publishEvent+=ActionEvent (',' publishEvent+=ActionEvent)* ']')?
		public Group getGroup_3_2() { return cGroup_3_2; }
		
		//'subscribe'
		public Keyword getSubscribeKeyword_3_2_0() { return cSubscribeKeyword_3_2_0; }
		
		//'events'
		public Keyword getEventsKeyword_3_2_1() { return cEventsKeyword_3_2_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_2_2() { return cLeftSquareBracketKeyword_3_2_2; }
		
		//publishEvent+=ActionEvent
		public Assignment getPublishEventAssignment_3_2_3() { return cPublishEventAssignment_3_2_3; }
		
		//ActionEvent
		public RuleCall getPublishEventActionEventParserRuleCall_3_2_3_0() { return cPublishEventActionEventParserRuleCall_3_2_3_0; }
		
		//(',' publishEvent+=ActionEvent)*
		public Group getGroup_3_2_4() { return cGroup_3_2_4; }
		
		//','
		public Keyword getCommaKeyword_3_2_4_0() { return cCommaKeyword_3_2_4_0; }
		
		//publishEvent+=ActionEvent
		public Assignment getPublishEventAssignment_3_2_4_1() { return cPublishEventAssignment_3_2_4_1; }
		
		//ActionEvent
		public RuleCall getPublishEventActionEventParserRuleCall_3_2_4_1_0() { return cPublishEventActionEventParserRuleCall_3_2_4_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_2_5() { return cRightSquareBracketKeyword_3_2_5; }
		
		//('subscribe' 'data' '[' triggerDataPoint+=ActionDataPoint (',' triggerDataPoint+=ActionDataPoint)* ']')?
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//'subscribe'
		public Keyword getSubscribeKeyword_3_3_0() { return cSubscribeKeyword_3_3_0; }
		
		//'data'
		public Keyword getDataKeyword_3_3_1() { return cDataKeyword_3_3_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_3_2() { return cLeftSquareBracketKeyword_3_3_2; }
		
		//triggerDataPoint+=ActionDataPoint
		public Assignment getTriggerDataPointAssignment_3_3_3() { return cTriggerDataPointAssignment_3_3_3; }
		
		//ActionDataPoint
		public RuleCall getTriggerDataPointActionDataPointParserRuleCall_3_3_3_0() { return cTriggerDataPointActionDataPointParserRuleCall_3_3_3_0; }
		
		//(',' triggerDataPoint+=ActionDataPoint)*
		public Group getGroup_3_3_4() { return cGroup_3_3_4; }
		
		//','
		public Keyword getCommaKeyword_3_3_4_0() { return cCommaKeyword_3_3_4_0; }
		
		//triggerDataPoint+=ActionDataPoint
		public Assignment getTriggerDataPointAssignment_3_3_4_1() { return cTriggerDataPointAssignment_3_3_4_1; }
		
		//ActionDataPoint
		public RuleCall getTriggerDataPointActionDataPointParserRuleCall_3_3_4_1_0() { return cTriggerDataPointActionDataPointParserRuleCall_3_3_4_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_3_5() { return cRightSquareBracketKeyword_3_3_5; }
		
		//('execute' 'Operations' '[' executeOperation+=ActionOperation (',' executeOperation+=ActionOperation)* ']')?
		public Group getGroup_3_4() { return cGroup_3_4; }
		
		//'execute'
		public Keyword getExecuteKeyword_3_4_0() { return cExecuteKeyword_3_4_0; }
		
		//'Operations'
		public Keyword getOperationsKeyword_3_4_1() { return cOperationsKeyword_3_4_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_4_2() { return cLeftSquareBracketKeyword_3_4_2; }
		
		//executeOperation+=ActionOperation
		public Assignment getExecuteOperationAssignment_3_4_3() { return cExecuteOperationAssignment_3_4_3; }
		
		//ActionOperation
		public RuleCall getExecuteOperationActionOperationParserRuleCall_3_4_3_0() { return cExecuteOperationActionOperationParserRuleCall_3_4_3_0; }
		
		//(',' executeOperation+=ActionOperation)*
		public Group getGroup_3_4_4() { return cGroup_3_4_4; }
		
		//','
		public Keyword getCommaKeyword_3_4_4_0() { return cCommaKeyword_3_4_4_0; }
		
		//executeOperation+=ActionOperation
		public Assignment getExecuteOperationAssignment_3_4_4_1() { return cExecuteOperationAssignment_3_4_4_1; }
		
		//ActionOperation
		public RuleCall getExecuteOperationActionOperationParserRuleCall_3_4_4_1_0() { return cExecuteOperationActionOperationParserRuleCall_3_4_4_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_4_5() { return cRightSquareBracketKeyword_3_4_5; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ResponseBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.ResponseBlock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cResponseBlockAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cResponseAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cResponseResponseCrossReference_1_0 = (CrossReference)cResponseAssignment_1.eContents().get(0);
		private final RuleCall cResponseResponseQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cResponseResponseCrossReference_1_0.eContents().get(1);
		
		//ResponseBlock mncModel::ResponseBlock:
		//	{mncModel::ResponseBlock} response=[mncModel::Response|QualifiedName]?;
		@Override public ParserRule getRule() { return rule; }
		
		//{mncModel::ResponseBlock} response=[mncModel::Response|QualifiedName]?
		public Group getGroup() { return cGroup; }
		
		//{mncModel::ResponseBlock}
		public Action getResponseBlockAction_0() { return cResponseBlockAction_0; }
		
		//response=[mncModel::Response|QualifiedName]?
		public Assignment getResponseAssignment_1() { return cResponseAssignment_1; }
		
		//[mncModel::Response|QualifiedName]
		public CrossReference getResponseResponseCrossReference_1_0() { return cResponseResponseCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getResponseResponseQualifiedNameParserRuleCall_1_0_1() { return cResponseResponseQualifiedNameParserRuleCall_1_0_1; }
	}
	public class ActionCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.ActionCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionCommandAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cCommandAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cCommandCommandCrossReference_1_0 = (CrossReference)cCommandAssignment_1.eContents().get(0);
		private final RuleCall cCommandCommandQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cCommandCommandCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActionParemeterAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActionParemeterActionParemeterParserRuleCall_3_0 = (RuleCall)cActionParemeterAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cResponsesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cResponseHandlingAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cResponseHandlingResponseBlockParserRuleCall_5_2_0 = (RuleCall)cResponseHandlingAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cResponseHandlingAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cResponseHandlingResponseBlockParserRuleCall_5_3_1_0 = (RuleCall)cResponseHandlingAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		
		//ActionCommand mncModel::ActionCommand:
		//	{mncModel::ActionCommand} command=[mncModel::Command|QualifiedName] '('
		//	actionParemeter=ActionParemeter? ')' ('responses=>' '{' responseHandling+=ResponseBlock (','
		//	responseHandling+=ResponseBlock)* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{mncModel::ActionCommand} command=[mncModel::Command|QualifiedName] '(' actionParemeter=ActionParemeter? ')'
		//('responses=>' '{' responseHandling+=ResponseBlock (',' responseHandling+=ResponseBlock)* '}')?
		public Group getGroup() { return cGroup; }
		
		//{mncModel::ActionCommand}
		public Action getActionCommandAction_0() { return cActionCommandAction_0; }
		
		//command=[mncModel::Command|QualifiedName]
		public Assignment getCommandAssignment_1() { return cCommandAssignment_1; }
		
		//[mncModel::Command|QualifiedName]
		public CrossReference getCommandCommandCrossReference_1_0() { return cCommandCommandCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getCommandCommandQualifiedNameParserRuleCall_1_0_1() { return cCommandCommandQualifiedNameParserRuleCall_1_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//actionParemeter=ActionParemeter?
		public Assignment getActionParemeterAssignment_3() { return cActionParemeterAssignment_3; }
		
		//ActionParemeter
		public RuleCall getActionParemeterActionParemeterParserRuleCall_3_0() { return cActionParemeterActionParemeterParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//('responses=>' '{' responseHandling+=ResponseBlock (',' responseHandling+=ResponseBlock)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'responses=>'
		public Keyword getResponsesKeyword_5_0() { return cResponsesKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//responseHandling+=ResponseBlock
		public Assignment getResponseHandlingAssignment_5_2() { return cResponseHandlingAssignment_5_2; }
		
		//ResponseBlock
		public RuleCall getResponseHandlingResponseBlockParserRuleCall_5_2_0() { return cResponseHandlingResponseBlockParserRuleCall_5_2_0; }
		
		//(',' responseHandling+=ResponseBlock)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//','
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//responseHandling+=ResponseBlock
		public Assignment getResponseHandlingAssignment_5_3_1() { return cResponseHandlingAssignment_5_3_1; }
		
		//ResponseBlock
		public RuleCall getResponseHandlingResponseBlockParserRuleCall_5_3_1_0() { return cResponseHandlingResponseBlockParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
	}
	public class ActionAlarmElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.ActionAlarm");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionAlarmAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAlarmAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cAlarmAlarmCrossReference_1_0 = (CrossReference)cAlarmAssignment_1.eContents().get(0);
		private final RuleCall cAlarmAlarmQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cAlarmAlarmCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActionParemeterAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActionParemeterActionParemeterParserRuleCall_3_0 = (RuleCall)cActionParemeterAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ActionAlarm mncModel::ActionAlarm:
		//	{mncModel::ActionAlarm} alarm=[mncModel::Alarm|QualifiedName] '('
		//	actionParemeter=ActionParemeter? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{mncModel::ActionAlarm} alarm=[mncModel::Alarm|QualifiedName] '(' actionParemeter=ActionParemeter? ')'
		public Group getGroup() { return cGroup; }
		
		//{mncModel::ActionAlarm}
		public Action getActionAlarmAction_0() { return cActionAlarmAction_0; }
		
		//alarm=[mncModel::Alarm|QualifiedName]
		public Assignment getAlarmAssignment_1() { return cAlarmAssignment_1; }
		
		//[mncModel::Alarm|QualifiedName]
		public CrossReference getAlarmAlarmCrossReference_1_0() { return cAlarmAlarmCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getAlarmAlarmQualifiedNameParserRuleCall_1_0_1() { return cAlarmAlarmQualifiedNameParserRuleCall_1_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//actionParemeter=ActionParemeter?
		public Assignment getActionParemeterAssignment_3() { return cActionParemeterAssignment_3; }
		
		//ActionParemeter
		public RuleCall getActionParemeterActionParemeterParserRuleCall_3_0() { return cActionParemeterActionParemeterParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ActionEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.ActionEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cEventAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cEventEventCrossReference_1_0 = (CrossReference)cEventAssignment_1.eContents().get(0);
		private final RuleCall cEventEventQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cEventEventCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActionParemeterAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActionParemeterActionParemeterParserRuleCall_3_0 = (RuleCall)cActionParemeterAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ActionEvent mncModel::ActionEvent:
		//	{mncModel::ActionEvent} event=[mncModel::Event|QualifiedName] '('
		//	actionParemeter=ActionParemeter? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{mncModel::ActionEvent} event=[mncModel::Event|QualifiedName] '(' actionParemeter=ActionParemeter? ')'
		public Group getGroup() { return cGroup; }
		
		//{mncModel::ActionEvent}
		public Action getActionEventAction_0() { return cActionEventAction_0; }
		
		//event=[mncModel::Event|QualifiedName]
		public Assignment getEventAssignment_1() { return cEventAssignment_1; }
		
		//[mncModel::Event|QualifiedName]
		public CrossReference getEventEventCrossReference_1_0() { return cEventEventCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getEventEventQualifiedNameParserRuleCall_1_0_1() { return cEventEventQualifiedNameParserRuleCall_1_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//actionParemeter=ActionParemeter?
		public Assignment getActionParemeterAssignment_3() { return cActionParemeterAssignment_3; }
		
		//ActionParemeter
		public RuleCall getActionParemeterActionParemeterParserRuleCall_3_0() { return cActionParemeterActionParemeterParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ActionDataPointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.ActionDataPoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionDataPointAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cDataPointAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cDataPointDataPointCrossReference_1_0 = (CrossReference)cDataPointAssignment_1.eContents().get(0);
		private final RuleCall cDataPointDataPointQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cDataPointDataPointCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActionParemeterAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActionParemeterActionParemeterParserRuleCall_3_0 = (RuleCall)cActionParemeterAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ActionDataPoint mncModel::ActionDataPoint:
		//	{mncModel::ActionDataPoint} dataPoint=[mncModel::DataPoint|QualifiedName] '('
		//	actionParemeter=ActionParemeter? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{mncModel::ActionDataPoint} dataPoint=[mncModel::DataPoint|QualifiedName] '(' actionParemeter=ActionParemeter? ')'
		public Group getGroup() { return cGroup; }
		
		//{mncModel::ActionDataPoint}
		public Action getActionDataPointAction_0() { return cActionDataPointAction_0; }
		
		//dataPoint=[mncModel::DataPoint|QualifiedName]
		public Assignment getDataPointAssignment_1() { return cDataPointAssignment_1; }
		
		//[mncModel::DataPoint|QualifiedName]
		public CrossReference getDataPointDataPointCrossReference_1_0() { return cDataPointDataPointCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getDataPointDataPointQualifiedNameParserRuleCall_1_0_1() { return cDataPointDataPointQualifiedNameParserRuleCall_1_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//actionParemeter=ActionParemeter?
		public Assignment getActionParemeterAssignment_3() { return cActionParemeterAssignment_3; }
		
		//ActionParemeter
		public RuleCall getActionParemeterActionParemeterParserRuleCall_3_0() { return cActionParemeterActionParemeterParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ActionOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.ActionOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionOperationAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cOperationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cOperationOperationCrossReference_1_0 = (CrossReference)cOperationAssignment_1.eContents().get(0);
		private final RuleCall cOperationOperationQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cOperationOperationCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActionParemeterAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActionParemeterActionParemeterParserRuleCall_3_0 = (RuleCall)cActionParemeterAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ActionOperation mncModel::ActionOperation:
		//	{mncModel::ActionOperation} operation=[operations::Operation|QualifiedName] '('
		//	actionParemeter=ActionParemeter? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{mncModel::ActionOperation} operation=[operations::Operation|QualifiedName] '(' actionParemeter=ActionParemeter? ')'
		public Group getGroup() { return cGroup; }
		
		//{mncModel::ActionOperation}
		public Action getActionOperationAction_0() { return cActionOperationAction_0; }
		
		//operation=[operations::Operation|QualifiedName]
		public Assignment getOperationAssignment_1() { return cOperationAssignment_1; }
		
		//[operations::Operation|QualifiedName]
		public CrossReference getOperationOperationCrossReference_1_0() { return cOperationOperationCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getOperationOperationQualifiedNameParserRuleCall_1_0_1() { return cOperationOperationQualifiedNameParserRuleCall_1_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//actionParemeter=ActionParemeter?
		public Assignment getActionParemeterAssignment_3() { return cActionParemeterAssignment_3; }
		
		//ActionParemeter
		public RuleCall getActionParemeterActionParemeterParserRuleCall_3_0() { return cActionParemeterActionParemeterParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ActionParemeterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.capability.Capability.ActionParemeter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cParameterValuesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cParameterValuesPrimitiveValueParserRuleCall_0_0 = (RuleCall)cParameterValuesAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cParameterValuesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cParameterValuesPrimitiveValueParserRuleCall_1_1_0 = (RuleCall)cParameterValuesAssignment_1_1.eContents().get(0);
		
		//ActionParemeter mncModel::ActionParemeter:
		//	parameterValues+=PrimitiveValue (',' parameterValues+=PrimitiveValue)*;
		@Override public ParserRule getRule() { return rule; }
		
		//parameterValues+=PrimitiveValue (',' parameterValues+=PrimitiveValue)*
		public Group getGroup() { return cGroup; }
		
		//parameterValues+=PrimitiveValue
		public Assignment getParameterValuesAssignment_0() { return cParameterValuesAssignment_0; }
		
		//PrimitiveValue
		public RuleCall getParameterValuesPrimitiveValueParserRuleCall_0_0() { return cParameterValuesPrimitiveValueParserRuleCall_0_0; }
		
		//(',' parameterValues+=PrimitiveValue)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//parameterValues+=PrimitiveValue
		public Assignment getParameterValuesAssignment_1_1() { return cParameterValuesAssignment_1_1; }
		
		//PrimitiveValue
		public RuleCall getParameterValuesPrimitiveValueParserRuleCall_1_1_0() { return cParameterValuesPrimitiveValueParserRuleCall_1_1_0; }
	}
	
	
	private final CapabilityElements pCapability;
	private final ControlCapabilitiesElements pControlCapabilities;
	private final CapabilitiesOutcomeElements pCapabilitiesOutcome;
	private final ActionElements pAction;
	private final ResponseBlockElements pResponseBlock;
	private final ActionCommandElements pActionCommand;
	private final ActionAlarmElements pActionAlarm;
	private final ActionEventElements pActionEvent;
	private final ActionDataPointElements pActionDataPoint;
	private final ActionOperationElements pActionOperation;
	private final ActionParemeterElements pActionParemeter;
	
	private final Grammar grammar;
	
	private final DmlGrammarAccess gaDml;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CapabilityGrammarAccess(GrammarProvider grammarProvider,
			DmlGrammarAccess gaDml,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaDml = gaDml;
		this.gaTerminals = gaTerminals;
		this.pCapability = new CapabilityElements();
		this.pControlCapabilities = new ControlCapabilitiesElements();
		this.pCapabilitiesOutcome = new CapabilitiesOutcomeElements();
		this.pAction = new ActionElements();
		this.pResponseBlock = new ResponseBlockElements();
		this.pActionCommand = new ActionCommandElements();
		this.pActionAlarm = new ActionAlarmElements();
		this.pActionEvent = new ActionEventElements();
		this.pActionDataPoint = new ActionDataPointElements();
		this.pActionOperation = new ActionOperationElements();
		this.pActionParemeter = new ActionParemeterElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.capability.Capability".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public DmlGrammarAccess getDmlGrammarAccess() {
		return gaDml;
	}
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Capability capabilityModel::Capability:
	//	{capabilityModel::Capability}
	//	'Capability' name=EString 'compatible' 'component' 'interface'
	//	componentInterface+=[mncModel::InterfaceDescription|QualifiedName] (","
	//	componentInterface+=[mncModel::InterfaceDescription|QualifiedName]*)?
	//	'{'
	//	requiredINITProcess=Action? ('providesControlCapabilities'
	//	providesControlCapabilities=ControlCapabilities)? ('providesOutcomes'
	//	providesOutcomes=CapabilitiesOutcome)?
	//	'}';
	public CapabilityElements getCapabilityAccess() {
		return pCapability;
	}
	
	public ParserRule getCapabilityRule() {
		return getCapabilityAccess().getRule();
	}
	
	//ControlCapabilities capabilityModel::ControlCapabilities:
	//	{capabilityModel::ControlCapabilities}
	//	'{' (('fireable' 'commands' ':' commands+=[mncModel::Command|QualifiedName] (","
	//	commands+=[mncModel::Command|QualifiedName])*)? & ('receivable' 'events' ':' events+=[mncModel::Event|QualifiedName]
	//	("," events+=[mncModel::Event|QualifiedName])*)? & ('raised' 'alarms' ':' alarms+=[mncModel::Alarm|QualifiedName] (","
	//	alarms+=[mncModel::Alarm|QualifiedName])*)? & ('subscribable' 'DataPoints' ':'
	//	dataPoints+=[mncModel::DataPoint|QualifiedName] ("," dataPoints+=[mncModel::DataPoint|QualifiedName])*)?)
	//	'}';
	public ControlCapabilitiesElements getControlCapabilitiesAccess() {
		return pControlCapabilities;
	}
	
	public ParserRule getControlCapabilitiesRule() {
		return getControlCapabilitiesAccess().getRule();
	}
	
	//CapabilitiesOutcome capabilityModel::CapabilitiesOutcome:
	//	{capabilityModel::CapabilitiesOutcome}
	//	'{' (('receivable' 'responses' responses+=[mncModel::Response|QualifiedName] (','
	//	responses+=[mncModel::Response|QualifiedName]*)?)? & ('receivable' 'events' events+=[mncModel::Event|QualifiedName]
	//	(',' events+=[mncModel::Event|QualifiedName]*)?)? & ('receivable' 'alarms' alarms+=[mncModel::Alarm|QualifiedName]
	//	(',' alarms+=[mncModel::Alarm|QualifiedName]*)?)? & ('receivable' 'dataPoints'
	//	dataPoints+=[mncModel::DataPoint|QualifiedName] (',' dataPoints+=[mncModel::DataPoint|QualifiedName])*)?)
	//	'}';
	public CapabilitiesOutcomeElements getCapabilitiesOutcomeAccess() {
		return pCapabilitiesOutcome;
	}
	
	public ParserRule getCapabilitiesOutcomeRule() {
		return getCapabilitiesOutcomeAccess().getRule();
	}
	
	//Action mncModel::Action:
	//	{mncModel::Action}
	//	'Init'
	//	'{' (('subscribe' 'alarms' '[' raiseAlarm+=ActionAlarm (',' raiseAlarm+=ActionAlarm)* ']')? & ('fire' 'Commands' '['
	//	fireCommand+=ActionCommand (',' fireCommand+=ActionCommand)* ']')? & ('subscribe' 'events' '['
	//	publishEvent+=ActionEvent (',' publishEvent+=ActionEvent)* ']')? & ('subscribe' 'data' '['
	//	triggerDataPoint+=ActionDataPoint (',' triggerDataPoint+=ActionDataPoint)* ']')? & ('execute' 'Operations' '['
	//	executeOperation+=ActionOperation (',' executeOperation+=ActionOperation)* ']')?)
	//	'}';
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//ResponseBlock mncModel::ResponseBlock:
	//	{mncModel::ResponseBlock} response=[mncModel::Response|QualifiedName]?;
	public ResponseBlockElements getResponseBlockAccess() {
		return pResponseBlock;
	}
	
	public ParserRule getResponseBlockRule() {
		return getResponseBlockAccess().getRule();
	}
	
	//ActionCommand mncModel::ActionCommand:
	//	{mncModel::ActionCommand} command=[mncModel::Command|QualifiedName] '('
	//	actionParemeter=ActionParemeter? ')' ('responses=>' '{' responseHandling+=ResponseBlock (','
	//	responseHandling+=ResponseBlock)* '}')?;
	public ActionCommandElements getActionCommandAccess() {
		return pActionCommand;
	}
	
	public ParserRule getActionCommandRule() {
		return getActionCommandAccess().getRule();
	}
	
	//ActionAlarm mncModel::ActionAlarm:
	//	{mncModel::ActionAlarm} alarm=[mncModel::Alarm|QualifiedName] '('
	//	actionParemeter=ActionParemeter? ')';
	public ActionAlarmElements getActionAlarmAccess() {
		return pActionAlarm;
	}
	
	public ParserRule getActionAlarmRule() {
		return getActionAlarmAccess().getRule();
	}
	
	//ActionEvent mncModel::ActionEvent:
	//	{mncModel::ActionEvent} event=[mncModel::Event|QualifiedName] '('
	//	actionParemeter=ActionParemeter? ')';
	public ActionEventElements getActionEventAccess() {
		return pActionEvent;
	}
	
	public ParserRule getActionEventRule() {
		return getActionEventAccess().getRule();
	}
	
	//ActionDataPoint mncModel::ActionDataPoint:
	//	{mncModel::ActionDataPoint} dataPoint=[mncModel::DataPoint|QualifiedName] '('
	//	actionParemeter=ActionParemeter? ')';
	public ActionDataPointElements getActionDataPointAccess() {
		return pActionDataPoint;
	}
	
	public ParserRule getActionDataPointRule() {
		return getActionDataPointAccess().getRule();
	}
	
	//ActionOperation mncModel::ActionOperation:
	//	{mncModel::ActionOperation} operation=[operations::Operation|QualifiedName] '('
	//	actionParemeter=ActionParemeter? ')';
	public ActionOperationElements getActionOperationAccess() {
		return pActionOperation;
	}
	
	public ParserRule getActionOperationRule() {
		return getActionOperationAccess().getRule();
	}
	
	//ActionParemeter mncModel::ActionParemeter:
	//	parameterValues+=PrimitiveValue (',' parameterValues+=PrimitiveValue)*;
	public ActionParemeterElements getActionParemeterAccess() {
		return pActionParemeter;
	}
	
	public ParserRule getActionParemeterRule() {
		return getActionParemeterAccess().getRule();
	}
	
	//DataPackage dataModel::DataPackage:
	//	('Package' name=EString)?
	//	dataModelCollections+=DataModel*;
	public DmlGrammarAccess.DataPackageElements getDataPackageAccess() {
		return gaDml.getDataPackageAccess();
	}
	
	public ParserRule getDataPackageRule() {
		return getDataPackageAccess().getRule();
	}
	
	//DataModel dataModel::DataModel:
	//	'DataModel' name=EString
	//	'{' ('primitives' '{' primitives+=Parameter ("," primitives+=Parameter)* '}')? & ('composites' '{'
	//	composites+=[dataModel::DataModel] ("," composites+=[dataModel::DataModel])* '}')?
	//	'}';
	public DmlGrammarAccess.DataModelElements getDataModelAccess() {
		return gaDml.getDataModelAccess();
	}
	
	public ParserRule getDataModelRule() {
		return getDataModelAccess().getRule();
	}
	
	//Parameter dataModel::Parameter:
	//	SimpleType | AbstractType | ArrayType;
	public DmlGrammarAccess.ParameterElements getParameterAccess() {
		return gaDml.getParameterAccess();
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)*;
	public DmlGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaDml.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//SimpleType dataModel::SimpleType:
	//	{dataModel::SimpleType} type=PrimitiveValueType name=EString ('=' value=PrimitiveValue)?;
	public DmlGrammarAccess.SimpleTypeElements getSimpleTypeAccess() {
		return gaDml.getSimpleTypeAccess();
	}
	
	public ParserRule getSimpleTypeRule() {
		return getSimpleTypeAccess().getRule();
	}
	
	//AbstractType dataModel::AbstractType:
	//	{dataModel::AbstractType} type=[dataModel::DataModel|QualifiedName] name=EString ('=' value=AbstractObjectValue)?;
	public DmlGrammarAccess.AbstractTypeElements getAbstractTypeAccess() {
		return gaDml.getAbstractTypeAccess();
	}
	
	public ParserRule getAbstractTypeRule() {
		return getAbstractTypeAccess().getRule();
	}
	
	//PrimitiveValue dataModel::PrimitiveValue:
	//	{dataModel::IntValue} intValue=EInt | {dataModel::FloatValue} floatValue=EFloat | {dataModel::StringValue}
	//	stringValue=STRING | {dataModel::BoolValue} boolValue=EBoolean | {dataModel::DateValue} dateValue=EDate | ArrayValues
	//	| AbstractObjectValue;
	public DmlGrammarAccess.PrimitiveValueElements getPrimitiveValueAccess() {
		return gaDml.getPrimitiveValueAccess();
	}
	
	public ParserRule getPrimitiveValueRule() {
		return getPrimitiveValueAccess().getRule();
	}
	
	//AbstractObjectValue dataModel::AbstractObjectValue:
	//	{dataModel::AbstractObjectValue} abstractValue=ID;
	public DmlGrammarAccess.AbstractObjectValueElements getAbstractObjectValueAccess() {
		return gaDml.getAbstractObjectValueAccess();
	}
	
	public ParserRule getAbstractObjectValueRule() {
		return getAbstractObjectValueAccess().getRule();
	}
	
	//ArrayValues dataModel::ArrayValues:
	//	{dataModel::ArrayValues}
	//	'[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']';
	public DmlGrammarAccess.ArrayValuesElements getArrayValuesAccess() {
		return gaDml.getArrayValuesAccess();
	}
	
	public ParserRule getArrayValuesRule() {
		return getArrayValuesAccess().getRule();
	}
	
	//ArrayType dataModel::Parameter:
	//	{dataModel::ArrayType} (primitiveType=PrimitiveValueType | dataModelType=[dataModel::DataModel|QualifiedName]) '[' ']'
	//	name=EString ('=' '[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']')?;
	public DmlGrammarAccess.ArrayTypeElements getArrayTypeAccess() {
		return gaDml.getArrayTypeAccess();
	}
	
	public ParserRule getArrayTypeRule() {
		return getArrayTypeAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public DmlGrammarAccess.EStringElements getEStringAccess() {
		return gaDml.getEStringAccess();
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum PrimitiveValueType returns dataModel::PrimitiveValueType:
	//	int | boolean | float | string | object | date;
	public DmlGrammarAccess.PrimitiveValueTypeElements getPrimitiveValueTypeAccess() {
		return gaDml.getPrimitiveValueTypeAccess();
	}
	
	public EnumRule getPrimitiveValueTypeRule() {
		return getPrimitiveValueTypeAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public DmlGrammarAccess.EIntElements getEIntAccess() {
		return gaDml.getEIntAccess();
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'false' | 'true';
	public DmlGrammarAccess.EBooleanElements getEBooleanAccess() {
		return gaDml.getEBooleanAccess();
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EFloat ecore::EFloat:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public DmlGrammarAccess.EFloatElements getEFloatAccess() {
		return gaDml.getEFloatAccess();
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//EDate ecore::EDate:
	//	Day '-' Month '-' Year;
	public DmlGrammarAccess.EDateElements getEDateAccess() {
		return gaDml.getEDateAccess();
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//Day:
	//	INT;
	public DmlGrammarAccess.DayElements getDayAccess() {
		return gaDml.getDayAccess();
	}
	
	public ParserRule getDayRule() {
		return getDayAccess().getRule();
	}
	
	//Month:
	//	INT;
	public DmlGrammarAccess.MonthElements getMonthAccess() {
		return gaDml.getMonthAccess();
	}
	
	public ParserRule getMonthRule() {
		return getMonthAccess().getRule();
	}
	
	//Year:
	//	INT;
	public DmlGrammarAccess.YearElements getYearAccess() {
		return gaDml.getYearAccess();
	}
	
	public ParserRule getYearRule() {
		return getYearAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
