/*
 * generated by Xtext 2.18.0
 */
package com.dml.dsl.parser.antlr;

import com.dml.dsl.parser.antlr.internal.InternalDmlParser;
import com.dml.dsl.services.DmlGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DmlParser extends AbstractAntlrParser {

	@Inject
	private DmlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDmlParser createParser(XtextTokenStream stream) {
		return new InternalDmlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DataPackage";
	}

	public DmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
