/**
 * generated by Xtext 2.15.0
 */
package com.operation.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.operation.dsl.OperationRuntimeModule;
import com.operation.dsl.OperationStandaloneSetup;
import com.operation.dsl.ide.OperationIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class OperationIdeSetup extends OperationStandaloneSetup {
  @Override
  public Injector createInjector() {
    OperationRuntimeModule _operationRuntimeModule = new OperationRuntimeModule();
    OperationIdeModule _operationIdeModule = new OperationIdeModule();
    return Guice.createInjector(Modules2.mixin(_operationRuntimeModule, _operationIdeModule));
  }
}
