/*
 * generated by Xtext 2.22.0
 */
package com.smr.activity.dsl.validation;

import com.dml.dsl.validation.DmlValidator;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;
import org.eclipse.xtext.validation.NamesAreUniqueValidator;

@ComposedChecks(validators = {NamesAreUniqueValidator.class})
public abstract class AbstractActivityDiagramValidator extends DmlValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://activitydiagram/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://mncModel/4.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://dataModelPackage/1.0"));
		return result;
	}
}
