/*
 * generated by Xtext 2.18.0
 */
package com.dml.dsl.serializer;

import com.dml.dsl.services.DmlGrammarAccess;
import com.google.inject.Inject;
import dataModelPackage.AbstractObjectValue;
import dataModelPackage.AbstractType;
import dataModelPackage.ArrayType;
import dataModelPackage.ArrayValues;
import dataModelPackage.BoolValue;
import dataModelPackage.DataModel;
import dataModelPackage.DataModelPackage;
import dataModelPackage.DataPackage;
import dataModelPackage.DateValue;
import dataModelPackage.FloatValue;
import dataModelPackage.IntValue;
import dataModelPackage.SimpleType;
import dataModelPackage.StringValue;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public abstract class AbstractDmlSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DmlGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == DataModelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DataModelPackage.ABSTRACT_OBJECT_VALUE:
				sequence_AbstractObjectValue(context, (AbstractObjectValue) semanticObject); 
				return; 
			case DataModelPackage.ABSTRACT_TYPE:
				sequence_AbstractType(context, (AbstractType) semanticObject); 
				return; 
			case DataModelPackage.ARRAY_TYPE:
				sequence_ArrayType(context, (ArrayType) semanticObject); 
				return; 
			case DataModelPackage.ARRAY_VALUES:
				sequence_ArrayValues(context, (ArrayValues) semanticObject); 
				return; 
			case DataModelPackage.BOOL_VALUE:
				sequence_PrimitiveValue(context, (BoolValue) semanticObject); 
				return; 
			case DataModelPackage.DATA_MODEL:
				sequence_DataModel(context, (DataModel) semanticObject); 
				return; 
			case DataModelPackage.DATA_PACKAGE:
				sequence_DataPackage(context, (DataPackage) semanticObject); 
				return; 
			case DataModelPackage.DATE_VALUE:
				sequence_PrimitiveValue(context, (DateValue) semanticObject); 
				return; 
			case DataModelPackage.FLOAT_VALUE:
				sequence_PrimitiveValue(context, (FloatValue) semanticObject); 
				return; 
			case DataModelPackage.INT_VALUE:
				sequence_PrimitiveValue(context, (IntValue) semanticObject); 
				return; 
			case DataModelPackage.SIMPLE_TYPE:
				sequence_SimpleType(context, (SimpleType) semanticObject); 
				return; 
			case DataModelPackage.STRING_VALUE:
				sequence_PrimitiveValue(context, (StringValue) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     PrimitiveValue returns AbstractObjectValue
	 *     AbstractObjectValue returns AbstractObjectValue
	 *
	 * Constraint:
	 *     abstractValue=ID
	 */
	protected void sequence_AbstractObjectValue(ISerializationContext context, AbstractObjectValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DataModelPackage.Literals.ABSTRACT_OBJECT_VALUE__ABSTRACT_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DataModelPackage.Literals.ABSTRACT_OBJECT_VALUE__ABSTRACT_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAbstractObjectValueAccess().getAbstractValueIDTerminalRuleCall_1_0(), semanticObject.getAbstractValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Parameter returns AbstractType
	 *     AbstractType returns AbstractType
	 *
	 * Constraint:
	 *     (type=[DataModel|QualifiedName] name=EString value=AbstractObjectValue?)
	 */
	protected void sequence_AbstractType(ISerializationContext context, AbstractType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Parameter returns ArrayType
	 *     ArrayType returns ArrayType
	 *
	 * Constraint:
	 *     ((primitiveType=PrimitiveValueType | dataModelType=[DataModel|QualifiedName]) name=EString (values+=PrimitiveValue values+=PrimitiveValue*)?)
	 */
	protected void sequence_ArrayType(ISerializationContext context, ArrayType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PrimitiveValue returns ArrayValues
	 *     ArrayValues returns ArrayValues
	 *
	 * Constraint:
	 *     (values+=PrimitiveValue values+=PrimitiveValue*)?
	 */
	protected void sequence_ArrayValues(ISerializationContext context, ArrayValues semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataModel returns DataModel
	 *
	 * Constraint:
	 *     {DataModel}
	 */
	protected void sequence_DataModel(ISerializationContext context, DataModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataPackage returns DataPackage
	 *
	 * Constraint:
	 *     ((name=EString dataModelCollections+=DataModel+) | dataModelCollections+=DataModel+)?
	 */
	protected void sequence_DataPackage(ISerializationContext context, DataPackage semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PrimitiveValue returns BoolValue
	 *
	 * Constraint:
	 *     boolValue=EBoolean
	 */
	protected void sequence_PrimitiveValue(ISerializationContext context, BoolValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DataModelPackage.Literals.BOOL_VALUE__BOOL_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DataModelPackage.Literals.BOOL_VALUE__BOOL_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrimitiveValueAccess().getBoolValueEBooleanParserRuleCall_3_1_0(), semanticObject.isBoolValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PrimitiveValue returns DateValue
	 *
	 * Constraint:
	 *     dateValue=EDate
	 */
	protected void sequence_PrimitiveValue(ISerializationContext context, DateValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DataModelPackage.Literals.DATE_VALUE__DATE_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DataModelPackage.Literals.DATE_VALUE__DATE_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrimitiveValueAccess().getDateValueEDateParserRuleCall_4_1_0(), semanticObject.getDateValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PrimitiveValue returns FloatValue
	 *
	 * Constraint:
	 *     floatValue=EFloat
	 */
	protected void sequence_PrimitiveValue(ISerializationContext context, FloatValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DataModelPackage.Literals.FLOAT_VALUE__FLOAT_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DataModelPackage.Literals.FLOAT_VALUE__FLOAT_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrimitiveValueAccess().getFloatValueEFloatParserRuleCall_1_1_0(), semanticObject.getFloatValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PrimitiveValue returns IntValue
	 *
	 * Constraint:
	 *     intValue=EInt
	 */
	protected void sequence_PrimitiveValue(ISerializationContext context, IntValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DataModelPackage.Literals.INT_VALUE__INT_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DataModelPackage.Literals.INT_VALUE__INT_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrimitiveValueAccess().getIntValueEIntParserRuleCall_0_1_0(), semanticObject.getIntValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PrimitiveValue returns StringValue
	 *
	 * Constraint:
	 *     stringValue=STRING
	 */
	protected void sequence_PrimitiveValue(ISerializationContext context, StringValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DataModelPackage.Literals.STRING_VALUE__STRING_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DataModelPackage.Literals.STRING_VALUE__STRING_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrimitiveValueAccess().getStringValueSTRINGTerminalRuleCall_2_1_0(), semanticObject.getStringValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Parameter returns SimpleType
	 *     SimpleType returns SimpleType
	 *
	 * Constraint:
	 *     (type=PrimitiveValueType name=EString value=PrimitiveValue?)
	 */
	protected void sequence_SimpleType(ISerializationContext context, SimpleType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
