/*
 * generated by Xtext 2.15.0
 */
package com.capability.ide

import com.capability.ide.highlighting.CapabilityLspSemanticHighlightingCalculator
import com.capability.ide.hover.CapabilityLspHoverService
import org.eclipse.xtext.ide.server.hover.IHoverService
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator

/**
 * KIDE-owned IDE bindings layered on the generated Capability services.
 */
class CapabilityIdeModule extends AbstractCapabilityIdeModule {

    def Class<? extends IHoverService> bindIHoverService() {
        CapabilityLspHoverService
    }

    def Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
        CapabilityLspSemanticHighlightingCalculator
    }
}
