/**
 * generated by Xtext 2.13.0
 */
package com.smr.activity.dsl;

import com.smr.activity.dsl.ActivityDiagramStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ActivityDiagramStandaloneSetup extends ActivityDiagramStandaloneSetupGenerated {
  public static void doSetup() {
    new ActivityDiagramStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
