/**
 * generated by Xtext 2.13.0
 */
package com.dml.dsl.validation;

import com.dml.dsl.validation.AbstractDmlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DmlValidator extends AbstractDmlValidator {
  public static final String INVALID_NAME = "invalidName";
}
