/**
 * generated by Xtext 2.13.0
 */
package com.dml.dsl.scoping;

import com.dml.dsl.scoping.AbstractDmlScopeProvider;
import com.google.inject.Inject;
import dataModelPackage.DataModel;
import dataModelPackage.DataModelPackage;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.resource.impl.ResourceDescriptionsProvider;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DmlScopeProvider extends AbstractDmlScopeProvider {
  @Inject
  private ResourceDescriptionsProvider resourceDescriptionsProvider;
  
  public List<DataModel> getCondidateDataModels() {
    List<DataModel> _xblockexpression = null;
    {
      List<DataModel> dataModelList = CollectionLiterals.<DataModel>newArrayList();
      Iterable<IEObjectDescription> _exportedObjectsByType = this.resourceDescriptionsProvider.createResourceDescriptions().getExportedObjectsByType(DataModelPackage.Literals.DATA_MODEL);
      for (final IEObjectDescription eObjectDescription : _exportedObjectsByType) {
        EObject _eObjectOrProxy = eObjectDescription.getEObjectOrProxy();
        dataModelList.add(((DataModel) _eObjectOrProxy));
      }
      _xblockexpression = dataModelList;
    }
    return _xblockexpression;
  }
}
