/**
 * generated by Xtext 2.15.0
 */
package com.mncml.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.mncml.dsl.MncRuntimeModule;
import com.mncml.dsl.MncStandaloneSetup;
import com.mncml.dsl.ide.MncIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MncIdeSetup extends MncStandaloneSetup {
  @Override
  public Injector createInjector() {
    MncRuntimeModule _mncRuntimeModule = new MncRuntimeModule();
    MncIdeModule _mncIdeModule = new MncIdeModule();
    return Guice.createInjector(Modules2.mixin(_mncRuntimeModule, _mncIdeModule));
  }
}
