import { describe, expect, it } from "vitest";
import type { GenerationResult } from "../src/types";
import {
  GenerationIntegrityError,
  validateGenerationResult
} from "../src/generationIntegrity";

const content = "cHVibGljIGNsYXNzIE91dCB7fQo=";
const hash = "cd840d30eb4d65df2ccf2a95f610870b62f732a547140b60009f795ad1cae7ec";
const sourceRevision = "a".repeat(64);
const krlRevision = "b".repeat(64);
const synthesisFingerprint = "c".repeat(64);
const fingerprint = "d".repeat(64);

function result(overrides: Partial<GenerationResult> = {}): GenerationResult {
  const manifest = {
    schemaVersion: "1",
    toolchainVersion: "1",
    fingerprint,
    source: { modelId: "flow.activity", revision: sourceRevision, etag: sourceRevision },
    knowledge: { revision: 3, etag: "e".repeat(64) },
    synthesis: { fingerprint: synthesisFingerprint },
    krl: { modelId: "bindings.krl", revision: krlRevision, etag: krlRevision },
    targetVersions: { java: "1" },
    artifacts: [{
      path: "generated/Out.java",
      mediaType: "text/x-java-source",
      bytes: 20,
      sha256: hash,
      targetId: "java",
      targetVersion: "1",
      targetName: "Java",
      templateName: "reference"
    }]
  };

  return {
    resultId: "gen-1",
    toolchainVersion: "1",
    fingerprint,
    sourceModelId: "flow.activity",
    sourceModelVersion: "4",
    sourceRevision,
    krlModelId: "bindings.krl",
    krlModelVersion: "2",
    krlRevision,
    knowledgeRevision: 3,
    knowledgeEtag: "e".repeat(64),
    synthesisFingerprint,
    manifestJson: JSON.stringify(manifest),
    artifacts: [{
      path: "generated/Out.java",
      mediaType: "text/x-java-source",
      contentBase64: content,
      sha256: hash,
      targetId: "java",
      targetVersion: "1"
    }],
    ...overrides
  };
}

const expected = {
  sourceModelId: "flow.activity",
  sourceRevision,
  krlModelId: "bindings.krl",
  krlRevision,
  synthesisFingerprint
};

describe("generation integrity", () => {
  it("accepts a response whose provenance, manifest and bytes all agree", async () => {
    await expect(validateGenerationResult(result(), expected)).resolves.toMatchObject({
      resultId: "gen-1",
      fingerprint
    });
  });

  it("rejects corrupted generated bytes", async () => {
    const broken = result();
    broken.artifacts[0].contentBase64 = "YnJva2Vu";
    await expect(validateGenerationResult(broken, expected)).rejects.toThrow(
      /invalid base64|hash mismatch/
    );
  });

  it("rejects path traversal in generated artifacts", async () => {
    const broken = result();
    broken.artifacts[0].path = "../Out.java";
    await expect(validateGenerationResult(broken, expected)).rejects.toThrow(
      GenerationIntegrityError
    );
  });

  it("rejects synthesis provenance drift", async () => {
    await expect(
      validateGenerationResult(
        result({ synthesisFingerprint: "f".repeat(64) }),
        expected
      )
    ).rejects.toThrow(/synthesis fingerprint mismatch/);
  });

  it("rejects manifest evidence that differs from response bytes", async () => {
    const broken = result();
    const manifest = JSON.parse(broken.manifestJson);
    manifest.artifacts[0].sha256 = "0".repeat(64);
    broken.manifestJson = JSON.stringify(manifest);
    await expect(validateGenerationResult(broken, expected)).rejects.toThrow(
      /manifest hash/
    );
  });
});
