/*
 * generated by Xtext 2.18.0
 */
package com.operation.dsl.parser.antlr;

import com.google.inject.Inject;
import com.operation.dsl.parser.antlr.internal.InternalOperationParser;
import com.operation.dsl.services.OperationGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class OperationParser extends AbstractAntlrParser {

	@Inject
	private OperationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOperationParser createParser(XtextTokenStream stream) {
		return new InternalOperationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "OperationDescriptions";
	}

	public OperationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OperationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
