/*
 * generated by Xtext 2.18.0
 */
package com.capability.serializer;

import CapabilityDescription.CapabilitiesOutcome;
import CapabilityDescription.Capability;
import CapabilityDescription.CapabilityDescriptionPackage;
import CapabilityDescription.ControlCapabilities;
import com.capability.services.CapabilityGrammarAccess;
import com.dml.dsl.serializer.DmlSemanticSequencer;
import com.google.inject.Inject;
import dataModelPackage.AbstractObjectValue;
import dataModelPackage.AbstractType;
import dataModelPackage.ArrayType;
import dataModelPackage.ArrayValues;
import dataModelPackage.BoolValue;
import dataModelPackage.DataModel;
import dataModelPackage.DataModelPackage;
import dataModelPackage.DataPackage;
import dataModelPackage.DateValue;
import dataModelPackage.FloatValue;
import dataModelPackage.IntValue;
import dataModelPackage.SimpleType;
import dataModelPackage.StringValue;
import java.util.Set;
import mncModel.ActionAlarm;
import mncModel.ActionCommand;
import mncModel.ActionDataPoint;
import mncModel.ActionEvent;
import mncModel.ActionOperation;
import mncModel.ActionParemeter;
import mncModel.MncModelPackage;
import mncModel.ResponseBlock;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;

@SuppressWarnings("all")
public class CapabilitySemanticSequencer extends DmlSemanticSequencer {

	@Inject
	private CapabilityGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == CapabilityDescriptionPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case CapabilityDescriptionPackage.CAPABILITIES_OUTCOME:
				sequence_CapabilitiesOutcome(context, (CapabilitiesOutcome) semanticObject); 
				return; 
			case CapabilityDescriptionPackage.CAPABILITY:
				sequence_Capability(context, (Capability) semanticObject); 
				return; 
			case CapabilityDescriptionPackage.CONTROL_CAPABILITIES:
				sequence_ControlCapabilities(context, (ControlCapabilities) semanticObject); 
				return; 
			}
		else if (epackage == DataModelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DataModelPackage.ABSTRACT_OBJECT_VALUE:
				sequence_AbstractObjectValue(context, (AbstractObjectValue) semanticObject); 
				return; 
			case DataModelPackage.ABSTRACT_TYPE:
				sequence_AbstractType(context, (AbstractType) semanticObject); 
				return; 
			case DataModelPackage.ARRAY_TYPE:
				sequence_ArrayType(context, (ArrayType) semanticObject); 
				return; 
			case DataModelPackage.ARRAY_VALUES:
				sequence_ArrayValues(context, (ArrayValues) semanticObject); 
				return; 
			case DataModelPackage.BOOL_VALUE:
				sequence_PrimitiveValue(context, (BoolValue) semanticObject); 
				return; 
			case DataModelPackage.DATA_MODEL:
				sequence_DataModel(context, (DataModel) semanticObject); 
				return; 
			case DataModelPackage.DATA_PACKAGE:
				sequence_DataPackage(context, (DataPackage) semanticObject); 
				return; 
			case DataModelPackage.DATE_VALUE:
				sequence_PrimitiveValue(context, (DateValue) semanticObject); 
				return; 
			case DataModelPackage.FLOAT_VALUE:
				sequence_PrimitiveValue(context, (FloatValue) semanticObject); 
				return; 
			case DataModelPackage.INT_VALUE:
				sequence_PrimitiveValue(context, (IntValue) semanticObject); 
				return; 
			case DataModelPackage.SIMPLE_TYPE:
				sequence_SimpleType(context, (SimpleType) semanticObject); 
				return; 
			case DataModelPackage.STRING_VALUE:
				sequence_PrimitiveValue(context, (StringValue) semanticObject); 
				return; 
			}
		else if (epackage == MncModelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MncModelPackage.ACTION:
				sequence_Action(context, (mncModel.Action) semanticObject); 
				return; 
			case MncModelPackage.ACTION_ALARM:
				sequence_ActionAlarm(context, (ActionAlarm) semanticObject); 
				return; 
			case MncModelPackage.ACTION_COMMAND:
				sequence_ActionCommand(context, (ActionCommand) semanticObject); 
				return; 
			case MncModelPackage.ACTION_DATA_POINT:
				sequence_ActionDataPoint(context, (ActionDataPoint) semanticObject); 
				return; 
			case MncModelPackage.ACTION_EVENT:
				sequence_ActionEvent(context, (ActionEvent) semanticObject); 
				return; 
			case MncModelPackage.ACTION_OPERATION:
				sequence_ActionOperation(context, (ActionOperation) semanticObject); 
				return; 
			case MncModelPackage.ACTION_PAREMETER:
				sequence_ActionParemeter(context, (ActionParemeter) semanticObject); 
				return; 
			case MncModelPackage.RESPONSE_BLOCK:
				sequence_ResponseBlock(context, (ResponseBlock) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     ActionAlarm returns ActionAlarm
	 *
	 * Constraint:
	 *     (alarm=[Alarm|QualifiedName] actionParemeter=ActionParemeter?)
	 */
	protected void sequence_ActionAlarm(ISerializationContext context, ActionAlarm semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ActionCommand returns ActionCommand
	 *
	 * Constraint:
	 *     (command=[Command|QualifiedName] actionParemeter=ActionParemeter? (responseHandling+=ResponseBlock responseHandling+=ResponseBlock*)?)
	 */
	protected void sequence_ActionCommand(ISerializationContext context, ActionCommand semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ActionDataPoint returns ActionDataPoint
	 *
	 * Constraint:
	 *     (dataPoint=[DataPoint|QualifiedName] actionParemeter=ActionParemeter?)
	 */
	protected void sequence_ActionDataPoint(ISerializationContext context, ActionDataPoint semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ActionEvent returns ActionEvent
	 *
	 * Constraint:
	 *     (event=[Event|QualifiedName] actionParemeter=ActionParemeter?)
	 */
	protected void sequence_ActionEvent(ISerializationContext context, ActionEvent semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ActionOperation returns ActionOperation
	 *
	 * Constraint:
	 *     (operation=[Operation|QualifiedName] actionParemeter=ActionParemeter?)
	 */
	protected void sequence_ActionOperation(ISerializationContext context, ActionOperation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ActionParemeter returns ActionParemeter
	 *
	 * Constraint:
	 *     (parameterValues+=PrimitiveValue parameterValues+=PrimitiveValue*)
	 */
	protected void sequence_ActionParemeter(ISerializationContext context, ActionParemeter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Action returns Action
	 *
	 * Constraint:
	 *     (
	 *         (raiseAlarm+=ActionAlarm raiseAlarm+=ActionAlarm*) | 
	 *         (fireCommand+=ActionCommand fireCommand+=ActionCommand*) | 
	 *         (publishEvent+=ActionEvent publishEvent+=ActionEvent*) | 
	 *         (triggerDataPoint+=ActionDataPoint triggerDataPoint+=ActionDataPoint*) | 
	 *         (executeOperation+=ActionOperation executeOperation+=ActionOperation*)
	 *     )*
	 */
	protected void sequence_Action(ISerializationContext context, mncModel.Action semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     CapabilitiesOutcome returns CapabilitiesOutcome
	 *
	 * Constraint:
	 *     (
	 *         (responses+=[Response|QualifiedName] responses+=[Response|QualifiedName]*) | 
	 *         (events+=[Event|QualifiedName] events+=[Event|QualifiedName]*) | 
	 *         (alarms+=[Alarm|QualifiedName] alarms+=[Alarm|QualifiedName]*) | 
	 *         (dataPoints+=[DataPoint|QualifiedName] dataPoints+=[DataPoint|QualifiedName]*)
	 *     )*
	 */
	protected void sequence_CapabilitiesOutcome(ISerializationContext context, CapabilitiesOutcome semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Capability returns Capability
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         componentInterface+=[InterfaceDescription|QualifiedName] 
	 *         componentInterface+=[InterfaceDescription|QualifiedName]* 
	 *         requiredINITProcess=Action? 
	 *         providesControlCapabilities=ControlCapabilities? 
	 *         providesOutcomes=CapabilitiesOutcome?
	 *     )
	 */
	protected void sequence_Capability(ISerializationContext context, Capability semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ControlCapabilities returns ControlCapabilities
	 *
	 * Constraint:
	 *     (
	 *         (commands+=[Command|QualifiedName] commands+=[Command|QualifiedName]*) | 
	 *         (events+=[Event|QualifiedName] events+=[Event|QualifiedName]*) | 
	 *         (alarms+=[Alarm|QualifiedName] alarms+=[Alarm|QualifiedName]*) | 
	 *         (dataPoints+=[DataPoint|QualifiedName] dataPoints+=[DataPoint|QualifiedName]*)
	 *     )*
	 */
	protected void sequence_ControlCapabilities(ISerializationContext context, ControlCapabilities semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ResponseBlock returns ResponseBlock
	 *
	 * Constraint:
	 *     response=[Response|QualifiedName]?
	 */
	protected void sequence_ResponseBlock(ISerializationContext context, ResponseBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
