/**
 * generated by Xtext 2.15.0
 */
package com.capability.ui;

import com.capability.ui.AbstractCapabilityUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CapabilityUiModule extends AbstractCapabilityUiModule {
  public CapabilityUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
