/**
 * generated by Xtext 2.15.0
 */
package com.mncml.dsl.formatting2;

import com.google.inject.Inject;
import com.mncml.dsl.services.MncGrammarAccess;
import java.util.Arrays;
import java.util.function.Consumer;
import mncModel.Action;
import mncModel.ActionAlarm;
import mncModel.ActionCommand;
import mncModel.ActionDataPoint;
import mncModel.ActionEvent;
import mncModel.Alarm;
import mncModel.AlarmBlock;
import mncModel.Command;
import mncModel.CommandResponseBlock;
import mncModel.ControlNode;
import mncModel.DataPoint;
import mncModel.DataPointBlock;
import mncModel.Event;
import mncModel.EventBlock;
import mncModel.InterfaceDescription;
import mncModel.SubscribableItemList;
import mncModel.Transition;
import mncModel.Validation;
import mncModel.utility.OperatingStateUtility;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

@SuppressWarnings("all")
public class MncFormatter extends AbstractFormatter2 {
  @Inject
  private MncGrammarAccess access;
  
  protected void _format(final InterfaceDescription id, @Extension final IFormattableDocument document) {
    InputOutput.<String>println(id.getName());
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getInterfaceDescriptionKeyword_1()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).assignment(this.access.getInterfaceDescriptionAccess().getNameAssignment_2()), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).assignment(this.access.getInterfaceDescriptionAccess().getUsesAssignment_3_1()), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).assignment(this.access.getInterfaceDescriptionAccess().getUsesAssignment_3_2_1()), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getCommaKeyword_3_2_0()), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getLeftCurlyBracketKeyword_4()), _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getLeftCurlyBracketKeyword_5_0_1_0_1()), _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getLeftCurlyBracketKeyword_5_1_1()), _function_7);
    final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getLeftCurlyBracketKeyword_5_3_1()), _function_8);
    final Procedure1<IHiddenRegionFormatter> _function_9 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getLeftCurlyBracketKeyword_5_4_1()), _function_9);
    final Procedure1<IHiddenRegionFormatter> _function_10 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getLeftCurlyBracketKeyword_5_5_1()), _function_10);
    final Procedure1<IHiddenRegionFormatter> _function_11 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getLeftCurlyBracketKeyword_5_5_1()), _function_11);
    final Procedure1<IHiddenRegionFormatter> _function_12 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getRightCurlyBracketKeyword_5_0_1_1()), _function_12);
    final Procedure1<IHiddenRegionFormatter> _function_13 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getRightCurlyBracketKeyword_5_1_3()), _function_13);
    final Procedure1<IHiddenRegionFormatter> _function_14 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getRightCurlyBracketKeyword_5_2_3()), _function_14);
    final Procedure1<IHiddenRegionFormatter> _function_15 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getRightCurlyBracketKeyword_5_3_3()), _function_15);
    final Procedure1<IHiddenRegionFormatter> _function_16 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getRightCurlyBracketKeyword_5_4_3()), _function_16);
    final Procedure1<IHiddenRegionFormatter> _function_17 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getRightCurlyBracketKeyword_5_5_3()), _function_17);
    final Procedure1<IHiddenRegionFormatter> _function_18 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getRightCurlyBracketKeyword_6()), _function_18);
    EList<Command> _commands = id.getCommands();
    boolean _tripleNotEquals = (_commands != null);
    if (_tripleNotEquals) {
      final Procedure1<IHiddenRegionFormatter> _function_19 = (IHiddenRegionFormatter it) -> {
        it.newLine();
      };
      document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getCommandsKeyword_5_2_0()), _function_19);
    }
    EList<Command> _commands_1 = id.getCommands();
    for (final Command com : _commands_1) {
      document.<Command>format(com);
    }
    EList<Event> _events = id.getEvents();
    boolean _tripleNotEquals_1 = (_events != null);
    if (_tripleNotEquals_1) {
      final Procedure1<IHiddenRegionFormatter> _function_20 = (IHiddenRegionFormatter it) -> {
        it.newLine();
      };
      document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getEventsKeyword_5_3_0()), _function_20);
    }
    EList<Event> _events_1 = id.getEvents();
    for (final Event event : _events_1) {
      document.<Event>format(event);
    }
    EList<DataPoint> _dataPoints = id.getDataPoints();
    boolean _tripleNotEquals_2 = (_dataPoints != null);
    if (_tripleNotEquals_2) {
      final Procedure1<IHiddenRegionFormatter> _function_21 = (IHiddenRegionFormatter it) -> {
        it.newLine();
      };
      document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getDataPointsKeyword_5_0_1_0_0()), _function_21);
    }
    EList<DataPoint> _dataPoints_1 = id.getDataPoints();
    for (final DataPoint dp : _dataPoints_1) {
      document.<DataPoint>format(dp);
    }
    EList<Alarm> _alarms = id.getAlarms();
    boolean _tripleNotEquals_3 = (_alarms != null);
    if (_tripleNotEquals_3) {
      final Procedure1<IHiddenRegionFormatter> _function_22 = (IHiddenRegionFormatter it) -> {
        it.newLine();
      };
      document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getAlarmsKeyword_5_1_0()), _function_22);
    }
    EList<Alarm> _alarms_1 = id.getAlarms();
    for (final Alarm alarm : _alarms_1) {
      document.<Alarm>format(alarm);
    }
    OperatingStateUtility _operatingStatesUtility = id.getOperatingStatesUtility();
    boolean _tripleNotEquals_4 = (_operatingStatesUtility != null);
    if (_tripleNotEquals_4) {
      final Procedure1<IHiddenRegionFormatter> _function_23 = (IHiddenRegionFormatter it) -> {
        it.newLine();
      };
      document.prepend(this.textRegionExtensions.regionFor(id).keyword(this.access.getInterfaceDescriptionAccess().getOperatingStatesKeyword_5_5_0()), _function_23);
    }
    document.<OperatingStateUtility>format(id.getOperatingStatesUtility());
    SubscribableItemList _subscribedItems = id.getSubscribedItems();
    boolean _tripleNotEquals_5 = (_subscribedItems != null);
    if (_tripleNotEquals_5) {
      document.<SubscribableItemList>format(id.getSubscribedItems());
    }
  }
  
  protected void _format(final OperatingStateUtility opsu, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    this.textRegionExtensions.regionFor(opsu).keyword(document.<Keyword>prepend(this.access.getOperatingStateUtilityAccess().getStartStatesKeyword_2_0(), _function));
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    this.textRegionExtensions.regionFor(opsu).keyword(document.<Keyword>append(this.access.getOperatingStateUtilityAccess().getStartStatesKeyword_2_0(), _function_1));
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    this.textRegionExtensions.regionFor(opsu).keyword(document.<Keyword>prepend(this.access.getOperatingStateUtilityAccess().getEndStatesKeyword_3_0(), _function_2));
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    this.textRegionExtensions.regionFor(opsu).keyword(document.<Keyword>append(this.access.getOperatingStateUtilityAccess().getEndStatesKeyword_3_0(), _function_3));
  }
  
  protected void _format(final Command com, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    this.textRegionExtensions.regionFor(com).keyword(document.<Keyword>append(this.access.getCommandAccess().getRightSquareBracketKeyword_5(), _function));
  }
  
  protected void _format(final Event event, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    this.textRegionExtensions.regionFor(event).keyword(document.<Keyword>append(this.access.getEventAccess().getRightSquareBracketKeyword_5(), _function));
  }
  
  protected void _format(final Alarm alarm, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    this.textRegionExtensions.regionFor(alarm).keyword(document.<Keyword>append(this.access.getAlarmAccess().getRightSquareBracketKeyword_6(), _function));
  }
  
  protected void _format(final DataPoint dp, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    this.textRegionExtensions.regionFor(dp).keyword(document.<Keyword>append(this.access.getDataPointAccess().getRightSquareBracketKeyword_7(), _function));
  }
  
  protected void _format(final SubscribableItemList list, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(list).keyword(this.access.getSubscribableItemListAccess().getSubscribableItemListKeyword_1()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(list).keyword(this.access.getSubscribableItemListAccess().getLeftCurlyBracketKeyword_2()), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(list).keyword(this.access.getSubscribableItemListAccess().getLeftCurlyBracketKeyword_2()), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(list).keyword(this.access.getSubscribableItemListAccess().getSubscribedEventsKeyword_3_0()), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(list).keyword(this.access.getSubscribableItemListAccess().getSubscribedAlarmsKeyword_4_0()), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(list).keyword(this.access.getSubscribableItemListAccess().getSubscribedDataPointsKeyword_5_0()), _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(list).keyword(this.access.getSubscribableItemListAccess().getRightCurlyBracketKeyword_6()), _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(list).keyword(this.access.getSubscribableItemListAccess().getRightCurlyBracketKeyword_6()), _function_7);
  }
  
  protected void _format(final ControlNode cn, @Extension final IFormattableDocument document) {
    InputOutput.<String>println(cn.getName());
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getControlNodeKeyword_1()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).assignment(this.access.getControlNodeAccess().getNameAssignment_2()), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getLeftCurlyBracketKeyword_4()), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getLeftCurlyBracketKeyword_5_1_1()), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getLeftCurlyBracketKeyword_5_2_1()), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getLeftCurlyBracketKeyword_5_3_1()), _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getLeftCurlyBracketKeyword_5_4_1()), _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getRightCurlyBracketKeyword_6()), _function_7);
    final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getRightCurlyBracketKeyword_5_1_3()), _function_8);
    final Procedure1<IHiddenRegionFormatter> _function_9 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getRightCurlyBracketKeyword_5_2_3()), _function_9);
    final Procedure1<IHiddenRegionFormatter> _function_10 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getRightCurlyBracketKeyword_5_3_3()), _function_10);
    final Procedure1<IHiddenRegionFormatter> _function_11 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cn).keyword(this.access.getControlNodeAccess().getRightCurlyBracketKeyword_5_4_3()), _function_11);
    final Consumer<CommandResponseBlock> _function_12 = (CommandResponseBlock it) -> {
      document.<CommandResponseBlock>format(it);
    };
    cn.getCommandResponseBlocks().forEach(_function_12);
    final Consumer<EventBlock> _function_13 = (EventBlock it) -> {
      document.<EventBlock>format(it);
    };
    cn.getEventBlocks().forEach(_function_13);
    final Consumer<AlarmBlock> _function_14 = (AlarmBlock it) -> {
      document.<AlarmBlock>format(it);
    };
    cn.getAlarmBlocks().forEach(_function_14);
    final Consumer<DataPointBlock> _function_15 = (DataPointBlock it) -> {
      document.<DataPointBlock>format(it);
    };
    cn.getDataPointBlocks().forEach(_function_15);
  }
  
  protected void _format(final CommandResponseBlock cr, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(cr).keyword(this.access.getCommandResponseBlockAccess().getCommandKeyword_1()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cr).assignment(this.access.getCommandResponseBlockAccess().getCommandAssignment_2()), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cr).keyword(this.access.getCommandResponseBlockAccess().getLeftCurlyBracketKeyword_3()), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cr).keyword(this.access.getCommandResponseBlockAccess().getRightCurlyBracketKeyword_6_4()), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cr).keyword(this.access.getCommandResponseBlockAccess().getRightCurlyBracketKeyword_7()), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cr).keyword(this.access.getCommandResponseBlockAccess().getLeftCurlyBracketKeyword_3()), _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cr).keyword(this.access.getCommandResponseBlockAccess().getLeftCurlyBracketKeyword_6_2()), _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cr).keyword(this.access.getCommandResponseBlockAccess().getRightCurlyBracketKeyword_6_4()), _function_7);
    final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(cr).keyword(this.access.getCommandResponseBlockAccess().getRightCurlyBracketKeyword_7()), _function_8);
    final Consumer<Validation> _function_9 = (Validation it) -> {
      document.<Validation>format(it);
    };
    cr.getValidationRules().forEach(_function_9);
    final Consumer<Validation> _function_10 = (Validation it) -> {
      document.<Action>format(it.getOnSuccessAction());
    };
    cr.getValidationRules().forEach(_function_10);
    document.<Action>format(cr.getAction());
  }
  
  protected void _format(final Validation vaidation, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(vaidation).keyword(this.access.getValidationAccess().getValidateKeyword_1()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(vaidation).keyword(this.access.getValidationAccess().getValidateKeyword_1()), _function_1);
  }
  
  protected void _format(final EventBlock ev, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ev).keyword(this.access.getEventBlockAccess().getLeftCurlyBracketKeyword_3()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ev).keyword(this.access.getEventBlockAccess().getRightCurlyBracketKeyword_6()), _function_1);
    document.<Action>format(ev.getAction());
    final Consumer<Validation> _function_2 = (Validation it) -> {
      document.<Action>format(it.getOnSuccessAction());
    };
    ev.getValidationRules().forEach(_function_2);
  }
  
  protected void _format(final AlarmBlock al, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(al).keyword(this.access.getAlarmBlockAccess().getLeftCurlyBracketKeyword_3()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(al).keyword(this.access.getAlarmBlockAccess().getRightCurlyBracketKeyword_6()), _function_1);
    final Consumer<Validation> _function_2 = (Validation it) -> {
      document.<Action>format(it.getOnSuccessAction());
    };
    al.getValidationRules().forEach(_function_2);
    document.<Action>format(al.getAction());
  }
  
  protected void _format(final DataPointBlock dp, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(dp).keyword(this.access.getDataPointBlockAccess().getLeftCurlyBracketKeyword_4()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(dp).keyword(this.access.getDataPointBlockAccess().getRightCurlyBracketKeyword_7()), _function_1);
    final Consumer<Validation> _function_2 = (Validation it) -> {
      document.<Action>format(it.getOnSuccessAction());
    };
    dp.getValidationRules().forEach(_function_2);
    document.<Action>format(dp.getAction());
  }
  
  protected void _format(final Action ac, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getLeftCurlyBracketKeyword_2()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getRightCurlyBracketKeyword_9()), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getLeftSquareBracketKeyword_3_2()), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getLeftSquareBracketKeyword_4_2()), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getLeftSquareBracketKeyword_5_2()), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getLeftSquareBracketKeyword_7_2()), _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getLeftSquareBracketKeyword_8_2()), _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getRightSquareBracketKeyword_3_4()), _function_7);
    final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getRightSquareBracketKeyword_4_4()), _function_8);
    final Procedure1<IHiddenRegionFormatter> _function_9 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getRightSquareBracketKeyword_5_4()), _function_9);
    final Procedure1<IHiddenRegionFormatter> _function_10 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getRightSquareBracketKeyword_6_4()), _function_10);
    final Procedure1<IHiddenRegionFormatter> _function_11 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getRightSquareBracketKeyword_7_4()), _function_11);
    final Procedure1<IHiddenRegionFormatter> _function_12 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getRightSquareBracketKeyword_8_4()), _function_12);
    final Procedure1<IHiddenRegionFormatter> _function_13 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getCommandsKeyword_4_1()), _function_13);
    final Procedure1<IHiddenRegionFormatter> _function_14 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getEventsKeyword_5_1()), _function_14);
    final Procedure1<IHiddenRegionFormatter> _function_15 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getDataKeyword_6_1()), _function_15);
    final Procedure1<IHiddenRegionFormatter> _function_16 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getAlarmsKeyword_3_1()), _function_16);
    final Procedure1<IHiddenRegionFormatter> _function_17 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getStatesKeyword_8_1()), _function_17);
    EList<ActionCommand> _fireCommand = ac.getFireCommand();
    boolean _tripleNotEquals = (_fireCommand != null);
    if (_tripleNotEquals) {
      EList<ActionCommand> _fireCommand_1 = ac.getFireCommand();
      for (final ActionCommand a : _fireCommand_1) {
        document.<ActionCommand>format(a);
      }
    }
    EList<ActionAlarm> _raiseAlarm = ac.getRaiseAlarm();
    boolean _tripleNotEquals_1 = (_raiseAlarm != null);
    if (_tripleNotEquals_1) {
      EList<ActionAlarm> _raiseAlarm_1 = ac.getRaiseAlarm();
      for (final ActionAlarm a_1 : _raiseAlarm_1) {
        document.<ActionAlarm>format(a_1);
      }
    }
    EList<ActionEvent> _publishEvent = ac.getPublishEvent();
    boolean _tripleNotEquals_2 = (_publishEvent != null);
    if (_tripleNotEquals_2) {
      EList<ActionEvent> _publishEvent_1 = ac.getPublishEvent();
      for (final ActionEvent a_2 : _publishEvent_1) {
        document.<ActionEvent>format(a_2);
      }
    }
    EList<ActionDataPoint> _triggerDataPoint = ac.getTriggerDataPoint();
    boolean _tripleNotEquals_3 = (_triggerDataPoint != null);
    if (_tripleNotEquals_3) {
      EList<ActionDataPoint> _triggerDataPoint_1 = ac.getTriggerDataPoint();
      for (final ActionDataPoint a_3 : _triggerDataPoint_1) {
        document.<ActionDataPoint>format(a_3);
      }
    }
    EList<Transition> _transitionStates = ac.getTransitionStates();
    boolean _tripleNotEquals_4 = (_transitionStates != null);
    if (_tripleNotEquals_4) {
      EList<Transition> _transitionStates_1 = ac.getTransitionStates();
      for (final Transition a_4 : _transitionStates_1) {
        document.<Transition>format(a_4);
      }
    }
    final Procedure1<IHiddenRegionFormatter> _function_18 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    final Procedure1<IHiddenRegionFormatter> _function_19 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    final Procedure1<IHiddenRegionFormatter> _function_20 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<ISemanticRegion, ISemanticRegion>interior(
      document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getLeftSquareBracketKeyword_3_2()), _function_18), 
      document.append(this.textRegionExtensions.regionFor(ac).keyword(this.access.getActionAccess().getRightSquareBracketKeyword_3_4()), _function_19), _function_20);
  }
  
  protected void _format(final Transition tr, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(tr).keyword(this.access.getTransitionAccess().getCurrentStateKeyword_1()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(tr).keyword(this.access.getTransitionAccess().getEqualsSignGreaterThanSignKeyword_4()), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(tr).assignment(this.access.getTransitionAccess().getCurrentStateAssignment_2_0_0()), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(tr).keyword(this.access.getTransitionAccess().getCommaKeyword_2_0_1_0()), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(tr).assignment(this.access.getTransitionAccess().getCurrentStateAssignment_2_0_1_1()), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(tr).assignment(this.access.getTransitionAccess().getNextStateAssignment_6()), _function_5);
  }
  
  public void format(final Object alarm, final IFormattableDocument document) {
    if (alarm instanceof XtextResource) {
      _format((XtextResource)alarm, document);
      return;
    } else if (alarm instanceof Alarm) {
      _format((Alarm)alarm, document);
      return;
    } else if (alarm instanceof AlarmBlock) {
      _format((AlarmBlock)alarm, document);
      return;
    } else if (alarm instanceof Command) {
      _format((Command)alarm, document);
      return;
    } else if (alarm instanceof CommandResponseBlock) {
      _format((CommandResponseBlock)alarm, document);
      return;
    } else if (alarm instanceof ControlNode) {
      _format((ControlNode)alarm, document);
      return;
    } else if (alarm instanceof DataPoint) {
      _format((DataPoint)alarm, document);
      return;
    } else if (alarm instanceof DataPointBlock) {
      _format((DataPointBlock)alarm, document);
      return;
    } else if (alarm instanceof Event) {
      _format((Event)alarm, document);
      return;
    } else if (alarm instanceof EventBlock) {
      _format((EventBlock)alarm, document);
      return;
    } else if (alarm instanceof InterfaceDescription) {
      _format((InterfaceDescription)alarm, document);
      return;
    } else if (alarm instanceof Action) {
      _format((Action)alarm, document);
      return;
    } else if (alarm instanceof SubscribableItemList) {
      _format((SubscribableItemList)alarm, document);
      return;
    } else if (alarm instanceof Transition) {
      _format((Transition)alarm, document);
      return;
    } else if (alarm instanceof Validation) {
      _format((Validation)alarm, document);
      return;
    } else if (alarm instanceof OperatingStateUtility) {
      _format((OperatingStateUtility)alarm, document);
      return;
    } else if (alarm instanceof EObject) {
      _format((EObject)alarm, document);
      return;
    } else if (alarm == null) {
      _format((Void)null, document);
      return;
    } else if (alarm != null) {
      _format(alarm, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(alarm, document).toString());
    }
  }
}
