/**
 * generated by Xtext 2.18.0
 */
package com.dml.dsl.serializer;

import com.dml.dsl.serializer.AbstractDmlSyntacticSequencer;

@SuppressWarnings("all")
public class DmlSyntacticSequencer extends AbstractDmlSyntacticSequencer {
}
