/**
 * generated by Xtext 2.15.0
 */
package com.capability.ide;

import com.capability.ide.AbstractCapabilityIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CapabilityIdeModule extends AbstractCapabilityIdeModule {
}
