/**
 * generated by Xtext 2.15.0
 */
package com.capability.ide;

import com.capability.CapabilityRuntimeModule;
import com.capability.CapabilityStandaloneSetup;
import com.capability.ide.CapabilityIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CapabilityIdeSetup extends CapabilityStandaloneSetup {
  @Override
  public Injector createInjector() {
    CapabilityRuntimeModule _capabilityRuntimeModule = new CapabilityRuntimeModule();
    CapabilityIdeModule _capabilityIdeModule = new CapabilityIdeModule();
    return Guice.createInjector(Modules2.mixin(_capabilityRuntimeModule, _capabilityIdeModule));
  }
}
