/*
 * generated by Xtext 2.22.0
 */
package com.mncml.dsl.parser.antlr;

import com.google.inject.Inject;
import com.mncml.dsl.parser.antlr.internal.InternalMncParser;
import com.mncml.dsl.services.MncGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MncParser extends AbstractAntlrParser {

	@Inject
	private MncGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMncParser createParser(XtextTokenStream stream) {
		return new InternalMncParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MncGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MncGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
