/*
 * generated by Xtext 2.18.0
 */
package com.operation.dsl.services;

import com.dml.dsl.services.DmlGrammarAccess;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class OperationGrammarAccess extends AbstractGrammarElementFinder {
	
	public class OperationDescriptionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.operation.dsl.Operation.OperationDescriptions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOperationDescriptionsAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cOperationsAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cOperationsOperationParserRuleCall_1_0_0 = (RuleCall)cOperationsAssignment_1_0.eContents().get(0);
		private final Assignment cOperationsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperationsOperationParserRuleCall_1_1_0 = (RuleCall)cOperationsAssignment_1_1.eContents().get(0);
		
		//OperationDescriptions operationModel::OperationDescriptions:
		//	{operationModel::OperationDescriptions} (operations+=Operation
		//	operations+=Operation*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{operationModel::OperationDescriptions} (operations+=Operation operations+=Operation*)?
		public Group getGroup() { return cGroup; }
		
		//{operationModel::OperationDescriptions}
		public Action getOperationDescriptionsAction_0() { return cOperationDescriptionsAction_0; }
		
		//(operations+=Operation operations+=Operation*)?
		public Group getGroup_1() { return cGroup_1; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_1_0() { return cOperationsAssignment_1_0; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_1_0_0() { return cOperationsOperationParserRuleCall_1_0_0; }
		
		//operations+=Operation*
		public Assignment getOperationsAssignment_1_1() { return cOperationsAssignment_1_1; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_1_1_0() { return cOperationsOperationParserRuleCall_1_1_0; }
	}
	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.operation.dsl.Operation.Operation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOperationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOperationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cInputParametersAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cInputParametersParameterParserRuleCall_4_0_0 = (RuleCall)cInputParametersAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cInputParametersAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cInputParametersParameterParserRuleCall_4_1_1_0 = (RuleCall)cInputParametersAssignment_4_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cExecuteKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cExecutableScriptAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cExecutableScriptEStringParserRuleCall_7_1_0 = (RuleCall)cExecutableScriptAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cReturnKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cOutputParametersAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cOutputParametersParameterParserRuleCall_8_1_0 = (RuleCall)cOutputParametersAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Operation operationModel::Operation:
		//	{operationModel::Operation}
		//	'Operation' name=EString '(' (inputParameters+=Parameter ("," inputParameters+=Parameter)*)? ')'
		//	'{' ('execute' executableScript=EString)? ('return' outputParameters=Parameter)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{operationModel::Operation} 'Operation' name=EString '(' (inputParameters+=Parameter ("," inputParameters+=Parameter)*)?
		//')' '{' ('execute' executableScript=EString)? ('return' outputParameters=Parameter)? '}'
		public Group getGroup() { return cGroup; }
		
		//{operationModel::Operation}
		public Action getOperationAction_0() { return cOperationAction_0; }
		
		//'Operation'
		public Keyword getOperationKeyword_1() { return cOperationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//(inputParameters+=Parameter ("," inputParameters+=Parameter)*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//inputParameters+=Parameter
		public Assignment getInputParametersAssignment_4_0() { return cInputParametersAssignment_4_0; }
		
		//Parameter
		public RuleCall getInputParametersParameterParserRuleCall_4_0_0() { return cInputParametersParameterParserRuleCall_4_0_0; }
		
		//("," inputParameters+=Parameter)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//","
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//inputParameters+=Parameter
		public Assignment getInputParametersAssignment_4_1_1() { return cInputParametersAssignment_4_1_1; }
		
		//Parameter
		public RuleCall getInputParametersParameterParserRuleCall_4_1_1_0() { return cInputParametersParameterParserRuleCall_4_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//('execute' executableScript=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'execute'
		public Keyword getExecuteKeyword_7_0() { return cExecuteKeyword_7_0; }
		
		//executableScript=EString
		public Assignment getExecutableScriptAssignment_7_1() { return cExecutableScriptAssignment_7_1; }
		
		//EString
		public RuleCall getExecutableScriptEStringParserRuleCall_7_1_0() { return cExecutableScriptEStringParserRuleCall_7_1_0; }
		
		//('return' outputParameters=Parameter)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'return'
		public Keyword getReturnKeyword_8_0() { return cReturnKeyword_8_0; }
		
		//outputParameters=Parameter
		public Assignment getOutputParametersAssignment_8_1() { return cOutputParametersAssignment_8_1; }
		
		//Parameter
		public RuleCall getOutputParametersParameterParserRuleCall_8_1_0() { return cOutputParametersParameterParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	
	
	private final OperationDescriptionsElements pOperationDescriptions;
	private final OperationElements pOperation;
	
	private final Grammar grammar;
	
	private final DmlGrammarAccess gaDml;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public OperationGrammarAccess(GrammarProvider grammarProvider,
			DmlGrammarAccess gaDml,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaDml = gaDml;
		this.gaTerminals = gaTerminals;
		this.pOperationDescriptions = new OperationDescriptionsElements();
		this.pOperation = new OperationElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.operation.dsl.Operation".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public DmlGrammarAccess getDmlGrammarAccess() {
		return gaDml;
	}
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//OperationDescriptions operationModel::OperationDescriptions:
	//	{operationModel::OperationDescriptions} (operations+=Operation
	//	operations+=Operation*)?;
	public OperationDescriptionsElements getOperationDescriptionsAccess() {
		return pOperationDescriptions;
	}
	
	public ParserRule getOperationDescriptionsRule() {
		return getOperationDescriptionsAccess().getRule();
	}
	
	//Operation operationModel::Operation:
	//	{operationModel::Operation}
	//	'Operation' name=EString '(' (inputParameters+=Parameter ("," inputParameters+=Parameter)*)? ')'
	//	'{' ('execute' executableScript=EString)? ('return' outputParameters=Parameter)?
	//	'}';
	public OperationElements getOperationAccess() {
		return pOperation;
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}
	
	//DataPackage dataModel::DataPackage:
	//	('Package' name=EString)?
	//	dataModelCollections+=DataModel*;
	public DmlGrammarAccess.DataPackageElements getDataPackageAccess() {
		return gaDml.getDataPackageAccess();
	}
	
	public ParserRule getDataPackageRule() {
		return getDataPackageAccess().getRule();
	}
	
	//DataModel dataModel::DataModel:
	//	'DataModel' name=EString
	//	'{' ('primitives' '{' primitives+=Parameter ("," primitives+=Parameter)* '}')? & ('composites' '{'
	//	composites+=[dataModel::DataModel] ("," composites+=[dataModel::DataModel])* '}')?
	//	'}';
	public DmlGrammarAccess.DataModelElements getDataModelAccess() {
		return gaDml.getDataModelAccess();
	}
	
	public ParserRule getDataModelRule() {
		return getDataModelAccess().getRule();
	}
	
	//Parameter dataModel::Parameter:
	//	SimpleType | AbstractType | ArrayType;
	public DmlGrammarAccess.ParameterElements getParameterAccess() {
		return gaDml.getParameterAccess();
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)*;
	public DmlGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaDml.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//SimpleType dataModel::SimpleType:
	//	{dataModel::SimpleType} type=PrimitiveValueType name=EString ('=' value=PrimitiveValue)?;
	public DmlGrammarAccess.SimpleTypeElements getSimpleTypeAccess() {
		return gaDml.getSimpleTypeAccess();
	}
	
	public ParserRule getSimpleTypeRule() {
		return getSimpleTypeAccess().getRule();
	}
	
	//AbstractType dataModel::AbstractType:
	//	{dataModel::AbstractType} type=[dataModel::DataModel|QualifiedName] name=EString ('=' value=AbstractObjectValue)?;
	public DmlGrammarAccess.AbstractTypeElements getAbstractTypeAccess() {
		return gaDml.getAbstractTypeAccess();
	}
	
	public ParserRule getAbstractTypeRule() {
		return getAbstractTypeAccess().getRule();
	}
	
	//PrimitiveValue dataModel::PrimitiveValue:
	//	{dataModel::IntValue} intValue=EInt | {dataModel::FloatValue} floatValue=EFloat | {dataModel::StringValue}
	//	stringValue=STRING | {dataModel::BoolValue} boolValue=EBoolean | {dataModel::DateValue} dateValue=EDate | ArrayValues
	//	| AbstractObjectValue;
	public DmlGrammarAccess.PrimitiveValueElements getPrimitiveValueAccess() {
		return gaDml.getPrimitiveValueAccess();
	}
	
	public ParserRule getPrimitiveValueRule() {
		return getPrimitiveValueAccess().getRule();
	}
	
	//AbstractObjectValue dataModel::AbstractObjectValue:
	//	{dataModel::AbstractObjectValue} abstractValue=ID;
	public DmlGrammarAccess.AbstractObjectValueElements getAbstractObjectValueAccess() {
		return gaDml.getAbstractObjectValueAccess();
	}
	
	public ParserRule getAbstractObjectValueRule() {
		return getAbstractObjectValueAccess().getRule();
	}
	
	//ArrayValues dataModel::ArrayValues:
	//	{dataModel::ArrayValues}
	//	'[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']';
	public DmlGrammarAccess.ArrayValuesElements getArrayValuesAccess() {
		return gaDml.getArrayValuesAccess();
	}
	
	public ParserRule getArrayValuesRule() {
		return getArrayValuesAccess().getRule();
	}
	
	//ArrayType dataModel::Parameter:
	//	{dataModel::ArrayType} (primitiveType=PrimitiveValueType | dataModelType=[dataModel::DataModel|QualifiedName]) '[' ']'
	//	name=EString ('=' '[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']')?;
	public DmlGrammarAccess.ArrayTypeElements getArrayTypeAccess() {
		return gaDml.getArrayTypeAccess();
	}
	
	public ParserRule getArrayTypeRule() {
		return getArrayTypeAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public DmlGrammarAccess.EStringElements getEStringAccess() {
		return gaDml.getEStringAccess();
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum PrimitiveValueType returns dataModel::PrimitiveValueType:
	//	int | boolean | float | string | object | date;
	public DmlGrammarAccess.PrimitiveValueTypeElements getPrimitiveValueTypeAccess() {
		return gaDml.getPrimitiveValueTypeAccess();
	}
	
	public EnumRule getPrimitiveValueTypeRule() {
		return getPrimitiveValueTypeAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public DmlGrammarAccess.EIntElements getEIntAccess() {
		return gaDml.getEIntAccess();
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'false' | 'true';
	public DmlGrammarAccess.EBooleanElements getEBooleanAccess() {
		return gaDml.getEBooleanAccess();
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EFloat ecore::EFloat:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public DmlGrammarAccess.EFloatElements getEFloatAccess() {
		return gaDml.getEFloatAccess();
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//EDate ecore::EDate:
	//	Day '-' Month '-' Year;
	public DmlGrammarAccess.EDateElements getEDateAccess() {
		return gaDml.getEDateAccess();
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//Day:
	//	INT;
	public DmlGrammarAccess.DayElements getDayAccess() {
		return gaDml.getDayAccess();
	}
	
	public ParserRule getDayRule() {
		return getDayAccess().getRule();
	}
	
	//Month:
	//	INT;
	public DmlGrammarAccess.MonthElements getMonthAccess() {
		return gaDml.getMonthAccess();
	}
	
	public ParserRule getMonthRule() {
		return getMonthAccess().getRule();
	}
	
	//Year:
	//	INT;
	public DmlGrammarAccess.YearElements getYearAccess() {
		return gaDml.getYearAccess();
	}
	
	public ParserRule getYearRule() {
		return getYearAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
