/**
 * generated by Xtext 2.13.0
 */
package com.dml.dsl.formatting2;

import dataModelPackage.DataModel;
import dataModelPackage.DataPackage;
import dataModelPackage.Parameter;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class DmlFormatter extends AbstractFormatter2 {
  protected void _format(final DataPackage dataPackage, @Extension final IFormattableDocument document) {
    EList<DataModel> _dataModelCollections = dataPackage.getDataModelCollections();
    for (final DataModel dataModel : _dataModelCollections) {
      document.<DataModel>format(dataModel);
    }
  }
  
  protected void _format(final DataModel dataModel, @Extension final IFormattableDocument document) {
    EList<Parameter> _primitives = dataModel.getPrimitives();
    for (final Parameter parameter : _primitives) {
      document.<Parameter>format(parameter);
    }
  }
  
  public void format(final Object dataModel, final IFormattableDocument document) {
    if (dataModel instanceof XtextResource) {
      _format((XtextResource)dataModel, document);
      return;
    } else if (dataModel instanceof DataModel) {
      _format((DataModel)dataModel, document);
      return;
    } else if (dataModel instanceof DataPackage) {
      _format((DataPackage)dataModel, document);
      return;
    } else if (dataModel instanceof EObject) {
      _format((EObject)dataModel, document);
      return;
    } else if (dataModel == null) {
      _format((Void)null, document);
      return;
    } else if (dataModel != null) {
      _format(dataModel, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(dataModel, document).toString());
    }
  }
}
