/*
 * generated by Xtext 2.18.0
 */
package com.operation.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.operation.dsl.ide.contentassist.antlr.internal.InternalOperationParser;
import com.operation.dsl.services.OperationGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class OperationParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(OperationGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, OperationGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getParameterAccess().getAlternatives(), "rule__Parameter__Alternatives");
			builder.put(grammarAccess.getPrimitiveValueAccess().getAlternatives(), "rule__PrimitiveValue__Alternatives");
			builder.put(grammarAccess.getArrayTypeAccess().getAlternatives_1(), "rule__ArrayType__Alternatives_1");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
			builder.put(grammarAccess.getPrimitiveValueTypeAccess().getAlternatives(), "rule__PrimitiveValueType__Alternatives");
			builder.put(grammarAccess.getOperationDescriptionsAccess().getGroup(), "rule__OperationDescriptions__Group__0");
			builder.put(grammarAccess.getOperationDescriptionsAccess().getGroup_1(), "rule__OperationDescriptions__Group_1__0");
			builder.put(grammarAccess.getOperationAccess().getGroup(), "rule__Operation__Group__0");
			builder.put(grammarAccess.getOperationAccess().getGroup_4(), "rule__Operation__Group_4__0");
			builder.put(grammarAccess.getOperationAccess().getGroup_4_1(), "rule__Operation__Group_4_1__0");
			builder.put(grammarAccess.getOperationAccess().getGroup_7(), "rule__Operation__Group_7__0");
			builder.put(grammarAccess.getOperationAccess().getGroup_8(), "rule__Operation__Group_8__0");
			builder.put(grammarAccess.getDataPackageAccess().getGroup(), "rule__DataPackage__Group__0");
			builder.put(grammarAccess.getDataPackageAccess().getGroup_0(), "rule__DataPackage__Group_0__0");
			builder.put(grammarAccess.getDataModelAccess().getGroup_0(), "rule__DataModel__Group_0__0");
			builder.put(grammarAccess.getDataModelAccess().getGroup_0_3(), "rule__DataModel__Group_0_3__0");
			builder.put(grammarAccess.getDataModelAccess().getGroup_0_3_3(), "rule__DataModel__Group_0_3_3__0");
			builder.put(grammarAccess.getDataModelAccess().getGroup_1(), "rule__DataModel__Group_1__0");
			builder.put(grammarAccess.getDataModelAccess().getGroup_1_0(), "rule__DataModel__Group_1_0__0");
			builder.put(grammarAccess.getDataModelAccess().getGroup_1_0_3(), "rule__DataModel__Group_1_0_3__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getSimpleTypeAccess().getGroup(), "rule__SimpleType__Group__0");
			builder.put(grammarAccess.getSimpleTypeAccess().getGroup_3(), "rule__SimpleType__Group_3__0");
			builder.put(grammarAccess.getAbstractTypeAccess().getGroup(), "rule__AbstractType__Group__0");
			builder.put(grammarAccess.getAbstractTypeAccess().getGroup_3(), "rule__AbstractType__Group_3__0");
			builder.put(grammarAccess.getPrimitiveValueAccess().getGroup_0(), "rule__PrimitiveValue__Group_0__0");
			builder.put(grammarAccess.getPrimitiveValueAccess().getGroup_1(), "rule__PrimitiveValue__Group_1__0");
			builder.put(grammarAccess.getPrimitiveValueAccess().getGroup_2(), "rule__PrimitiveValue__Group_2__0");
			builder.put(grammarAccess.getPrimitiveValueAccess().getGroup_3(), "rule__PrimitiveValue__Group_3__0");
			builder.put(grammarAccess.getPrimitiveValueAccess().getGroup_4(), "rule__PrimitiveValue__Group_4__0");
			builder.put(grammarAccess.getAbstractObjectValueAccess().getGroup(), "rule__AbstractObjectValue__Group__0");
			builder.put(grammarAccess.getArrayValuesAccess().getGroup(), "rule__ArrayValues__Group__0");
			builder.put(grammarAccess.getArrayValuesAccess().getGroup_2(), "rule__ArrayValues__Group_2__0");
			builder.put(grammarAccess.getArrayValuesAccess().getGroup_2_1(), "rule__ArrayValues__Group_2_1__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup(), "rule__ArrayType__Group__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup_5(), "rule__ArrayType__Group_5__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup_5_2(), "rule__ArrayType__Group_5_2__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup_5_2_1(), "rule__ArrayType__Group_5_2_1__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
			builder.put(grammarAccess.getEDateAccess().getGroup(), "rule__EDate__Group__0");
			builder.put(grammarAccess.getOperationDescriptionsAccess().getOperationsAssignment_1_0(), "rule__OperationDescriptions__OperationsAssignment_1_0");
			builder.put(grammarAccess.getOperationDescriptionsAccess().getOperationsAssignment_1_1(), "rule__OperationDescriptions__OperationsAssignment_1_1");
			builder.put(grammarAccess.getOperationAccess().getNameAssignment_2(), "rule__Operation__NameAssignment_2");
			builder.put(grammarAccess.getOperationAccess().getInputParametersAssignment_4_0(), "rule__Operation__InputParametersAssignment_4_0");
			builder.put(grammarAccess.getOperationAccess().getInputParametersAssignment_4_1_1(), "rule__Operation__InputParametersAssignment_4_1_1");
			builder.put(grammarAccess.getOperationAccess().getExecutableScriptAssignment_7_1(), "rule__Operation__ExecutableScriptAssignment_7_1");
			builder.put(grammarAccess.getOperationAccess().getOutputParametersAssignment_8_1(), "rule__Operation__OutputParametersAssignment_8_1");
			builder.put(grammarAccess.getDataPackageAccess().getNameAssignment_0_1(), "rule__DataPackage__NameAssignment_0_1");
			builder.put(grammarAccess.getDataPackageAccess().getDataModelCollectionsAssignment_1(), "rule__DataPackage__DataModelCollectionsAssignment_1");
			builder.put(grammarAccess.getDataModelAccess().getNameAssignment_0_1(), "rule__DataModel__NameAssignment_0_1");
			builder.put(grammarAccess.getDataModelAccess().getPrimitivesAssignment_0_3_2(), "rule__DataModel__PrimitivesAssignment_0_3_2");
			builder.put(grammarAccess.getDataModelAccess().getPrimitivesAssignment_0_3_3_1(), "rule__DataModel__PrimitivesAssignment_0_3_3_1");
			builder.put(grammarAccess.getDataModelAccess().getCompositesAssignment_1_0_2(), "rule__DataModel__CompositesAssignment_1_0_2");
			builder.put(grammarAccess.getDataModelAccess().getCompositesAssignment_1_0_3_1(), "rule__DataModel__CompositesAssignment_1_0_3_1");
			builder.put(grammarAccess.getSimpleTypeAccess().getTypeAssignment_1(), "rule__SimpleType__TypeAssignment_1");
			builder.put(grammarAccess.getSimpleTypeAccess().getNameAssignment_2(), "rule__SimpleType__NameAssignment_2");
			builder.put(grammarAccess.getSimpleTypeAccess().getValueAssignment_3_1(), "rule__SimpleType__ValueAssignment_3_1");
			builder.put(grammarAccess.getAbstractTypeAccess().getTypeAssignment_1(), "rule__AbstractType__TypeAssignment_1");
			builder.put(grammarAccess.getAbstractTypeAccess().getNameAssignment_2(), "rule__AbstractType__NameAssignment_2");
			builder.put(grammarAccess.getAbstractTypeAccess().getValueAssignment_3_1(), "rule__AbstractType__ValueAssignment_3_1");
			builder.put(grammarAccess.getPrimitiveValueAccess().getIntValueAssignment_0_1(), "rule__PrimitiveValue__IntValueAssignment_0_1");
			builder.put(grammarAccess.getPrimitiveValueAccess().getFloatValueAssignment_1_1(), "rule__PrimitiveValue__FloatValueAssignment_1_1");
			builder.put(grammarAccess.getPrimitiveValueAccess().getStringValueAssignment_2_1(), "rule__PrimitiveValue__StringValueAssignment_2_1");
			builder.put(grammarAccess.getPrimitiveValueAccess().getBoolValueAssignment_3_1(), "rule__PrimitiveValue__BoolValueAssignment_3_1");
			builder.put(grammarAccess.getPrimitiveValueAccess().getDateValueAssignment_4_1(), "rule__PrimitiveValue__DateValueAssignment_4_1");
			builder.put(grammarAccess.getAbstractObjectValueAccess().getAbstractValueAssignment_1(), "rule__AbstractObjectValue__AbstractValueAssignment_1");
			builder.put(grammarAccess.getArrayValuesAccess().getValuesAssignment_2_0(), "rule__ArrayValues__ValuesAssignment_2_0");
			builder.put(grammarAccess.getArrayValuesAccess().getValuesAssignment_2_1_1(), "rule__ArrayValues__ValuesAssignment_2_1_1");
			builder.put(grammarAccess.getArrayTypeAccess().getPrimitiveTypeAssignment_1_0(), "rule__ArrayType__PrimitiveTypeAssignment_1_0");
			builder.put(grammarAccess.getArrayTypeAccess().getDataModelTypeAssignment_1_1(), "rule__ArrayType__DataModelTypeAssignment_1_1");
			builder.put(grammarAccess.getArrayTypeAccess().getNameAssignment_4(), "rule__ArrayType__NameAssignment_4");
			builder.put(grammarAccess.getArrayTypeAccess().getValuesAssignment_5_2_0(), "rule__ArrayType__ValuesAssignment_5_2_0");
			builder.put(grammarAccess.getArrayTypeAccess().getValuesAssignment_5_2_1_1(), "rule__ArrayType__ValuesAssignment_5_2_1_1");
			builder.put(grammarAccess.getDataModelAccess().getUnorderedGroup(), "rule__DataModel__UnorderedGroup");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private OperationGrammarAccess grammarAccess;

	@Override
	protected InternalOperationParser createParser() {
		InternalOperationParser result = new InternalOperationParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public OperationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OperationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
