#!/usr/bin/env python3
from pathlib import Path
import json, zipfile

root = Path(__file__).resolve().parents[1]
projects = []
for mf in root.glob('*/META-INF/MANIFEST.MF'):
    proj = mf.parents[1]
    bundle = None
    for line in mf.read_text(errors='ignore').splitlines():
        if line.startswith('Bundle-SymbolicName:'):
            bundle = line.split(':',1)[1].strip().split(';',1)[0]
            break
    projects.append({"project": proj.name, "bundle": bundle or proj.name})

projects.sort(key=lambda x: x['project'])
outdir = root / 'demo' / 'product'
outdir.mkdir(parents=True, exist_ok=True)
manifest = {
    "name": "KIDE Demonstrator",
    "description": "Packaged demonstrator metadata for the DSL toolchain in this repository.",
    "projects": projects,
}
(outdir / 'manifest.json').write_text(json.dumps(manifest, indent=2))

quickstart = root / 'demo' / 'QUICKSTART.md'
quickstart.write_text("""# KIDE Demonstrator Quickstart\n\n1. Install Eclipse Modeling Tools (2023-12 or newer) with Xtext support.\n2. Import all repository folders as existing projects.\n3. Build workspace once (`Project -> Build All`).\n4. Open `com.mncml/representations.aird` or `com.model.domain.activity.design/representations.aird` in Sirius.\n5. Use DSL editors from:\n   - `com.mncml.dsl` (MNC DSL)\n   - `com.smr.activity.dsl` (Activity DSL)\n\nThis package was generated by `scripts/build_demo_product.py`.\n""")

zip_path = root / 'demo' / 'kide-demonstrator.zip'
with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
    zf.write(quickstart, arcname='QUICKSTART.md')
    zf.write(outdir / 'manifest.json', arcname='product/manifest.json')

print(f"Generated {zip_path}")
print(f"Discovered {len(projects)} Eclipse plug-in projects")
