#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class VerificationFailure(RuntimeError):
    pass


def require(path: str, *needles: str) -> str:
    target = ROOT / path
    if not target.is_file():
        raise VerificationFailure(f"required quality file is missing: {path}")
    text = target.read_text(encoding="utf-8")
    for needle in needles:
        if needle not in text:
            raise VerificationFailure(f"{path} is missing required quality contract: {needle}")
    return text


def main() -> int:
    build = require(
        ".github/workflows/build.yml",
        "python3 scripts/verify_product_journey.py",
        "Smoke-test packaged deterministic synthesis",
        "Smoke-test packaged semantic code generation",
        "Verify generated Web API transport against packaged OpenAPI",
        "npm run test:e2e",
    )
    require(
        "scripts/smoke_codegen.py",
        "validate_manifest(output)",
        "compile_java(output)",
        "artifact.get(\"sha256\") != sha256(target)",
    )
    require(
        "web/src/api.ts",
        "validateGenerationResult",
    )
    require(
        "web/src/generationIntegrity.ts",
        "generated artifact hash mismatch",
        "unsafe generated artifact path",
        "manifest synthesis fingerprint",
    )
    require(
        "web/tests/generationIntegrity.test.ts",
        "rejects corrupted generated bytes",
        "rejects path traversal in generated artifacts",
        "rejects synthesis provenance drift",
    )
    journey = require(
        "web/e2e/golden-journey.spec.ts",
        "golden engineering journey produces integrity-checked generated code",
        "Synthesize",
        "Generate code",
        "generated/Out.java",
    )

    if re.search(r"if:\s*\$\{\{[^\n]*(?:smoke_codegen|test:e2e)", build):
        raise VerificationFailure("mandatory product journey gates must not be conditional")
    if "test.skip" in journey or "test.fixme" in journey:
        raise VerificationFailure("golden engineering journey must not be skipped")

    print("PR84 PRODUCT JOURNEY QUALITY CONTRACT VERIFIED")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except VerificationFailure as exc:
        print(f"ERROR: {exc}")
        raise SystemExit(2)
