/*
 * generated by Xtext 2.22.0
 */
package com.smr.activity.dsl.scoping;

import com.dml.dsl.scoping.DmlScopeProvider;

public abstract class AbstractActivityDiagramScopeProvider extends DmlScopeProvider {
}
