/*
 * generated by Xtext 2.18.0
 */
package com.capability.validation;

import com.dml.dsl.validation.DmlValidator;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public abstract class AbstractCapabilityValidator extends DmlValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://CapabilityDescription/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://mncModel/4.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://dataModelPackage/1.0"));
		return result;
	}
}
