/**
 * generated by Xtext 2.15.0
 */
package com.capability.validation;

import CapabilityDescription.Capability;
import CapabilityDescription.CapabilityDescriptionPackage;
import CapabilityDescription.ControlCapabilities;
import com.capability.validation.AbstractCapabilityValidator;
import java.util.function.Consumer;
import mncModel.Action;
import mncModel.ActionAlarm;
import mncModel.ActionCommand;
import mncModel.ActionDataPoint;
import mncModel.ActionEvent;
import mncModel.Alarm;
import mncModel.Command;
import mncModel.DataPoint;
import mncModel.Event;
import mncModel.InterfaceDescription;
import mncModel.MncModelPackage;
import org.eclipse.emf.common.util.BasicEList;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CapabilityValidator extends AbstractCapabilityValidator {
  public static final String INVALID_CONTROL_CAPABILITIES_COMAND = "invalidControlCapabilitiesCommand";
  
  public static final String INVALID_CONTROL_CAPABILITIES_EVENT = "invalidControlCapabilitiesEvent";
  
  public static final String INVALID_CONTROL_CAPABILITIES_ALARM = "invalidControlCapabilitiesAlarm";
  
  public static final String INVALID_CONTROL_CAPABILITIES_DATAPOINT = "invalidControlCapabilitiesDatapoint";
  
  public static final String INVALID_CAPABILITIES_OUTCOME = "invalidCapabilitiesOutcome";
  
  public static BasicEList<Command> getCommandsFromAllInterfaces(final EList<InterfaceDescription> interfaces) {
    final BasicEList<Command> commands = new BasicEList<Command>();
    final Consumer<InterfaceDescription> _function = (InterfaceDescription ides) -> {
      if (((ides.getCommands() != null) && (ides.getCommands() != null))) {
        commands.addAll(ides.getCommands());
      }
    };
    interfaces.forEach(_function);
    return commands;
  }
  
  public static BasicEList<Event> getEventsFromAllInterfaces(final EList<InterfaceDescription> interfaces) {
    final BasicEList<Event> events = new BasicEList<Event>();
    final Consumer<InterfaceDescription> _function = (InterfaceDescription ides) -> {
      if (((ides.getEvents() != null) && (ides.getEvents() != null))) {
        events.addAll(ides.getEvents());
      }
    };
    interfaces.forEach(_function);
    return events;
  }
  
  public static BasicEList<Alarm> getAlarmsFromAllInterfaces(final EList<InterfaceDescription> interfaces) {
    final BasicEList<Alarm> alarms = new BasicEList<Alarm>();
    final Consumer<InterfaceDescription> _function = (InterfaceDescription ides) -> {
      if (((ides.getAlarms() != null) && (ides.getAlarms() != null))) {
        alarms.addAll(ides.getAlarms());
      }
    };
    interfaces.forEach(_function);
    return alarms;
  }
  
  public static BasicEList<DataPoint> getDataPointsFromAllInterfaces(final EList<InterfaceDescription> interfaces) {
    final BasicEList<DataPoint> dataPoints = new BasicEList<DataPoint>();
    final Consumer<InterfaceDescription> _function = (InterfaceDescription ides) -> {
      if (((ides.getDataPoints() != null) && (ides.getDataPoints() != null))) {
        dataPoints.addAll(ides.getDataPoints());
      }
    };
    interfaces.forEach(_function);
    return dataPoints;
  }
  
  @Check
  public void checkINITItems(final Action action) {
    if ((action != null)) {
      Capability capability = EcoreUtil2.<Capability>getContainerOfType(action, Capability.class);
      if ((capability != null)) {
        EList<InterfaceDescription> interfaceDescriptions = capability.getComponentInterface();
        Action _requiredINITProcess = capability.getRequiredINITProcess();
        boolean _tripleNotEquals = (_requiredINITProcess != null);
        if (_tripleNotEquals) {
          BasicEList<Command> availableCommands = new BasicEList<Command>();
          BasicEList<Event> availableEvents = new BasicEList<Event>();
          BasicEList<Alarm> availableAlarms = new BasicEList<Alarm>();
          BasicEList<DataPoint> availableDataPoints = new BasicEList<DataPoint>();
          EList<ActionCommand> _fireCommand = capability.getRequiredINITProcess().getFireCommand();
          for (final ActionCommand fireComs : _fireCommand) {
            availableCommands.add(fireComs.getCommand());
          }
          EList<ActionEvent> _publishEvent = capability.getRequiredINITProcess().getPublishEvent();
          for (final ActionEvent pubEvent : _publishEvent) {
            availableEvents.add(pubEvent.getEvent());
          }
          EList<ActionAlarm> _raiseAlarm = capability.getRequiredINITProcess().getRaiseAlarm();
          for (final ActionAlarm raiseAlarm : _raiseAlarm) {
            availableAlarms.add(raiseAlarm.getAlarm());
          }
          EList<ActionDataPoint> _triggerDataPoint = capability.getRequiredINITProcess().getTriggerDataPoint();
          for (final ActionDataPoint triggerDataPoint : _triggerDataPoint) {
            availableDataPoints.add(triggerDataPoint.getDataPoint());
          }
          boolean _containsAll = CapabilityValidator.getCommandsFromAllInterfaces(interfaceDescriptions).containsAll(null);
          boolean _not = (!_containsAll);
          if (_not) {
            this.error("Command is not a part of component interface description", 
              MncModelPackage.Literals.ACTION__FIRE_COMMAND, 
              CapabilityValidator.INVALID_CONTROL_CAPABILITIES_COMAND);
          }
          boolean _containsAll_1 = CapabilityValidator.getEventsFromAllInterfaces(interfaceDescriptions).containsAll(availableEvents);
          boolean _not_1 = (!_containsAll_1);
          if (_not_1) {
            this.error("Event is not a part of component interface description", 
              MncModelPackage.Literals.ACTION__PUBLISH_EVENT, 
              CapabilityValidator.INVALID_CONTROL_CAPABILITIES_EVENT);
          }
          boolean _containsAll_2 = CapabilityValidator.getAlarmsFromAllInterfaces(interfaceDescriptions).containsAll(availableAlarms);
          boolean _not_2 = (!_containsAll_2);
          if (_not_2) {
            this.error("Alarm is not a part of component interface description", 
              MncModelPackage.Literals.ACTION__RAISE_ALARM, 
              CapabilityValidator.INVALID_CONTROL_CAPABILITIES_ALARM);
          }
          boolean _containsAll_3 = CapabilityValidator.getDataPointsFromAllInterfaces(interfaceDescriptions).containsAll(availableDataPoints);
          boolean _not_3 = (!_containsAll_3);
          if (_not_3) {
            this.error("Datapoint is not a part of component interface description", 
              MncModelPackage.Literals.ACTION__TRIGGER_DATA_POINT, 
              CapabilityValidator.INVALID_CONTROL_CAPABILITIES_DATAPOINT);
          }
        }
      }
    }
  }
  
  @Check
  public void checkControlCapabilities(final ControlCapabilities controlCapability) {
    Capability capability = EcoreUtil2.<Capability>getContainerOfType(controlCapability, Capability.class);
    if ((capability != null)) {
      EList<InterfaceDescription> interfaceDescriptions = capability.getComponentInterface();
      boolean _containsAll = CapabilityValidator.getCommandsFromAllInterfaces(interfaceDescriptions).containsAll(controlCapability.getCommands());
      boolean _not = (!_containsAll);
      if (_not) {
        this.error("Command is not a part of component interface description", 
          CapabilityDescriptionPackage.Literals.CONTROL_CAPABILITIES__COMMANDS, 
          CapabilityValidator.INVALID_CONTROL_CAPABILITIES_COMAND);
      }
      boolean _containsAll_1 = CapabilityValidator.getEventsFromAllInterfaces(interfaceDescriptions).containsAll(controlCapability.getEvents());
      boolean _not_1 = (!_containsAll_1);
      if (_not_1) {
        this.error("Event is not a part of component interface description", 
          CapabilityDescriptionPackage.Literals.CONTROL_CAPABILITIES__EVENTS, 
          CapabilityValidator.INVALID_CONTROL_CAPABILITIES_EVENT);
      }
      boolean _containsAll_2 = CapabilityValidator.getAlarmsFromAllInterfaces(interfaceDescriptions).containsAll(controlCapability.getAlarms());
      boolean _not_2 = (!_containsAll_2);
      if (_not_2) {
        this.error("Alarm is not a part of component interface description", 
          CapabilityDescriptionPackage.Literals.CONTROL_CAPABILITIES__ALARMS, 
          CapabilityValidator.INVALID_CONTROL_CAPABILITIES_ALARM);
      }
      boolean _containsAll_3 = CapabilityValidator.getDataPointsFromAllInterfaces(interfaceDescriptions).containsAll(controlCapability.getDataPoints());
      boolean _not_3 = (!_containsAll_3);
      if (_not_3) {
        this.error("Datapoint is not a part of component interface description", 
          CapabilityDescriptionPackage.Literals.CONTROL_CAPABILITIES__DATA_POINTS, 
          CapabilityValidator.INVALID_CONTROL_CAPABILITIES_DATAPOINT);
      }
    }
  }
}
