/**
 * generated by Xtext 2.15.0
 */
package com.operation.dsl.ui.quickfix;

import com.dml.dsl.ui.quickfix.DmlQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class OperationQuickfixProvider extends DmlQuickfixProvider {
}
