/*
 * generated by Xtext 2.13.0
 */
package com.smr.activity.dsl.validation

import activityDiagramModel.Activity
import activityDiagramModel.ActivityDiagram
import activityDiagramModel.ActivityDiagramModelPackage
import activityDiagramModel.ConditionalActivity
import activityDiagramModel.Outcome
import dataModelPackage.ArrayType
import dataModelPackage.ArrayValues
import dataModelPackage.BoolValue
import dataModelPackage.FloatValue
import dataModelPackage.IntValue
import dataModelPackage.Parameter
import dataModelPackage.PrimitiveValue
import dataModelPackage.PrimitiveValueType
import dataModelPackage.SimpleType
import dataModelPackage.StringValue
import mncModel.AbstractOutcomeItems
import mncModel.Alarm
import mncModel.Command
import mncModel.ControlNode
import mncModel.DataPoint
import mncModel.Event
import mncModel.Model
import mncModel.Response
import org.eclipse.emf.common.util.BasicEList
import org.eclipse.xtext.EcoreUtil2
import org.eclipse.xtext.validation.Check
import mncModel.AbstractInterfaceItems
import mncModel.CheckParameterCondition
import mncModel.MncModelPackage

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ActivityDiagramValidator extends AbstractActivityDiagramValidator {

	public static val INVALID_OUTCOME = 'invalidOutcome'
	public static val INVALID_RESULT = 'invalidResult'
	public static val INVALID_CONTROL_CAPABILITY = 'invalidControlCapability'
	public static val INVALID_CAPABILITY_OUTCOME = 'invalidCapabilityOutcome'
	public static val TYPE_MISMATCH = 'typeMismatch'
	public static val INPUT_PARAMETER_NOT_FOUND = 'inputParameterNotFound'
	public static val OUTPUT_PARAMETER_NOT_FOUND = 'outputParameterNotFound'

	static def getCandidateParametersForOutcome(Outcome outcome) {
		var activity = EcoreUtil2.getContainerOfType(outcome, Activity)
		var parameterList = new BasicEList<Parameter>
		if (outcome !== null && outcome.capabilityOutcome !== null && outcome.capabilityOutcome !== null) {
			var abstractOutcomeItem = outcome.capabilityOutcome
			if (abstractOutcomeItem instanceof Response) {
				parameterList.addAll(abstractOutcomeItem.parameters)
			}
			if (abstractOutcomeItem instanceof Event) {
				parameterList.addAll(abstractOutcomeItem.parameters)
			}
			if (abstractOutcomeItem instanceof Alarm) {
				parameterList.addAll(abstractOutcomeItem.parameters)
			}
			if (abstractOutcomeItem instanceof DataPoint) {
				parameterList.addAll(abstractOutcomeItem.parameters)
			}
		}
		if (outcome !== null && activity !== null && activity.bindCapability === null &&
			activity.childActivityDiagram !== null) {
			var childActDiagramOutcomeParameters = activity.childActivityDiagram.results
			if (childActDiagramOutcomeParameters !== null) {
				parameterList.addAll(childActDiagramOutcomeParameters)
			}
		}
		if (outcome !== null && activity !== null && activity.bindCapability === null &&
			activity.childActivityDiagram === null && activity.requiresOperation !== null) {
			var requiredOperations = activity.requiresOperation
			if (requiredOperations !== null) {
				for (op : requiredOperations) {
					if (op.outputParameters !== null) {
						parameterList.addAll(op.outputParameters)
					}
				}

			}
		}
		return parameterList
	}

	static def getCandidateAbstractItemsAsControlCapabilities(Activity activity) {
		var interfaceItems = new BasicEList<AbstractInterfaceItems>()
		if (activity.bindCapability !== null) {
			var controlCapabilities = activity.bindCapability.providesControlCapabilities
			if (controlCapabilities !== null) {

				if (controlCapabilities.alarms !== null) {
					interfaceItems.addAll(controlCapabilities.alarms)
				}
				if (controlCapabilities.commands !== null) {
					interfaceItems.addAll(controlCapabilities.commands)
				}
				if (controlCapabilities.events !== null) {
					interfaceItems.addAll(controlCapabilities.events)
				}
				if (controlCapabilities.dataPoints !== null) {
					interfaceItems.addAll(controlCapabilities.dataPoints)
				}
			}

		}
		return interfaceItems
	}

	static def getSuitableResponsesForCommand(ControlNode node, Command command) {
		var responses = new BasicEList<Response>
		var crbs = node.commandResponseBlocks
		if (crbs !== null) {
			for (crb : crbs) {
				if (crb.command.equals(command) && crb.responseBlock !== null) {
					for (resB : crb.responseBlock) {
						responses.add(resB.response)
					}
				}
			}
		}
		return responses
	}

	static def getCandidateCapabilityOutcomes(Outcome outcome) {
		var capabilityOutcomes = new BasicEList<AbstractOutcomeItems>()

		var activity = EcoreUtil2.getContainerOfType(outcome, Activity)
		if (activity !== null && activity.bindCapability !== null &&
			activity.bindCapability.providesOutcomes !== null) {
			var controlCapabilities = activity.bindCapability.providesControlCapabilities
			var providedCapabilityOutcomes = activity.bindCapability.providesOutcomes

			if (controlCapabilities.commands !== null) {
				for (com : controlCapabilities.commands) {
					var mod = EcoreUtil2.getContainerOfType(com, Model)
					if (mod.systems.size > 1) {
						var cn = mod.systems as ControlNode
						var resps = cn.getSuitableResponsesForCommand(com)
						capabilityOutcomes.addAll(resps)
					}
				}
			}

			if (providedCapabilityOutcomes.responses !== null) {
				capabilityOutcomes.addAll(providedCapabilityOutcomes.responses)
			}

			if (controlCapabilities.events !== null) {
				capabilityOutcomes.addAll(controlCapabilities.events)
			}

			if (providedCapabilityOutcomes.events !== null) {
				capabilityOutcomes.addAll(providedCapabilityOutcomes.events)
			}

			if (controlCapabilities.alarms !== null) {
				capabilityOutcomes.addAll(controlCapabilities.alarms)
			}

			if (providedCapabilityOutcomes.alarms !== null) {
				capabilityOutcomes.addAll(providedCapabilityOutcomes.alarms)
			}

			if (controlCapabilities.dataPoints !== null) {
				capabilityOutcomes.addAll(providedCapabilityOutcomes.dataPoints)
			}

			if (providedCapabilityOutcomes.dataPoints !== null) {
				capabilityOutcomes.addAll(controlCapabilities.dataPoints)
			}

		}
		return capabilityOutcomes
	}

	def PrimitiveValueType getTypeOfPrimitiveValue(PrimitiveValue pv) {
		if (pv instanceof IntValue) {
			return PrimitiveValueType.INT
		}
		if (pv instanceof StringValue) {
			return PrimitiveValueType.STRING
		}
		if (pv instanceof FloatValue) {
			return PrimitiveValueType.FLOAT
		}
		if (pv instanceof BoolValue) {
			return PrimitiveValueType.BOOLEAN
		}
		if (pv instanceof ArrayValues) {
			if (pv.values !== null && pv.values.size > 0) {
				var pvFirstValueType = pv.values.get(0)
				return getTypeOfPrimitiveValue(pvFirstValueType)
			} else {
				return PrimitiveValueType.OBJECT
			}

		}
	}

	@Check
	def checkValidOutcome(Outcome outcome) {
		var allowedCapabilityOutcomes = getCandidateCapabilityOutcomes(outcome)
		var allowedOutcomeParameters = getCandidateParametersForOutcome(outcome)
		if (allowedCapabilityOutcomes.size > 0 && !allowedCapabilityOutcomes.contains(outcome.capabilityOutcome)) {
			error("The capability this activity requires never produces this outcome, so the branch can never be taken. Pick one of the outcomes the capability declares.",
				ActivityDiagramModelPackage.Literals.OUTCOME__CAPABILITY_OUTCOME, INVALID_CAPABILITY_OUTCOME)
		}
		var usedOutcomeParams = new BasicEList<Parameter>
		for (map : outcome.outcomeValidation) {
			usedOutcomeParams += map.parameter
		}
		if (!allowedOutcomeParameters.containsAll(usedOutcomeParams)) {
			error("The outcome does not carry this parameter, so there is nothing to read here. Use a parameter the outcome declares.",
				ActivityDiagramModelPackage.Literals.OUTCOME__OUTCOME_VALIDATION, INVALID_OUTCOME)
		}
	}

	@Check
	def checkFinalTrueAndFalseResultsAgainstActivityDiagramProducedResults(ConditionalActivity conAct) {
		if (conAct !== null && conAct.onTrueFinalResult !== null) {
			var actDg = EcoreUtil2.getContainerOfType(conAct, ActivityDiagram)
			if (actDg !== null && actDg.results !== null) {
				if (!actDg.results.contains(conAct.onTrueFinalResult)) {
					error("This result is not declared by the activity diagram, so nothing downstream can use it. Declare it on the diagram, or produce a result that is.",
						ActivityDiagramModelPackage.Literals.CONDITIONAL_ACTIVITY__ON_TRUE_FINAL_RESULT, INVALID_RESULT)
				}
			}
		}
	}

	@Check
	def checkValidControlCapabilitiesForGivenCapability(Activity activity) {
		var interfaceItems = getCandidateAbstractItemsAsControlCapabilities(activity)
		if (activity.useControlCapabilities !== null && !interfaceItems.containsAll(activity.useControlCapabilities)) {
			error("The required capability does not offer this control item. Choose one of the commands, events, alarms or data points the capability provides.",
				ActivityDiagramModelPackage.Literals.ACTIVITY__USE_CONTROL_CAPABILITIES, INVALID_CONTROL_CAPABILITY)
		}
	}

	@Check
	def checkTypesForOutcomeParameterAndValue(CheckParameterCondition checkOutcomeParam) {
		if (checkOutcomeParam.parameter !== null) {
			var outcomeParameter = checkOutcomeParam.parameter
			var max = checkOutcomeParam.checkMaxValue
			var min = checkOutcomeParam.checkMaxValue

			if ((outcomeParameter instanceof SimpleType) && !(max instanceof ArrayValues)) {
				var partype = (outcomeParameter as SimpleType).type
				if (!partype.getName().equals(getTypeOfPrimitiveValue(max).getName())) {
					error("The value does not match the type of the outcome parameter. Give a value of the parameter's declared type.",
						MncModelPackage.Literals.CHECK_PARAMETER_CONDITION__PARAMETER, TYPE_MISMATCH)
				}

			}
			if ((outcomeParameter instanceof SimpleType) && (max instanceof ArrayValues)) {
				error("The parameter expects a single value but a list was given. Remove the list, or declare the parameter as an array.",
					MncModelPackage.Literals.CHECK_PARAMETER_CONDITION__PARAMETER, TYPE_MISMATCH)
			}
			if ((outcomeParameter instanceof ArrayType) && !(max instanceof ArrayValues)) {
				error("The parameter expects a list of values but a single value was given. Wrap the value in a list, or stop declaring the parameter as an array.",
					MncModelPackage.Literals.CHECK_PARAMETER_CONDITION__PARAMETER, TYPE_MISMATCH)
			}

			if (outcomeParameter instanceof ArrayType && max instanceof ArrayValues) {
				var partype = (outcomeParameter as ArrayType).primitiveType

				if (!partype.getName().equals(getTypeOfPrimitiveValue(max).getName())) {
					error("The value does not match the type of the outcome parameter. Give a value of the parameter's declared type.",
						MncModelPackage.Literals.CHECK_PARAMETER_CONDITION__PARAMETER, TYPE_MISMATCH)
				}
			}

		}
	}

	static def findPreviousActivityForAnActivity(Activity activity) {
		var previousActivities = new BasicEList<Activity>()
		var activityDiagram = EcoreUtil2.getContainerOfType(activity, ActivityDiagram)
		var listOfActivities = activityDiagram.activities
		if (listOfActivities !== null) {
			for (act : listOfActivities) {
				if (act.conditionalActivity !== null) {
					for (cond : act.conditionalActivity) {
						if (cond.onTrueNextActivity !== null && cond.onTrueNextActivity.equals(activity)) {
							previousActivities.add(act)
						}
					}
				}
			}
		}
		return previousActivities
	}

	static def getValidInputParametersForAnActivity(Activity activity) {
		var activityDiagram = EcoreUtil2.getContainerOfType(activity, ActivityDiagram)
		var dataObjects = activityDiagram.dataObjects
		var contextDataModels = activityDiagram.contextDataModel
		var previousActivities = activity.findPreviousActivityForAnActivity
		var validInputParameters = new BasicEList<Parameter>()
		if (dataObjects !== null) {
			validInputParameters.addAll(dataObjects)
		}
		if (contextDataModels !== null) {
			validInputParameters.addAll(contextDataModels)
		}
		if (previousActivities !== null) {
			for (prevActs : previousActivities) {
				if (prevActs.conditionalActivity !== null) {
					for (cond : prevActs.conditionalActivity) {
						if (cond.outcome !== null) {
							for (outcome : cond.outcome) {
								for (map : outcome.outcomeValidation) {
									validInputParameters.addAll(map.parameter)
								}
							}

						}
					}
				}
				if (prevActs.childActivityDiagram !== null && prevActs.childActivityDiagram.results !== null) {
					validInputParameters.addAll(prevActs.childActivityDiagram.results)
				}
			}
		}

		return validInputParameters
	}

	static def getValidOutputParametersForAnActivity(Activity activity) {
		var capability = activity.bindCapability
		var operation = activity.requiresOperation
		var childActDiag = activity.childActivityDiagram
		var validOutputParameters = new BasicEList<Parameter>()
		if (capability !== null) {
			var conditionalActivities = activity.conditionalActivity
			if (conditionalActivities !== null) {
				for (cond : conditionalActivities) {
					if (cond.outcome !== null) {
						for(outcome: cond.outcome){
							for (map : outcome.outcomeValidation) {
							validOutputParameters.addAll(map.parameter)
						}
						}
						
					}
				}
			}
		}
		if (operation !== null) {
		}
		if (childActDiag !== null) {
		}
		return validOutputParameters
	}

	@Check
	def checkInputParametersForActivity(Activity activity) {
		var validInputParameters = getValidInputParametersForAnActivity(activity)
		if (activity.inputParameters !== null && !validInputParameters.containsAll(activity.inputParameters)) {
			error(
				"Nothing supplies this input: no earlier activity produces it and the activity diagram does not provide it. Produce it in a preceding activity, or declare it as an input of the diagram.",
				ActivityDiagramModelPackage.Literals.ACTIVITY__INPUT_PARAMETERS, INPUT_PARAMETER_NOT_FOUND)
		}
	}

}
