/**
 * generated by Xtext 2.15.0
 */
package com.capability;

import com.capability.CapabilityStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CapabilityStandaloneSetup extends CapabilityStandaloneSetupGenerated {
  public static void doSetup() {
    new CapabilityStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
