/**
 * generated by Xtext 2.15.0
 */
package com.mncml.dsl.ui;

import com.mncml.dsl.ui.AbstractMncUiModule;
import com.mncml.dsl.ui.hyperlink.MncHyperlinkHelper;
import com.mncml.dsl.ui.syntaxcoloring.MncHighlightingConfiguration;
import com.mncml.dsl.ui.syntaxcoloring.MncSemanticHighlightingCalculator;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.resource.IResourceSetProvider;
import org.eclipse.xtext.ui.resource.XtextLiveScopeResourceSetProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@SuppressWarnings("all")
public class MncUiModule extends AbstractMncUiModule {
  public MncUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
  
  public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
    return MncSemanticHighlightingCalculator.class;
  }
  
  public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
    return MncHighlightingConfiguration.class;
  }
  
  public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
    return MncHyperlinkHelper.class;
  }
  
  @Override
  public Class<? extends IResourceSetProvider> bindIResourceSetProvider() {
    return XtextLiveScopeResourceSetProvider.class;
  }
}
