/**
 * generated by Xtext 2.15.0
 */
package com.mncml.dsl;

import com.mncml.dsl.MncStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MncStandaloneSetup extends MncStandaloneSetupGenerated {
  public static void doSetup() {
    new MncStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
