/**
 * generated by Xtext 2.15.0
 */
package com.operation.dsl;

import com.operation.dsl.AbstractOperationRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class OperationRuntimeModule extends AbstractOperationRuntimeModule {
}
