/*
 * generated by Xtext 2.13.0
 */
package com.dml.dsl

import com.dml.dsl.scoping.DmlScopeProvider
import com.dml.dsl.serializer.DmlCustomSerializer
import com.google.inject.Binder
import org.eclipse.xtext.linking.LinkingScopeProviderBinding
import org.eclipse.xtext.scoping.IScopeProvider
import org.eclipse.xtext.serializer.impl.Serializer
import org.eclipse.xtext.serializer.ISerializer

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DmlRuntimeModule extends AbstractDmlRuntimeModule {
	override Class<? extends IScopeProvider> bindIScopeProvider() {
	return DmlScopeProvider;
	}
	
	override void configureLinkingIScopeProvider(Binder binder) {
		binder.bind(IScopeProvider).annotatedWith(LinkingScopeProviderBinding).
		to(DmlScopeProvider);
	}
	
	override Class<? extends ISerializer> bindISerializer() {
		return DmlCustomSerializer;
	}

}
    