/*
 * generated by Xtext 2.18.0
 */
package com.dml.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DmlGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DataPackageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.DataPackage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cPackageKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Assignment cDataModelCollectionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDataModelCollectionsDataModelParserRuleCall_1_0 = (RuleCall)cDataModelCollectionsAssignment_1.eContents().get(0);
		
		//DataPackage dataModel::DataPackage:
		//	('Package' name=EString)?
		//	dataModelCollections+=DataModel*;
		@Override public ParserRule getRule() { return rule; }
		
		//('Package' name=EString)? dataModelCollections+=DataModel*
		public Group getGroup() { return cGroup; }
		
		//('Package' name=EString)?
		public Group getGroup_0() { return cGroup_0; }
		
		//'Package'
		public Keyword getPackageKeyword_0_0() { return cPackageKeyword_0_0; }
		
		//name=EString
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_1_0() { return cNameEStringParserRuleCall_0_1_0; }
		
		//dataModelCollections+=DataModel*
		public Assignment getDataModelCollectionsAssignment_1() { return cDataModelCollectionsAssignment_1; }
		
		//DataModel
		public RuleCall getDataModelCollectionsDataModelParserRuleCall_1_0() { return cDataModelCollectionsDataModelParserRuleCall_1_0; }
	}
	public class DataModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.DataModel");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cUnorderedGroup.eContents().get(0);
		private final Keyword cDataModelKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_0_3 = (Group)cGroup_0.eContents().get(3);
		private final Keyword cPrimitivesKeyword_0_3_0 = (Keyword)cGroup_0_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_0_3_1 = (Keyword)cGroup_0_3.eContents().get(1);
		private final Assignment cPrimitivesAssignment_0_3_2 = (Assignment)cGroup_0_3.eContents().get(2);
		private final RuleCall cPrimitivesParameterParserRuleCall_0_3_2_0 = (RuleCall)cPrimitivesAssignment_0_3_2.eContents().get(0);
		private final Group cGroup_0_3_3 = (Group)cGroup_0_3.eContents().get(3);
		private final Keyword cCommaKeyword_0_3_3_0 = (Keyword)cGroup_0_3_3.eContents().get(0);
		private final Assignment cPrimitivesAssignment_0_3_3_1 = (Assignment)cGroup_0_3_3.eContents().get(1);
		private final RuleCall cPrimitivesParameterParserRuleCall_0_3_3_1_0 = (RuleCall)cPrimitivesAssignment_0_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_0_3_4 = (Keyword)cGroup_0_3.eContents().get(4);
		private final Group cGroup_1 = (Group)cUnorderedGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cGroup_1.eContents().get(0);
		private final Keyword cCompositesKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Assignment cCompositesAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final CrossReference cCompositesDataModelCrossReference_1_0_2_0 = (CrossReference)cCompositesAssignment_1_0_2.eContents().get(0);
		private final RuleCall cCompositesDataModelIDTerminalRuleCall_1_0_2_0_1 = (RuleCall)cCompositesDataModelCrossReference_1_0_2_0.eContents().get(1);
		private final Group cGroup_1_0_3 = (Group)cGroup_1_0.eContents().get(3);
		private final Keyword cCommaKeyword_1_0_3_0 = (Keyword)cGroup_1_0_3.eContents().get(0);
		private final Assignment cCompositesAssignment_1_0_3_1 = (Assignment)cGroup_1_0_3.eContents().get(1);
		private final CrossReference cCompositesDataModelCrossReference_1_0_3_1_0 = (CrossReference)cCompositesAssignment_1_0_3_1.eContents().get(0);
		private final RuleCall cCompositesDataModelIDTerminalRuleCall_1_0_3_1_0_1 = (RuleCall)cCompositesDataModelCrossReference_1_0_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_1_0_4 = (Keyword)cGroup_1_0.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//DataModel dataModel::DataModel:
		//	'DataModel' name=EString
		//	'{' ('primitives' '{' primitives+=Parameter ("," primitives+=Parameter)* '}')? & ('composites' '{'
		//	composites+=[dataModel::DataModel] ("," composites+=[dataModel::DataModel])* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'DataModel' name=EString '{' ('primitives' '{' primitives+=Parameter ("," primitives+=Parameter)* '}')? & ('composites'
		//'{' composites+=[dataModel::DataModel] ("," composites+=[dataModel::DataModel])* '}')? '}'
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }
		
		//'DataModel' name=EString '{' ('primitives' '{' primitives+=Parameter ("," primitives+=Parameter)* '}')?
		public Group getGroup_0() { return cGroup_0; }
		
		//'DataModel'
		public Keyword getDataModelKeyword_0_0() { return cDataModelKeyword_0_0; }
		
		//name=EString
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_1_0() { return cNameEStringParserRuleCall_0_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0_2() { return cLeftCurlyBracketKeyword_0_2; }
		
		//('primitives' '{' primitives+=Parameter ("," primitives+=Parameter)* '}')?
		public Group getGroup_0_3() { return cGroup_0_3; }
		
		//'primitives'
		public Keyword getPrimitivesKeyword_0_3_0() { return cPrimitivesKeyword_0_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0_3_1() { return cLeftCurlyBracketKeyword_0_3_1; }
		
		//primitives+=Parameter
		public Assignment getPrimitivesAssignment_0_3_2() { return cPrimitivesAssignment_0_3_2; }
		
		//Parameter
		public RuleCall getPrimitivesParameterParserRuleCall_0_3_2_0() { return cPrimitivesParameterParserRuleCall_0_3_2_0; }
		
		//("," primitives+=Parameter)*
		public Group getGroup_0_3_3() { return cGroup_0_3_3; }
		
		//","
		public Keyword getCommaKeyword_0_3_3_0() { return cCommaKeyword_0_3_3_0; }
		
		//primitives+=Parameter
		public Assignment getPrimitivesAssignment_0_3_3_1() { return cPrimitivesAssignment_0_3_3_1; }
		
		//Parameter
		public RuleCall getPrimitivesParameterParserRuleCall_0_3_3_1_0() { return cPrimitivesParameterParserRuleCall_0_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_0_3_4() { return cRightCurlyBracketKeyword_0_3_4; }
		
		//('composites' '{' composites+=[dataModel::DataModel] ("," composites+=[dataModel::DataModel])* '}')? '}'
		public Group getGroup_1() { return cGroup_1; }
		
		//('composites' '{' composites+=[dataModel::DataModel] ("," composites+=[dataModel::DataModel])* '}')?
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'composites'
		public Keyword getCompositesKeyword_1_0_0() { return cCompositesKeyword_1_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1_0_1() { return cLeftCurlyBracketKeyword_1_0_1; }
		
		//composites+=[dataModel::DataModel]
		public Assignment getCompositesAssignment_1_0_2() { return cCompositesAssignment_1_0_2; }
		
		//[dataModel::DataModel]
		public CrossReference getCompositesDataModelCrossReference_1_0_2_0() { return cCompositesDataModelCrossReference_1_0_2_0; }
		
		//ID
		public RuleCall getCompositesDataModelIDTerminalRuleCall_1_0_2_0_1() { return cCompositesDataModelIDTerminalRuleCall_1_0_2_0_1; }
		
		//("," composites+=[dataModel::DataModel])*
		public Group getGroup_1_0_3() { return cGroup_1_0_3; }
		
		//","
		public Keyword getCommaKeyword_1_0_3_0() { return cCommaKeyword_1_0_3_0; }
		
		//composites+=[dataModel::DataModel]
		public Assignment getCompositesAssignment_1_0_3_1() { return cCompositesAssignment_1_0_3_1; }
		
		//[dataModel::DataModel]
		public CrossReference getCompositesDataModelCrossReference_1_0_3_1_0() { return cCompositesDataModelCrossReference_1_0_3_1_0; }
		
		//ID
		public RuleCall getCompositesDataModelIDTerminalRuleCall_1_0_3_1_0_1() { return cCompositesDataModelIDTerminalRuleCall_1_0_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_0_4() { return cRightCurlyBracketKeyword_1_0_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_1() { return cRightCurlyBracketKeyword_1_1; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.Parameter");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSimpleTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAbstractTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cArrayTypeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Parameter dataModel::Parameter:
		//	SimpleType | AbstractType | ArrayType;
		@Override public ParserRule getRule() { return rule; }
		
		//SimpleType | AbstractType | ArrayType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SimpleType
		public RuleCall getSimpleTypeParserRuleCall_0() { return cSimpleTypeParserRuleCall_0; }
		
		//AbstractType
		public RuleCall getAbstractTypeParserRuleCall_1() { return cAbstractTypeParserRuleCall_1; }
		
		//ArrayType
		public RuleCall getArrayTypeParserRuleCall_2() { return cArrayTypeParserRuleCall_2; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class SimpleTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.SimpleType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSimpleTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypePrimitiveValueTypeEnumRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValuePrimitiveValueParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		
		//SimpleType dataModel::SimpleType:
		//	{dataModel::SimpleType} type=PrimitiveValueType name=EString ('=' value=PrimitiveValue)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{dataModel::SimpleType} type=PrimitiveValueType name=EString ('=' value=PrimitiveValue)?
		public Group getGroup() { return cGroup; }
		
		//{dataModel::SimpleType}
		public Action getSimpleTypeAction_0() { return cSimpleTypeAction_0; }
		
		//type=PrimitiveValueType
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//PrimitiveValueType
		public RuleCall getTypePrimitiveValueTypeEnumRuleCall_1_0() { return cTypePrimitiveValueTypeEnumRuleCall_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//('=' value=PrimitiveValue)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_3_0() { return cEqualsSignKeyword_3_0; }
		
		//value=PrimitiveValue
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//PrimitiveValue
		public RuleCall getValuePrimitiveValueParserRuleCall_3_1_0() { return cValuePrimitiveValueParserRuleCall_3_1_0; }
	}
	public class AbstractTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.AbstractType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAbstractTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTypeDataModelCrossReference_1_0 = (CrossReference)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cTypeDataModelQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cTypeDataModelCrossReference_1_0.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueAbstractObjectValueParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		
		//AbstractType dataModel::AbstractType:
		//	{dataModel::AbstractType} type=[dataModel::DataModel|QualifiedName] name=EString ('=' value=AbstractObjectValue)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{dataModel::AbstractType} type=[dataModel::DataModel|QualifiedName] name=EString ('=' value=AbstractObjectValue)?
		public Group getGroup() { return cGroup; }
		
		//{dataModel::AbstractType}
		public Action getAbstractTypeAction_0() { return cAbstractTypeAction_0; }
		
		//type=[dataModel::DataModel|QualifiedName]
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//[dataModel::DataModel|QualifiedName]
		public CrossReference getTypeDataModelCrossReference_1_0() { return cTypeDataModelCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getTypeDataModelQualifiedNameParserRuleCall_1_0_1() { return cTypeDataModelQualifiedNameParserRuleCall_1_0_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//('=' value=AbstractObjectValue)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_3_0() { return cEqualsSignKeyword_3_0; }
		
		//value=AbstractObjectValue
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//AbstractObjectValue
		public RuleCall getValueAbstractObjectValueParserRuleCall_3_1_0() { return cValueAbstractObjectValueParserRuleCall_3_1_0; }
	}
	public class PrimitiveValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.PrimitiveValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cIntValueAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cIntValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cIntValueEIntParserRuleCall_0_1_0 = (RuleCall)cIntValueAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cFloatValueAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cFloatValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cFloatValueEFloatParserRuleCall_1_1_0 = (RuleCall)cFloatValueAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cStringValueAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Assignment cStringValueAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cStringValueSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cStringValueAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cBoolValueAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Assignment cBoolValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cBoolValueEBooleanParserRuleCall_3_1_0 = (RuleCall)cBoolValueAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cDateValueAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Assignment cDateValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDateValueEDateParserRuleCall_4_1_0 = (RuleCall)cDateValueAssignment_4_1.eContents().get(0);
		private final RuleCall cArrayValuesParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cAbstractObjectValueParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//PrimitiveValue dataModel::PrimitiveValue:
		//	{dataModel::IntValue} intValue=EInt | {dataModel::FloatValue} floatValue=EFloat | {dataModel::StringValue}
		//	stringValue=STRING | {dataModel::BoolValue} boolValue=EBoolean | {dataModel::DateValue} dateValue=EDate | ArrayValues
		//	| AbstractObjectValue;
		@Override public ParserRule getRule() { return rule; }
		
		//{dataModel::IntValue} intValue=EInt | {dataModel::FloatValue} floatValue=EFloat | {dataModel::StringValue}
		//stringValue=STRING | {dataModel::BoolValue} boolValue=EBoolean | {dataModel::DateValue} dateValue=EDate | ArrayValues
		//| AbstractObjectValue
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{dataModel::IntValue} intValue=EInt
		public Group getGroup_0() { return cGroup_0; }
		
		//{dataModel::IntValue}
		public Action getIntValueAction_0_0() { return cIntValueAction_0_0; }
		
		//intValue=EInt
		public Assignment getIntValueAssignment_0_1() { return cIntValueAssignment_0_1; }
		
		//EInt
		public RuleCall getIntValueEIntParserRuleCall_0_1_0() { return cIntValueEIntParserRuleCall_0_1_0; }
		
		//{dataModel::FloatValue} floatValue=EFloat
		public Group getGroup_1() { return cGroup_1; }
		
		//{dataModel::FloatValue}
		public Action getFloatValueAction_1_0() { return cFloatValueAction_1_0; }
		
		//floatValue=EFloat
		public Assignment getFloatValueAssignment_1_1() { return cFloatValueAssignment_1_1; }
		
		//EFloat
		public RuleCall getFloatValueEFloatParserRuleCall_1_1_0() { return cFloatValueEFloatParserRuleCall_1_1_0; }
		
		//{dataModel::StringValue} stringValue=STRING
		public Group getGroup_2() { return cGroup_2; }
		
		//{dataModel::StringValue}
		public Action getStringValueAction_2_0() { return cStringValueAction_2_0; }
		
		//stringValue=STRING
		public Assignment getStringValueAssignment_2_1() { return cStringValueAssignment_2_1; }
		
		//STRING
		public RuleCall getStringValueSTRINGTerminalRuleCall_2_1_0() { return cStringValueSTRINGTerminalRuleCall_2_1_0; }
		
		//{dataModel::BoolValue} boolValue=EBoolean
		public Group getGroup_3() { return cGroup_3; }
		
		//{dataModel::BoolValue}
		public Action getBoolValueAction_3_0() { return cBoolValueAction_3_0; }
		
		//boolValue=EBoolean
		public Assignment getBoolValueAssignment_3_1() { return cBoolValueAssignment_3_1; }
		
		//EBoolean
		public RuleCall getBoolValueEBooleanParserRuleCall_3_1_0() { return cBoolValueEBooleanParserRuleCall_3_1_0; }
		
		//{dataModel::DateValue} dateValue=EDate
		public Group getGroup_4() { return cGroup_4; }
		
		//{dataModel::DateValue}
		public Action getDateValueAction_4_0() { return cDateValueAction_4_0; }
		
		//dateValue=EDate
		public Assignment getDateValueAssignment_4_1() { return cDateValueAssignment_4_1; }
		
		//EDate
		public RuleCall getDateValueEDateParserRuleCall_4_1_0() { return cDateValueEDateParserRuleCall_4_1_0; }
		
		//ArrayValues
		public RuleCall getArrayValuesParserRuleCall_5() { return cArrayValuesParserRuleCall_5; }
		
		//AbstractObjectValue
		public RuleCall getAbstractObjectValueParserRuleCall_6() { return cAbstractObjectValueParserRuleCall_6; }
	}
	public class AbstractObjectValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.AbstractObjectValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAbstractObjectValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAbstractValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAbstractValueIDTerminalRuleCall_1_0 = (RuleCall)cAbstractValueAssignment_1.eContents().get(0);
		
		//AbstractObjectValue dataModel::AbstractObjectValue:
		//	{dataModel::AbstractObjectValue} abstractValue=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//{dataModel::AbstractObjectValue} abstractValue=ID
		public Group getGroup() { return cGroup; }
		
		//{dataModel::AbstractObjectValue}
		public Action getAbstractObjectValueAction_0() { return cAbstractObjectValueAction_0; }
		
		//abstractValue=ID
		public Assignment getAbstractValueAssignment_1() { return cAbstractValueAssignment_1; }
		
		//ID
		public RuleCall getAbstractValueIDTerminalRuleCall_1_0() { return cAbstractValueIDTerminalRuleCall_1_0; }
	}
	public class ArrayValuesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.ArrayValues");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cArrayValuesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cValuesAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cValuesPrimitiveValueParserRuleCall_2_0_0 = (RuleCall)cValuesAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cValuesAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cValuesPrimitiveValueParserRuleCall_2_1_1_0 = (RuleCall)cValuesAssignment_2_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ArrayValues dataModel::ArrayValues:
		//	{dataModel::ArrayValues}
		//	'[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']';
		@Override public ParserRule getRule() { return rule; }
		
		//{dataModel::ArrayValues} '[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']'
		public Group getGroup() { return cGroup; }
		
		//{dataModel::ArrayValues}
		public Action getArrayValuesAction_0() { return cArrayValuesAction_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//(values+=PrimitiveValue (',' values+=PrimitiveValue)*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//values+=PrimitiveValue
		public Assignment getValuesAssignment_2_0() { return cValuesAssignment_2_0; }
		
		//PrimitiveValue
		public RuleCall getValuesPrimitiveValueParserRuleCall_2_0_0() { return cValuesPrimitiveValueParserRuleCall_2_0_0; }
		
		//(',' values+=PrimitiveValue)*
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//','
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }
		
		//values+=PrimitiveValue
		public Assignment getValuesAssignment_2_1_1() { return cValuesAssignment_2_1_1; }
		
		//PrimitiveValue
		public RuleCall getValuesPrimitiveValueParserRuleCall_2_1_1_0() { return cValuesPrimitiveValueParserRuleCall_2_1_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}
	public class ArrayTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.ArrayType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cArrayTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cPrimitiveTypeAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cPrimitiveTypePrimitiveValueTypeEnumRuleCall_1_0_0 = (RuleCall)cPrimitiveTypeAssignment_1_0.eContents().get(0);
		private final Assignment cDataModelTypeAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final CrossReference cDataModelTypeDataModelCrossReference_1_1_0 = (CrossReference)cDataModelTypeAssignment_1_1.eContents().get(0);
		private final RuleCall cDataModelTypeDataModelQualifiedNameParserRuleCall_1_1_0_1 = (RuleCall)cDataModelTypeDataModelCrossReference_1_1_0.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Assignment cValuesAssignment_5_2_0 = (Assignment)cGroup_5_2.eContents().get(0);
		private final RuleCall cValuesPrimitiveValueParserRuleCall_5_2_0_0 = (RuleCall)cValuesAssignment_5_2_0.eContents().get(0);
		private final Group cGroup_5_2_1 = (Group)cGroup_5_2.eContents().get(1);
		private final Keyword cCommaKeyword_5_2_1_0 = (Keyword)cGroup_5_2_1.eContents().get(0);
		private final Assignment cValuesAssignment_5_2_1_1 = (Assignment)cGroup_5_2_1.eContents().get(1);
		private final RuleCall cValuesPrimitiveValueParserRuleCall_5_2_1_1_0 = (RuleCall)cValuesAssignment_5_2_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		
		//ArrayType dataModel::Parameter:
		//	{dataModel::ArrayType} (primitiveType=PrimitiveValueType | dataModelType=[dataModel::DataModel|QualifiedName]) '['
		//	']' name=EString ('=' '[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{dataModel::ArrayType} (primitiveType=PrimitiveValueType | dataModelType=[dataModel::DataModel|QualifiedName]) '[' ']'
		//name=EString ('=' '[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']')?
		public Group getGroup() { return cGroup; }
		
		//{dataModel::ArrayType}
		public Action getArrayTypeAction_0() { return cArrayTypeAction_0; }
		
		//primitiveType=PrimitiveValueType | dataModelType=[dataModel::DataModel|QualifiedName]
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//primitiveType=PrimitiveValueType
		public Assignment getPrimitiveTypeAssignment_1_0() { return cPrimitiveTypeAssignment_1_0; }
		
		//PrimitiveValueType
		public RuleCall getPrimitiveTypePrimitiveValueTypeEnumRuleCall_1_0_0() { return cPrimitiveTypePrimitiveValueTypeEnumRuleCall_1_0_0; }
		
		//dataModelType=[dataModel::DataModel|QualifiedName]
		public Assignment getDataModelTypeAssignment_1_1() { return cDataModelTypeAssignment_1_1; }
		
		//[dataModel::DataModel|QualifiedName]
		public CrossReference getDataModelTypeDataModelCrossReference_1_1_0() { return cDataModelTypeDataModelCrossReference_1_1_0; }
		
		//QualifiedName
		public RuleCall getDataModelTypeDataModelQualifiedNameParserRuleCall_1_1_0_1() { return cDataModelTypeDataModelQualifiedNameParserRuleCall_1_1_0_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2() { return cLeftSquareBracketKeyword_2; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
		
		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
		
		//('=' '[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_5_0() { return cEqualsSignKeyword_5_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5_1() { return cLeftSquareBracketKeyword_5_1; }
		
		//(values+=PrimitiveValue (',' values+=PrimitiveValue)*)?
		public Group getGroup_5_2() { return cGroup_5_2; }
		
		//values+=PrimitiveValue
		public Assignment getValuesAssignment_5_2_0() { return cValuesAssignment_5_2_0; }
		
		//PrimitiveValue
		public RuleCall getValuesPrimitiveValueParserRuleCall_5_2_0_0() { return cValuesPrimitiveValueParserRuleCall_5_2_0_0; }
		
		//(',' values+=PrimitiveValue)*
		public Group getGroup_5_2_1() { return cGroup_5_2_1; }
		
		//','
		public Keyword getCommaKeyword_5_2_1_0() { return cCommaKeyword_5_2_1_0; }
		
		//values+=PrimitiveValue
		public Assignment getValuesAssignment_5_2_1_1() { return cValuesAssignment_5_2_1_1; }
		
		//PrimitiveValue
		public RuleCall getValuesPrimitiveValueParserRuleCall_5_2_1_1_0() { return cValuesPrimitiveValueParserRuleCall_5_2_1_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5_3() { return cRightSquareBracketKeyword_5_3; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cFalseKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cTrueKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'false' | 'true';
		@Override public ParserRule getRule() { return rule; }
		
		//'false' | 'true'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'false'
		public Keyword getFalseKeyword_0() { return cFalseKeyword_0; }
		
		//'true'
		public Keyword getTrueKeyword_1() { return cTrueKeyword_1; }
	}
	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat ecore::EFloat:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'E' | 'e'
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.EDate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDayParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cMonthParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cHyphenMinusKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cYearParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//EDate ecore::EDate:
		//	Day '-' Month '-' Year;
		@Override public ParserRule getRule() { return rule; }
		
		//Day '-' Month '-' Year
		public Group getGroup() { return cGroup; }
		
		//Day
		public RuleCall getDayParserRuleCall_0() { return cDayParserRuleCall_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//Month
		public RuleCall getMonthParserRuleCall_2() { return cMonthParserRuleCall_2; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_3() { return cHyphenMinusKeyword_3; }
		
		//Year
		public RuleCall getYearParserRuleCall_4() { return cYearParserRuleCall_4; }
	}
	public class DayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.Day");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Day:
		//	INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	public class MonthElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.Month");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Month:
		//	INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	public class YearElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.Year");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Year:
		//	INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	
	public class PrimitiveValueTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.dml.dsl.Dml.PrimitiveValueType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cIntEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cIntIntKeyword_0_0 = (Keyword)cIntEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBooleanBooleanKeyword_1_0 = (Keyword)cBooleanEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cFloatEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cFloatFloatKeyword_2_0 = (Keyword)cFloatEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cStringStringKeyword_3_0 = (Keyword)cStringEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cObjectEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cObjectObjectKeyword_4_0 = (Keyword)cObjectEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cDateEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cDateDateKeyword_5_0 = (Keyword)cDateEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum PrimitiveValueType returns dataModel::PrimitiveValueType:
		//	int | boolean | float | string | object | date;
		public EnumRule getRule() { return rule; }
		
		//int | boolean | float | string | object | date
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//int
		public EnumLiteralDeclaration getIntEnumLiteralDeclaration_0() { return cIntEnumLiteralDeclaration_0; }
		
		//'int'
		public Keyword getIntIntKeyword_0_0() { return cIntIntKeyword_0_0; }
		
		//boolean
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_1() { return cBooleanEnumLiteralDeclaration_1; }
		
		//'boolean'
		public Keyword getBooleanBooleanKeyword_1_0() { return cBooleanBooleanKeyword_1_0; }
		
		//float
		public EnumLiteralDeclaration getFloatEnumLiteralDeclaration_2() { return cFloatEnumLiteralDeclaration_2; }
		
		//'float'
		public Keyword getFloatFloatKeyword_2_0() { return cFloatFloatKeyword_2_0; }
		
		//string
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_3() { return cStringEnumLiteralDeclaration_3; }
		
		//'string'
		public Keyword getStringStringKeyword_3_0() { return cStringStringKeyword_3_0; }
		
		//object
		public EnumLiteralDeclaration getObjectEnumLiteralDeclaration_4() { return cObjectEnumLiteralDeclaration_4; }
		
		//'object'
		public Keyword getObjectObjectKeyword_4_0() { return cObjectObjectKeyword_4_0; }
		
		//date
		public EnumLiteralDeclaration getDateEnumLiteralDeclaration_5() { return cDateEnumLiteralDeclaration_5; }
		
		//'date'
		public Keyword getDateDateKeyword_5_0() { return cDateDateKeyword_5_0; }
	}
	
	private final DataPackageElements pDataPackage;
	private final DataModelElements pDataModel;
	private final ParameterElements pParameter;
	private final QualifiedNameElements pQualifiedName;
	private final SimpleTypeElements pSimpleType;
	private final AbstractTypeElements pAbstractType;
	private final PrimitiveValueElements pPrimitiveValue;
	private final AbstractObjectValueElements pAbstractObjectValue;
	private final ArrayValuesElements pArrayValues;
	private final ArrayTypeElements pArrayType;
	private final EStringElements pEString;
	private final PrimitiveValueTypeElements ePrimitiveValueType;
	private final EIntElements pEInt;
	private final EBooleanElements pEBoolean;
	private final EFloatElements pEFloat;
	private final EDateElements pEDate;
	private final DayElements pDay;
	private final MonthElements pMonth;
	private final YearElements pYear;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DmlGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDataPackage = new DataPackageElements();
		this.pDataModel = new DataModelElements();
		this.pParameter = new ParameterElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pSimpleType = new SimpleTypeElements();
		this.pAbstractType = new AbstractTypeElements();
		this.pPrimitiveValue = new PrimitiveValueElements();
		this.pAbstractObjectValue = new AbstractObjectValueElements();
		this.pArrayValues = new ArrayValuesElements();
		this.pArrayType = new ArrayTypeElements();
		this.pEString = new EStringElements();
		this.ePrimitiveValueType = new PrimitiveValueTypeElements();
		this.pEInt = new EIntElements();
		this.pEBoolean = new EBooleanElements();
		this.pEFloat = new EFloatElements();
		this.pEDate = new EDateElements();
		this.pDay = new DayElements();
		this.pMonth = new MonthElements();
		this.pYear = new YearElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.dml.dsl.Dml".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DataPackage dataModel::DataPackage:
	//	('Package' name=EString)?
	//	dataModelCollections+=DataModel*;
	public DataPackageElements getDataPackageAccess() {
		return pDataPackage;
	}
	
	public ParserRule getDataPackageRule() {
		return getDataPackageAccess().getRule();
	}
	
	//DataModel dataModel::DataModel:
	//	'DataModel' name=EString
	//	'{' ('primitives' '{' primitives+=Parameter ("," primitives+=Parameter)* '}')? & ('composites' '{'
	//	composites+=[dataModel::DataModel] ("," composites+=[dataModel::DataModel])* '}')?
	//	'}';
	public DataModelElements getDataModelAccess() {
		return pDataModel;
	}
	
	public ParserRule getDataModelRule() {
		return getDataModelAccess().getRule();
	}
	
	//Parameter dataModel::Parameter:
	//	SimpleType | AbstractType | ArrayType;
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//SimpleType dataModel::SimpleType:
	//	{dataModel::SimpleType} type=PrimitiveValueType name=EString ('=' value=PrimitiveValue)?;
	public SimpleTypeElements getSimpleTypeAccess() {
		return pSimpleType;
	}
	
	public ParserRule getSimpleTypeRule() {
		return getSimpleTypeAccess().getRule();
	}
	
	//AbstractType dataModel::AbstractType:
	//	{dataModel::AbstractType} type=[dataModel::DataModel|QualifiedName] name=EString ('=' value=AbstractObjectValue)?;
	public AbstractTypeElements getAbstractTypeAccess() {
		return pAbstractType;
	}
	
	public ParserRule getAbstractTypeRule() {
		return getAbstractTypeAccess().getRule();
	}
	
	//PrimitiveValue dataModel::PrimitiveValue:
	//	{dataModel::IntValue} intValue=EInt | {dataModel::FloatValue} floatValue=EFloat | {dataModel::StringValue}
	//	stringValue=STRING | {dataModel::BoolValue} boolValue=EBoolean | {dataModel::DateValue} dateValue=EDate | ArrayValues
	//	| AbstractObjectValue;
	public PrimitiveValueElements getPrimitiveValueAccess() {
		return pPrimitiveValue;
	}
	
	public ParserRule getPrimitiveValueRule() {
		return getPrimitiveValueAccess().getRule();
	}
	
	//AbstractObjectValue dataModel::AbstractObjectValue:
	//	{dataModel::AbstractObjectValue} abstractValue=ID;
	public AbstractObjectValueElements getAbstractObjectValueAccess() {
		return pAbstractObjectValue;
	}
	
	public ParserRule getAbstractObjectValueRule() {
		return getAbstractObjectValueAccess().getRule();
	}
	
	//ArrayValues dataModel::ArrayValues:
	//	{dataModel::ArrayValues}
	//	'[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']';
	public ArrayValuesElements getArrayValuesAccess() {
		return pArrayValues;
	}
	
	public ParserRule getArrayValuesRule() {
		return getArrayValuesAccess().getRule();
	}
	
	//ArrayType dataModel::Parameter:
	//	{dataModel::ArrayType} (primitiveType=PrimitiveValueType | dataModelType=[dataModel::DataModel|QualifiedName]) '['
	//	']' name=EString ('=' '[' (values+=PrimitiveValue (',' values+=PrimitiveValue)*)? ']')?;
	public ArrayTypeElements getArrayTypeAccess() {
		return pArrayType;
	}
	
	public ParserRule getArrayTypeRule() {
		return getArrayTypeAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum PrimitiveValueType returns dataModel::PrimitiveValueType:
	//	int | boolean | float | string | object | date;
	public PrimitiveValueTypeElements getPrimitiveValueTypeAccess() {
		return ePrimitiveValueType;
	}
	
	public EnumRule getPrimitiveValueTypeRule() {
		return getPrimitiveValueTypeAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'false' | 'true';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EFloat ecore::EFloat:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//EDate ecore::EDate:
	//	Day '-' Month '-' Year;
	public EDateElements getEDateAccess() {
		return pEDate;
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//Day:
	//	INT;
	public DayElements getDayAccess() {
		return pDay;
	}
	
	public ParserRule getDayRule() {
		return getDayAccess().getRule();
	}
	
	//Month:
	//	INT;
	public MonthElements getMonthAccess() {
		return pMonth;
	}
	
	public ParserRule getMonthRule() {
		return getMonthAccess().getRule();
	}
	
	//Year:
	//	INT;
	public YearElements getYearAccess() {
		return pYear;
	}
	
	public ParserRule getYearRule() {
		return getYearAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
