/*
 * generated by Xtext 2.13.0
 */
package com.smr.activity.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.ui.plugin.AbstractUIPlugin

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */

class ActivityDiagramUiModule extends AbstractActivityDiagramUiModule {
	
	new(AbstractUIPlugin plugin) {
		super(plugin)
	}
	
}
