/**
 * generated by Xtext 2.13.0
 */
package com.dml.dsl;

import com.dml.dsl.DmlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DmlStandaloneSetup extends DmlStandaloneSetupGenerated {
  public static void doSetup() {
    new DmlStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
