/*
 * generated by Xtext 2.15.0
 */
package com.mncml.dsl.ide

import com.mncml.dsl.ide.highlighting.MncLspSemanticHighlightingCalculator
import com.mncml.dsl.ide.quickfix.MncCodeActionService
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator

/**
 * KIDE-owned IDE bindings layered on the generated MNC services.
 */
class MncIdeModule extends AbstractMncIdeModule {

    def Class<? extends ICodeActionService2> bindICodeActionService2() {
        MncCodeActionService
    }

    def Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
        MncLspSemanticHighlightingCalculator
    }
}
