/*
 * generated by Xtext 2.22.0
 */
package com.smr.activity.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ActivityDiagramAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/smr/activity/dsl/parser/antlr/internal/InternalActivityDiagram.tokens");
	}
}
