/*
 * generated by Xtext 2.22.0
 */
package com.smr.activity.dsl.parser.antlr;

import com.google.inject.Inject;
import com.smr.activity.dsl.parser.antlr.internal.InternalActivityDiagramParser;
import com.smr.activity.dsl.services.ActivityDiagramGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ActivityDiagramParser extends AbstractAntlrParser {

	@Inject
	private ActivityDiagramGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalActivityDiagramParser createParser(XtextTokenStream stream) {
		return new InternalActivityDiagramParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ActivityDiagram";
	}

	public ActivityDiagramGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ActivityDiagramGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
